# $NetBSD$

VERSION=	20071029
DISTNAME=	ga_IE
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Irish dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
