# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-syslog-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		system

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		Syslog addon for Io.

ADDON_NAME=		Syslog

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
