# $NetBSD$
#

DISTNAME=		acr-0.2
CATEGORIES=		wip devel
MASTER_SITES=		ftp://ftp.nopcode.org/prj/acr/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.nopcode.org/?t=acr
COMMENT=		Autoconf replacement

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
