# $NetBSD$

BUILDLINK_TREE+=	HUnit

.if !defined(HUNIT_BUILDLINK3_MK)
HUNIT_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.HUnit?=	build
BUILDLINK_API_DEPENDS.HUnit+=	HUnit>=1.2.0.3
BUILDLINK_PKGSRCDIR.HUnit?=	../../wip/HUnit
.endif # HUNIT_BUILDLINK3_MK

BUILDLINK_TREE+=	-HUnit
