# $NetBSD$
#

DISTNAME=	libaura-3.1
CATEGORIES=	devel
MASTER_SITES=	ftp://packages.stura.uni-rostock.de/bsdinstaller/distfiles/

MAINTAINER=	joerg@NetBSD.org
HOMEPAGE=	http://www.bsdinstaller.com/
COMMENT=	Collection of useful C functions

USE_LIBTOOL=	yes

.include "../../mk/bsd.pkg.mk"
