# $NetBSD$

DISTNAME=	fontedit-1.1
CATEGORIES=	sysutils
MASTER_SITES=	http://www.bensmithurst.com/tarballs/

MAINTAINER=	lkundrak@skosi.org
COMMENT=	Converts console fonts between binary and editable

.include "../../mk/bsd.pkg.mk"
