# $NetBSD$

DISTNAME=	NZMATH-1.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:tl}
CATEGORIES=	math python
MASTER_SITES=	http://heanet.dl.sourceforge.net/project/nzmath/nzmath/NZMATH-1.2.0/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://tnt.math.metro-u.ac.jp/nzmath/
COMMENT=	Number theory oriented calculation system
LICENSE=	modified-bsd

USE_LANGUAGES=	# none
PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
