# $NetBSD: Makefile,v 1.15 2011/04/22 13:42:21 obache Exp $

.include "../../wip/xfce48/Makefile.common"

DISTNAME=	xfce4-fsguard-plugin-1.0.0
#PKGREVISION=	1
CATEGORIES=	sysutils
COMMENT=	Xfce disk space plugin

MASTER_SITES=	http://archive.xfce.org/src/panel-plugins/xfce4-fsguard-plugin/1.0/

.include "../../x11/xfce4-panel/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
