# $NetBSD$
#

DISTNAME=		cygwin-4.2.1
CATEGORIES=		cross
MASTER_SITES=		# empty
DISTFILES=		# empty

MAINTAINER=		makoto@ki.nu
HOMEPAGE=		http://www.cygwin.com/
COMMENT=		GNU C Compiler for win32 cross development
LICENSE=		gnu-gpl-v3

#.include "../../wip/mingw-binutils/buildlink3.mk"
#.include "../../wip/mingw-gcc/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
