# $NetBSD$
#

DISTNAME=	HTTP-3001.0.4
PKGNAME=	hs-HTTP-3001.0.4
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_HASKELL_HACKAGE:=HTTP/3001.0.4/}

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.haskell.org/http/
COMMENT=	Haskell library for client-side HTTP

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk" # This should be "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
