# $NetBSD$
#

DISTNAME=	HTTP-4000.0.8
CATEGORIES=	www

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell library for client-side HTTP

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-network/buildlink3.mk"
.include "../../wip/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
