# $NetBSD$
#

DISTNAME=	terminfo-0.3.1.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell bindings to the terminfo library
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/curses.buildlink3.mk"
.include "../../wip/hs-extensible-exceptions/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
