# $NetBSD$

BUILDLINK_TREE+=	hs-OpenGLRaw

.if !defined(HS_OPENGLRAW_BUILDLINK3_MK)
HS_OPENGLRAW_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.hs-OpenGLRaw+=	hs-OpenGLRaw>=1.1.0.0
BUILDLINK_PKGSRCDIR.hs-OpenGLRaw?=	../../wip/hs-OpenGLRaw

.endif	# HS_OPENGLRAW_BUILDLINK3_MK

BUILDLINK_TREE+=	-hs-OpenGLRaw
