# $NetBSD$
#

DISTNAME=	OpenGLRaw-1.1.0.0
CATEGORIES=	graphics

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.haskell.org/HOpenGL/
COMMENT=	Raw binding for the OpenGL graphics system
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../graphics/MesaLib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
