# $NetBSD$
#

DISTNAME=	text-0.11.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficient packed Unicode text type
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-deepseq/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
