# $NetBSD: Makefile,v 1.1 2015/01/19 20:37:07 fhajny Exp $

DISTNAME=	chawan-0.0.4
CATEGORIES=	textproc

MAINTAINER=	ishit@users.sourceforge.net
HOMEPAGE=	https://rubygems.org/gems/chawan/
COMMENT=	Cup for chasen that provides an easy to use for extracting Japanese
LICENSE=	generic-nonlicense

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
