# $NetBSD$
#

DISTNAME=	miniupnpc-1.6
CATEGORIES=	net
MASTER_SITES=	http://miniupnp.tuxfamily.org/files/

MAINTAINER=	matias@dotbsd.org
HOMEPAGE=	http://miniupnp.tuxfamily.org/files/
COMMENT=	Client and library for UPnP IGD services

LICENSE=	modified-bsd

USE_TOOLS+=	gmake

.include "../../mk/bsd.pkg.mk"
