# $NetBSD$
#

DISTNAME=	miniupnpc-1.0-RC11
PKGNAME=	miniupnpc-1.0nb11
CATEGORIES=	net
MASTER_SITES=	http://miniupnp.tuxfamily.org/files/

MAINTAINER=	matias@dotbsd.org
HOMEPAGE=	http://miniupnp.tuxfamily.org/files/
COMMENT=	Client and library for UPnP IGD services

USE_TOOLS+=     gmake

.include "../../mk/bsd.pkg.mk"
