# $NetBSD$
#

DISTNAME=	convertible-1.0.10.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Typeclasses and instances for converting between types

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
