# $NetBSD$
#

DISTNAME=		jpgtn-2.06
CATEGORIES=		wip graphics
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=jpgtn/}

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://jpgtn.sourceforge.net/
COMMENT=		A thumbnail generator for JPEG images

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../graphics/jpeg/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
