# $NetBSD: Makefile.depends,v 1.18 2007/08/15 13:23:27 rillig Exp $
#

DEPENDS+=	mplayer-share>=${MPLAYER_VERSION}:../../wip/mplayer-snapshot-share

.include "../../converters/libiconv/buildlink3.mk"
.include "../../fonts/fontconfig/buildlink3.mk"
.include "../../graphics/freetype2/buildlink3.mk"
.include "../../x11/libX11/buildlink3.mk"
