# $NetBSD$
#

DISTNAME=	julio-0.4.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	http://www.lifl.fr/~marvie/download/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://www.lifl.fr/~marvie/software/julio.html
COMMENT=	Python Implementation of the Fractal Specification
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none
PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
