# $NetBSD$

DISTNAME=	l2-0.9.13
PKGNAME=	ossp-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.ossp.org/pkg/lib/l2/

MAINTAINER=	obache@users.sourceforge.net
HOMEPAGE=	http://www.ossp.org/pkg/lib/l2/
COMMENT=	OSSP l2 - Flexible Logging

GNU_CONFIGURE=		yes
USE_LIBTOOL=		yes

TEST_TARGET=		check

.include "../../mk/bsd.pkg.mk"
