# $NetBSD$
#

DISTNAME=	tagged-0.1.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Provides newtype wrappers for phantom types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-data-default/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
