# $NetBSD$
#

DISTNAME=	tagged-0.4.5
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell 98 phantom types to avoid unsafely passing dummy arguments
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
