# $NetBSD$
#

DISTNAME=	OpenGL-2.4.0.1
CATEGORIES=	graphics

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.haskell.org/HOpenGL/
COMMENT=	Binding for the OpenGL graphics system
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-GLURaw/buildlink3.mk"
.include "../../wip/hs-ObjectName/buildlink3.mk"
.include "../../wip/hs-OpenGLRaw/buildlink3.mk"
.include "../../wip/hs-StateVar/buildlink3.mk"
.include "../../wip/hs-Tensor/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
