# $NetBSD$
#

DISTNAME=		gtypist-2.7
CATEGORIES=		wip textproc
MASTER_SITES=		ftp://ftp.gnu.org/gnu/gtypist/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		ftp://ftp.gnu.org/gnu/gtypist/
COMMENT=		Universal typing tutor

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
