# $NetBSD$

DISTNAME=	jsonpath-0.54
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc python
MASTER_SITES=	http://www.ultimate.com/phil/python/download/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://www.ultimate.com/phil/python/#jsonpath
COMMENT=	XPath for JSON
LICENSE=	mit

USE_LANGUAGES=	# none

PYDISTUTILSPKG= yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
