# $NetBSD$
#

DISTNAME=		IPython-0.5.0
CATEGORIES=		devel
MASTER_SITES=		http://ipython.scipy.org/dist/

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://ipython.scipy.org/dist/
COMMENT=		Interactive, enhanced Python shell

USE_BUILDLINK2=		yes
PY_PATCHPLIST=		yes
PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../lang/python/application.mk"
.include "../../mk/bsd.pkg.mk"
