# $NetBSD$
#

DISTNAME=	explicit-exception-0.1.6
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Exceptions which are explicit in the type signature
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
