# $NetBSD$
#

DISTNAME=	dlist-0.5
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Differences lists
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
