# $NetBSD$

PKGNAME=	hdf5-${HDF5_VER}
COMMENT=	Hierarchical Data Format (new generation)

.include "Makefile.common"
.include "options.mk"

.include "../../devel/zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
