# $NetBSD$

DISTNAME=	review-1.4.0
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/kmuto/review/wiki
COMMENT=	Converts single Markup Text into various publishing format
LICENSE=	gnu-gpl-v2

.include "../../lang/ruby/gem.mk"
.include "../../lang/ruby/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
