# $NetBSD$

DISTNAME=	HTML_Select-1.2

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://pear.php.net/package/HTML_Common
COMMENT=	HTML_Select is a PHP class for generating HTML form select elements

DEPENDS+=	pear-HTML_Common>=1.1:../../wip/pear-HTML_Common

.include "../../wip/php4/pear.mk"
.include "../../mk/bsd.pkg.mk"
