# $NetBSD$
#

DISTNAME=	QuickCheck-2.4.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Automatic testing of Haskell programs
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
