# $NetBSD$

DISTNAME=	semigroups-0.15.2
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Anything that associates
LICENSE=	2-clause-bsd

.include "../../mk/haskell.mk"
.include "../../devel/hs-hashable/buildlink3.mk"
.include "../../math/hs-nats/buildlink3.mk"
.include "../../devel/hs-text/buildlink3.mk"
.include "../../devel/hs-unordered-containers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
