# $NetBSD$
#

DISTNAME=		STonX-0.6.7.6
CATEGORIES=		emulators
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=stonx/}

MAINTAINER=		xmor61@users.sourceforge.net
HOMEPAGE=		http://stonx.sourceforge.net/
COMMENT=		Atari ST Emulator

USE_X11=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
