# $NetBSD$
#

DISTNAME=		STonX-0.6.7.6
CATEGORIES=		emulators
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=stonx/}

MAINTAINER=		xmor61@users.sourceforge.net
HOMEPAGE=		http://stonx.sourceforge.net/
COMMENT=		Atari ST Emulator

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../pkgtools/x11-links/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
