# $NetBSD$

DISTNAME=		fisg-0.2.0
WRKSRC=			${WRKDIR}/${DISTNAME}/src
CATEGORIES=		chat textproc
MASTER_SITES=		http://www.tnsp.org/files/

MAINTAINER=		snj@pobox.com
HOMEPAGE=		http://www.tnsp.org/fisg.php
COMMENT=		Fast IRC statistics generator

USE_BUILDLINK2=		YES
USE_GMAKE=		YES

.include "../../mk/bsd.pkg.mk"
