# $NetBSD$
#

DISTNAME=       amap-2.1
CATEGORIES=     net security
MASTER_SITES=   http://www.thc.org/releases/

MAINTAINER=     adam@monkeybyte.org
HOMEPAGE=       http://www.thc.org/
COMMENT=        Applications and Services scanner

USE_BUILDLINK2=	YES
HAS_CONFIGURE=	YES

.include "../../security/openssl/buildlink2.mk"

.include "../../mk/bsd.pkg.mk"
