# $NetBSD$
#

DISTNAME=	control-monad-failure-0.7.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Class for monads which can fail with an error
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-failure/buildlink3.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
