# $NetBSD$
#
DISTNAME=		tf-50b7
CATEGORIES=		net
MASTER_SITES=		http://tcp.com/pub/mud/Clients/tinyfugue/

MAINTAINER=		martijn.van.buul@gmail.com
HOMEPAGE=		http://tcp.com/pub/mud/Clients/tinyfugue/
COMMENT=		Beta-version of tinyfugue

PKG_DESTDIR_SUPPORT=	none

WRKSRC=			${WRKDIR}/tf-50b7

GNU_CONFIGURE=		yes
USE_LANGUAGES=		c

.include "../../mk/bsd.pkg.mk"
