# $NetBSD$
#
DISTNAME=		tf-50b6
CATEGORIES=		net
PKGREVISION=		1
MASTER_SITES=		http://ftp.tcp.com/pub/mud/Clients/tinyfugue/

MAINTAINER=		martijn.van.buul@gmail.com
HOMEPAGE=		http://ftp.tcp.com/pub/mud/Clients/tinyfugue/
COMMENT=		Beta-version of tinyfugue

WRKSRC=			${WRKDIR}/tf-50b6

GNU_CONFIGURE=		yes
USE_LANGUAGES=		c

.include "../../mk/bsd.pkg.mk"
