# $NetBSD$
#

DISTNAME=		tf-50b6
CATEGORIES=		net
MASTER_SITES=		http://ftp.tcp.com/pub/mud/Clients/tinyfugue/

MAINTAINER=		martijn.van.buul@gmail.com
HOMEPAGE=		http://ftp.tcp.com/pub/mud/Clients/tinyfugue/
COMMENT=		Beta-version of tinyfugue

WRKSRC=			${WRKDIR}/tf-50b6

USE_BUILDLINK3=		yes
GNU_CONFIGURE=		yes
USE_LANGUAGES=		c

.include "../../mk/bsd.pkg.mk"
