# $NetBSD$
#

DISTNAME=		qcad-manual-cs-2.0.4.0-1.html
PKGNAME=		qcad-manual-cs-2.0.4.0

.include "../qcad/Makefile.common"

COMMENT=		Online manual for QCad 2D CAD package, Czech

CONFLICTS=		qcad-manual-{[!c]?,?[!s]}-[0-9]*

.include "../qcad-manual-en/Makefile.common"
