# $NetBSD$
#

DISTNAME=	Tensor-1.0.0.1
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.haskell.org/HOpenGL/
COMMENT=	Tensor data types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
