# $NetBSD$
#

DISTNAME=		qcad-manual-de-2.0.4.0-1.html
PKGNAME=		qcad-manual-de-2.0.4.0

.include "../qcad/Makefile.common"

COMMENT=		Online manual for QCad 2D CAD package, German

CONFLICTS=		qcad-manual-{[!d]?,?[!e]}-[0-9]*

.include "../qcad-manual-en/Makefile.common"
