# $NetBSD$
#

DISTNAME=	hscolour-1.20.3
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Colourise Haskell code
LICENSE=	gnu-gpl-v2

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
