# $NetBSD$
#

DISTNAME=	gio-0.12.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Binding to the GIO
LICENSE=	gnu-lgpl-v2.1

.include "../../wip/mk/haskell.mk"
.include "../../wip/gtk2hs-buildtools/buildlink3.mk"
.include "../../wip/hs-glib/buildlink3.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
