# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
QUICKCHECK_BUILDLINK3_MK:=	${QUICKCHECK_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	QuickCheck
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NQuickCheck}
BUILDLINK_PACKAGES+=	QuickCheck
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}QuickCheck

.if ${QUICKCHECK_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.QuickCheck?=	build
BUILDLINK_API_DEPENDS.QuickCheck+=	QuickCheck>=2.1.0.1
BUILDLINK_PKGSRCDIR.QuickCheck?=	../../wip/QuickCheck
.endif	# QUICKCHECK_BUILDLINK3_MK

.include "../../wip/hs-mtl/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
