# $NetBSD$
#

DISTNAME=	QuickCheck-2.1.0.1
PKGREVISION=	1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.cs.chalmers.se/~koen
COMMENT=	Automatic testing of Haskell programs

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
