# $NetBSD$
#

DISTNAME=		bscript-0.3
CATEGORIES=		lang
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=bscript/}

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://bscript.sourceforge.net/
COMMENT=		Portable, fast, lightweight BASIC interpreter
LICENSE=		gnu-gpl-v2

PKG_DESTDIR_SUPPORT=	user-destdir

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
