# $NetBSD$
#

DISTNAME=		bscript-0.3
CATEGORIES=		wip lang
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=bscript/}

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://bscript.sourceforge.net/
COMMENT=		Portable, fast, lightweight BASIC interpreter

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
