# $NetBSD$
#

DISTNAME=	strict-0.3.2
CATEGORIES=	devel
LICENSE=	modified-bsd

MAINTAINER=	pho@cielonegro.org
COMMENT=	Strict versions of some standard Haskell data types

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
