# $NetBSD$
#

DISTNAME=	stream-fusion-0.1.2.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Faster Haskell lists using stream fusion
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
