# $NetBSD$
#

DISTNAME=	unix-compat-0.2.1.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Portable POSIX-compatibility layer
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
