# $NetBSD$
#

DISTNAME=	fclabels-0.11.1.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	First class accessor labels implemented as lenses
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
