# $NetBSD$
#

DISTNAME=	chunks-2007.4.18
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Simple template library with static safety
LICENSE=	gnu-lgpl-v2.1

.include "../../wip/mk/haskell.mk"
.include "../../textproc/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
