# $NetBSD$
#

.include "../../wip/mecab/Makefile.common"

DISTNAME=	mecab-jumandic-5.1-20070304
PKGNAME=	mecab-jumandic-5.1.20070304

COMMENT=	Japanese Morphological Dictionary for MeCab

GNU_CONFIGURE=	yes

UNLIMIT_RESOURCES=	datasize

.include "../../wip/mecab-base/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
