# $NetBSD$
#

DISTNAME=		intel2gas-1.3.3
CATEGORIES=		devel
MASTER_SITES=		http://www.niksula.cs.hut.fi/~mtiihone/intel2gas/

MAINTAINER=		ccatrian@eml.cc
HOMEPAGE=		http://www.niksula.cs.hut.fi/~mtiihone/intel2gas/
COMMENT=		Convert nasm source files to gas source files

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
