# $NetBSD$
#

DISTNAME=		orm-0.16
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		databases
MASTER_SITES=		http://tux4web.de/computer/software/orm/download/

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://www.tux4web.de/category/computer-programming/orm/
COMMENT=		Object-relational membrane for Python

PKG_DESTDIR_SUPPORT=	none

PY_PATCHPLIST=		yes
PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
