# $NetBSD$
#

DISTNAME=		orm-0.16
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		databases
MASTER_SITES=		http://tux4web.de/computer/software/orm/download/

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://tux4web.de/computer/software/orm
COMMENT=		Object-relational membrane for Python

PY_PATCHPLIST=		yes
PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
