# $NetBSD$

DISTNAME=	toptesi.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-5.76
TEXLIVE_REV=	32081

MAINTAINER=	leot1990@users.sourceforge.net
COMMENT=	Documentation for tex-toptesi

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
