# $NetBSD$

VERSION=	20030101
DISTNAME=	cs_CZ
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Czech dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
