# $NetBSD$

VERSION=	20030101
DISTNAME=	cs_CZ
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Czech dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
