#! /bin/sh
#
# $NetBSD$

case "$2" in
        DEINSTALL) cat <<EOF

==========================================================================

Note that the inn data directory (@INNDATA@) is NOT deleted during
the package deinstallation. Please remove this directory and all its
contents manually if it is no longer needed.

==========================================================================

EOF
        ;;
esac

exit 0
