#!/bin/sh
#
# $NetBSD$

if [ "$2" != "POST-INSTALL" ]; then
  exit 0
fi

DIRS="etc run tmp"
for DIR in $DIRS; do
	if [ ! -d @INNDATA@/$DIR ]; then
		install -d -o news -g news -m 775 @INNDATA@/$DIR
	fi
done

ETC="nnrp.access"
for FILE in $ETC; do 
	if [ ! -f @INNDATA@/etc/$FILE ]; then
		install -c -o news -g news -m 664 \
		    ${PKG_PREFIX}/share/examples/inn/$FILE @INNDATA@/etc
	fi
done

exit 0
