# $NetBSD$
#

DISTNAME=	haskell-lexer-1.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fully compliant Haskell 98 lexer

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
