# $NetBSD$
#

DISTNAME=	dexml-0.3.6
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc python
MASTER_SITES=	http://pypi.python.org/packages/source/d/dexml/

MAINTAINER=	wenheping@gmail.com
HOMEPAGE=	http://www.rfk.id.au/software/
COMMENT=	Dead-simple Object-XML mapper for Python
LICENSE=	mit

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
