# $NetBSD$
#

DISTNAME=	colorize-haskell-1.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Highligt Haskell source

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-ansi-terminal/buildlink3.mk"
.include "../../wip/hs-haskell-lexer/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
