# $NetBSD: Makefile.common,v 1.2 2011/07/08 17:23:05 drochner Exp $
#
# used by x11/py-vte/Makefile

DISTNAME=	vte-0.40.2
MASTER_SITES=	${MASTER_SITE_GITHUB:=GNOME/}

HOMEPAGE=	http://www.gnome.org/
LICENSE=	gnu-lgpl-v2

DISTINFO_FILE=		${.CURDIR}/../../wip/vte/distinfo
PATCHDIR=		${.CURDIR}/../../wip/vte/patches

PKGCONFIG_OVERRIDE+=	vte.pc.in
