# $NetBSD$
#

DISTNAME=	byacc-20001120
CATEGORIES=	devel
MASTER_SITES=	ftp://invisible-island.net/byacc/
EXTRACT_SUFX=	.tgz

MAINTAINER=	tech-pkg@netbsd.org
HOMEPAGE=	http://dickey.his.com/byacc/byacc.html
COMMENT=	Berkeley Yacc

.include "../../mk/bsd.pkg.mk"
