# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-random-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		devel

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		Random addon for Io.

ADDON_NAME=		Random

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
