# $NetBSD$

DISTNAME=	supercat-0.5.5
CATEGORIES=	sysutils
MASTER_SITES=	http://supercat.nosredna.net/

MAINTAINER=	youri.mout@gmail.com
HOMEPAGE=	http://supercat.nosredna.net/
COMMENT=	Supercat is a text colorizer
LICENSE=	gnu-gpl-v3

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+= --with-system-directory=${PREFIX}/share/supercat

.include "../../mk/bsd.pkg.mk"
