# $NetBSD$
#

DISTNAME=	HsHyperEstraier-0.4
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	HyperEstraier binding for Haskell
LICENSE=	public-domain

.include "../../textproc/hyperestraier/buildlink3.mk"
CONFIGURE_ARGS=

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-base-unicode-symbols/buildlink3.mk"
.include "../../wip/hs-network/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
