# $NetBSD$
#

DISTNAME=	vector-0.7.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell Efficient Arrays
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-primitive/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
