# $NetBSD$

DISTNAME=	vector-0.10.9.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficient Arrays for Haskell
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../wip/hs-primitive/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
