# $NetBSD$

.include "../xfce4/Makefile.common"

PKGNAME=	libxfce4mcs-${XFCE4_VERSION}
COMMENT=	XFce4 settings management library

WRKSRC=		${WRKDIR}/xfce-devel/libxfce4mcs

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../wip/libxfce4util/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
