# $NetBSD$

.include "../xfce4/Makefile.common"

DISTNAME=	libxfce4mcs-${XFCE4_VERSION}
COMMENT=	XFce4 settings management library

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../wip/libxfce4util/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
