# $NetBSD$
#

DISTNAME=		testdisk-5.8
CATEGORIES=		wip sysutils
MASTER_SITES=		http://www.cgsecurity.org/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.cgsecurity.org/
COMMENT=		Tool to check and undelete partitions

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
