# $NetBSD$
#

DISTNAME=		testdisk-6.10
CATEGORIES=		sysutils
MASTER_SITES=		http://www.cgsecurity.org/
EXTRACT_SUFX=		.tar.bz2

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.cgsecurity.org/wiki/TestDisk
COMMENT=		Tool to check and undelete partitions

GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
