# $NetBSD$

DISTNAME=	Image-ExifTool-5.46
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	graphics perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=Image/}

MAINTAINER=	kuli0020@umn.edu
HOMEPAGE=	http://www.sno.phy.queensu.ca/~phil/exiftool/
COMMENT=	Perl module for getting EXIF data from image files

PERL5_PACKLIST= auto/Image/ExifTool/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
