# $NetBSD$

.include "../../wip/heirloom-common/Makefile.prog2.common"

PKGNAME=	heirloom-cal-${HEIRLOOM_VER}
CATEGORIES=	textproc

MAKE_FLAGS+=	SUBDIRS="build cal"

.include "../../wip/heirloom-libcommon/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
