# $NetBSD$
#

DISTNAME=	google-perftools-1.3
CATEGORIES=	devel
MASTER_SITES=	http://google-perftools.googlecode.com/files/

MAINTAINER=	vle@gmx.net
HOMEPAGE=	http://google-perftools.googlecode.com/
COMMENT=	Multi-threaded malloc() and nifty performance analysis tools

LICENSE=	modified-bsd

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=		yes
USE_LIBTOOL=		yes
USE_LANGUAGES=		c c++

.include "../../mk/bsd.pkg.mk"
