# $NetBSD$
#

DISTNAME=		guilerxspencer-1.2
CATEGORIES=		devel
MASTER_SITES=		http://arglist.com/guile/${DISTNAME}/

MAINTAINER=		ben@NetBSD.org
HOMEPAGE=		http://arglist.com/guile/
COMMENT=		Guile bindings for Henry Spencer's regex

USE_BUILDLINK3=		yes
GNU_CONFIGURE=		yes
INSTALLATION_DIRS=	share/guile/site

.include "../../lang/guile/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
