# $NetBSD$
#

CATEGORIES=             databases math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/VR.html}
COMMENT=		Functions and datasets for 'Modern Applied Statistics with S'

R_PKGNAME=              VR
R_PKGVER=               7.2-4

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
