# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
EDITLINE_BUILDLINK3_MK:=	${EDITLINE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	editline
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Neditline}
BUILDLINK_PACKAGES+=	editline
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}editline

.if ${EDITLINE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.editline+=	editline>=2.11
BUILDLINK_PKGSRCDIR.editline?=	../../wip/editline
.endif	# EDITLINE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
