# $NetBSD$

DISTNAME=	nimfa-1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://pypi.python.org/packages/source/n/nimfa/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://nimfa.biolab.si
COMMENT=	Python Library for Nonnegative Matrix Factorization Techniques
LICENSE=	gnu-gpl-v3

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
