# $NetBSD$

.include "../xfce4/Makefile.common"

DISTNAME=	xfce4-systray-${XFCE4_VERSION}
CATEGORIES=	sysutils
COMMENT=	XFce4 systray plugin

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../textproc/libxml2/buildlink2.mk"
.include "../../wip/xfce4-panel/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
