#!/bin/sh
# $NetBSD$

PKGNAME=$1
STAGE=$2

TEXMFCNF=@TEXMFDIRS@/web2c/texmf.cnf

case ${STAGE} in
DEINSTALL)
	;;
POST-DEINSTALL)
	echo "Edit ${TEXMFCNF}"
	sed -e "/ttf2pk/d" ${TEXMFCNF} > ${TEXMFCNF}.tmp
	sed -e "/ttf2tfm/d" ${TEXMFCNF}.tmp > ${TEXMFCNF}
	rm -f ${TEXMFCNF}.tmp
	;;
*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
