#!/bin/sh
# $NetBSD$

TEXMFCNF=@TEXMFDIRS@/web2c/texmf.cnf

case ${STAGE} in
PRE-INSTALL)
	;;
POST-INSTALL)
	echo "Edit ${TEXMFCNF}"
	echo "% ttf2pk data directory"              >> ${TEXMFCNF}
	echo "TTF2PKINPUTS = \$TEXMF/ttf2tfm/base"  >> ${TEXMFCNF}
	echo "% ttf2tfm data directory"             >> ${TEXMFCNF}
	echo "TTF2TFMINPUTS = \$TEXMF/ttf2tfm/base" >> ${TEXMFCNF}
	;;
*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
