# $NetBSD$

DISTNAME=	xmpp4r-0.5
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	chat

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://home.gna.org/xmpp4r/
COMMENT=	XMPP/Jabber library for Ruby
LICENSE=	ruby-license

PKG_DESTDIR_SUPPORT=	user-destdir

GEM_BUILD=	gemspec

.include "../../misc/rubygems/rubygem.mk"
.include "../../mk/bsd.pkg.mk"
