# $NetBSD$

DISTNAME=	xmpp4r-0.5.6
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	chat

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://xmpp4r.github.io/
COMMENT=	XMPP/Jabber library for Ruby
LICENSE=	ruby-license

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
