# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBMAA_BUILDLINK3_MK:=	${LIBMAA_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libmaa
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmaa}
BUILDLINK_PACKAGES+=	libmaa
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libmaa

.if ${LIBMAA_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libmaa+=	libmaa>=0.990
BUILDLINK_PKGSRCDIR.libmaa?=	../../wip/libmaa
.endif	# LIBMAA_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
