# $NetBSD$

DISTNAME=	citeproc-hs-0.3.8
CATEGORIES=	textproc

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Citation Style Language implementation in Haskell
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-json/buildlink3.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-pandoc-types/buildlink3.mk"
.include "../../wip/hs-parsec/buildlink3.mk"
.include "../../wip/hs-syb/buildlink3.mk"
.include "../../wip/hs-utf8-string/buildlink3.mk"
.include "../../wip/hs-xml/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
