# $NetBSD$

DISTNAME=	timezone-olson-0.1.4
CATEGORIES=	time

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Pure Haskell parser and renderer for binary Olson timezone files
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-extensible-exceptions/buildlink3.mk"
.include "../../wip/hs-timezone-series/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
