# $NetBSD$

VERSION=	20070106
DISTNAME=	da_DK
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Danish dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
