# $NetBSD$
#

DISTNAME=	haserl-0.8.0
CATEGORIES=	lang www
MASTER_SITES=	http://downloads.sourceforge.net/haserl/

MAINTAINER=	xmor61@users.sourceforge.net
HOMEPAGE=	http://haserl.sourceforge.net/
COMMENT=	CGI wrapper for mixing HTML with shell script

GNU_CONFIGURE=	yes

PKG_DESTDIR_SUPPORT=	none

.include "../../mk/bsd.pkg.mk"
