# $NetBSD$

DISTNAME=	HTML_Common-1.2.1

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://pear.php.net/package/HTML_Common
COMMENT=	PEAR::HTML_Common is a base PHP class for other HTML classes

.include "../../wip/php4/pear.mk"
.include "../../mk/bsd.pkg.mk"
