# $NetBSD$
#

PEAR_CHANNEL=		pear.horde.org
PEAR_CHANNEL_ALIAS=	horde
PEAR_CHANNEL_VERSION=	2012.05.11

MAINTAINER=		frederic@fauberteau.org

.include "../../wip/mk/pear-channel.mk"
.include "../../mk/bsd.pkg.mk"

