# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TINYSVM_BUILDLINK3_MK:=	${TINYSVM_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	TinySVM
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NTinySVM}
BUILDLINK_PACKAGES+=	TinySVM
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}TinySVM

.if ${TINYSVM_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.TinySVM+=	TinySVM>=0.09
BUILDLINK_PKGSRCDIR.TinySVM?=	../../wip/TinySVM
.endif	# TINYSVM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
