# $NetBSD$

DISTNAME=	uptime-3.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	sysutils
MASTER_SITES=	https://pypi.python.org/packages/source/u/uptime/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/Cairnarvon/uptime
COMMENT=	Cross-platform uptime library
LICENSE=	modified-bsd

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
