# $NetBSD$

DISTNAME=	ap-utils-1.3.2-pre3
PKGNAME=	aputils-1.3.2pre3
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=ap-utils/}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	pancake@phreaker.net
HOMEPAGE=	http://ap-utils.polesye.net/
COMMENT=	Wireless Access Point Utilites for Unix

GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include 	"../../mk/bsd.pkg.mk"
