# $NetBSD$
#

DISTNAME=	uniplate-1.2.0.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www-users.cs.york.ac.uk/~ndm/uniplate/
COMMENT=	Haskell boilerplate removal library

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
