# $NetBSD$
#

DISTNAME=		wireless_tools.27
PKGNAME=		wireless-tools-27
CATEGORIES=		net linux
MASTER_SITES=		http://pcmcia-cs.sourceforge.net/ftp/contrib/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://pcmcia-cs.sourceforge.net/ftp/contrib/
COMMENT=		Tools for manipulating Linux Wireless Extensions

PKG_DESTDIR_SUPPORT= 	none

ONLY_FOR_PLATFORM=	Linux-*-*
USE_TOOLS+=		gmake

.include "../../mk/bsd.pkg.mk"
