# $NetBSD: Makefile,v 1.25 2011/04/22 13:45:19 obache Exp $

.include "../../wip/xfce48/Makefile.common"

THEMES_VERSION=	4.6.0

DISTNAME=	xfwm4-themes-${THEMES_VERSION}
PKGNAME=	xfce4-wm-themes-${THEMES_VERSION}
PKGREVISION=	5
CATEGORIES=	wm
COMMENT=	Xfce window manager themes

MASTER_SITES=	http://archive.xfce.org/src/art/xfwm4-themes/4.6/

USE_LANGUAGES=	#empty

MAKE_DIRS+=	${PREFIX}/share/themes/Xfce

.include "../../mk/bsd.pkg.mk"
