# $NetBSD$

.include "../xfce4/Makefile.common"

PKGNAME=	xfce4-wm-themes-${XFCE4_VERSION}
DISTNAME=	xfwm4-themes-${XFCE4_VERSION}
CATEGORIES=	wm
COMMENT=	XFce4 window manager themes

.include "../../wip/xfce4-wm/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
