# $NetBSD$

.include "../xfce4/Makefile.common"

PKGNAME=	xfce4-wm-themes-${XFCE4_VERSION}
DISTNAME=	xfwm4-themes-${XFCE4_VERSION}
COMMENT=	XFce4 window manager themes

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../textproc/libxml2/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
