# $NetBSD$
#

DISTNAME=		rss2html-0.5
CATEGORIES=		wip converters
MASTER_SITES=		ftp://ftp.nopcode.org/prj/rss2html/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.nopcode.org/?t=rss2html
COMMENT=		RSS to HTML converter

PKG_INSTALLATION_TYPES=	overwrite pkgviews

USE_BUILDLINK3=		YES
USE_GNU_TOOLS+=		make

INSTALLATION_DIRS+=	bin

.include "../../mk/bsd.pkg.mk"
