# $NetBSD$
#

DISTNAME=	transformers-base-0.4.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Lift computations from the bottom of a transformer stack
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
