# $NetBSD$
#

CATEGORIES=             databases math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/PHYLOGR.html}
COMMENT=		Manipulation of phylogenetically simulated data sets using GLS

R_PKGNAME=              PHYLOGR
R_PKGVER=               1.0.3

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
