# $NetBSD$
#

DISTNAME=	haskelldb-0.12
CATEGORIES=	databases

MAINTAINER=	pho@cielonegro.org
COMMENT=	SQL unwrapper for Haskell

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
