# $NetBSD$
#

DISTNAME=		MP3-Mplib-0.02
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		audio
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=../../authors/id/V/VP/VPARSEVAL/}

MAINTAINER=		bartosz.kuzma@gmail.com
COMMENT=		Speedy access to id3v1 and id3v2 tags

PERL5_PACKLIST=		auto/MP3/Mplib/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
