# $NetBSD$
#

.include "Makefile.common"

COMMENT+=		(GTK+ 1.0 interface)

CONFLICTS=		pornview-gtk2-[0-9]*

.include "../../graphics/gdk-pixbuf/buildlink3.mk"
.include "../../x11/gtk/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
