# $NetBSD$
#

DISTNAME=		LibVNCServer-0.7pre
PKGNAME=		libvncserver-0.7
CATEGORIES=		net
MASTER_SITES=		http://libvncserver.sourceforge.net/

MAINTAINER=		dhowland@users.sourceforge.net
HOMEPAGE=		http://libvncserver.sourceforge.net/
COMMENT=		Library for creating quick and easy VNC applications

GNU_CONFIGURE=		yes

.include "../../mk/bsd.prefs.mk"
.include "../../mk/bsd.pkg.mk"
