# $NetBSD$
#

DISTNAME=	srvx-1.1.3
CATEGORIES=	chat
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=srvx/}

MAINTAINER=	virtus@wanadoo.nl
HOMEPAGE=	http://srvx.sourceforge.net/
COMMENT=	Srvx IRC services

PKG_DESTDIR_SUPPORT=	none

USE_LIBTOOL=	YES
GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
