# $NetBSD$
#

.include "../../wip/pkg_online/Makefile.common"

CATEGORIES=	pkgtools meta-pkgs
PKGREVISION=	2

DEPENDS+=	pkg_online-client-[0-9]*:../../wip/pkg_online-client
DEPENDS+=	pkg_online-server-[0-9]*:../../wip/pkg_online-server

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
