# $NetBSD$
#

.include "../../wip/pkg_online/Makefile.common"

CATEGORIES=	pkgtools meta-pkgs

DEPENDS+=	pkg_online-client-${VERSION}nb1:../../wip/pkg_online-client
DEPENDS+=	pkg_online-server-${VERSION}nb1:../../wip/pkg_online-server

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
