# $NetBSD$

VERSION=	0.9.3
DISTNAME=	ConfigArgParse-${VERSION}
PKGNAME=	${PYPKGPREFIX}-configargparse-${VERSION}
CATEGORIES=	devel
MASTER_SITES=	https://pypi.python.org/packages/source/C/ConfigArgParse/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/bw2/ConfigArgParse
COMMENT=	Argparse-like with config files or environment variables support
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
