# $NetBSD: Makefile.common,v 1.8 2004/08/18 23:03:44 ben Exp $
# $Id: Makefile.common,v 1.3 2006/04/20 07:08:27 ahallmann Exp $

CFENGINE_VERSION= 2.1.17
DISTNAME=	cfengine-${CFENGINE_VERSION}
CATEGORIES=	sysutils net
MASTER_SITES=	ftp://ftp.iu.hio.no/pub/cfengine/ \
		http://sunsite.utk.edu/ftp/pub/cfengine/cfengine-ftp/

MAINTAINER=	hallmann@ahatec.de
HOMEPAGE=	http://www.cfengine.org/

DISTINFO_FILE=	${.CURDIR}/distinfo
PATCHDIR=	${.CURDIR}/patches
