# $NetBSD: Makefile.common,v 1.8 2004/08/18 23:03:44 ben Exp $
#

CFENGINE_VERSION= 2.1.16
DISTNAME=	cfengine-${CFENGINE_VERSION}
CATEGORIES=	sysutils net
MASTER_SITES=	ftp://ftp.iu.hio.no/pub/cfengine/ \
		http://sunsite.utk.edu/ftp/pub/cfengine/cfengine-ftp/

MAINTAINER=	hallmann@ahatec.de
HOMEPAGE=	http://www.cfengine.org/

DISTINFO_FILE=	${.CURDIR}/distinfo
PATCHDIR=	${.CURDIR}/patches
