# $NetBSD$
#

DISTNAME=	extensible-exceptions-0.1.1.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Extensible exceptions for Haskell

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
