# $NetBSD$
#

DISTNAME=	extensible-exceptions-0.1.1.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Extensible exceptions
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
