# $NetBSD$
#

DISTNAME=		cpphs-1.18.1
CATEGORIES=		lang

MAINTAINER=		esg@sdf.lonestar.org
COMMENT=		Re-implementation of cpp in Haskell
LICENSE=		gnu-lgpl-v2.1

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
