# $NetBSD$
#

DISTNAME=	HDBC-sqlite3-2.1.0.2
CATEGORIES=	databases

MAINTAINER=	pho@cielonegro.org
COMMENT=	Sqlite v3 driver for HDBC

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-HDBC/buildlink3.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../databases/sqlite3/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
