# $NetBSD$

VERSION=	20070607
DISTNAME=	nl_NL
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Dutch dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
