# $NetBSD$
#

DISTNAME=	spatialdata-1.8.0
CATEGORIES=	science
MASTER_SITES=	http://www.geodynamics.org/cig/software/pylith/
EXTRACT_SUFX=	.tgz

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://www.geodynamics.org/cig/software/pylith/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

PKG_DESTDIR_SUPPORT=	user-destdir

CHECK_PORTABILITY_SKIP= configure
GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
