# $NetBSD$
#

DISTNAME=		sleuthkit-1.66
CATEGORIES=		wip
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=sleuthkit/}

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://sleuthkit.sourceforge.net/
COMMENT=		OpenSource Forensic Toolkit

USE_PERL5=		YES
USE_BUILDLINK3=	YES

.include "../../mk/bsd.pkg.mk"
