# $NetBSD$
DISTNAME=	hopenssl-${VERSION}
PKGNAME=	hs-hopenssl-${VERSION}
VERSION=	1.2
CATEGORIES=	security

MAINTAINER=	emil@math.su.se
COMMENT=	FFI bindings to OpenSSL's EVP digest interface

#LICENSE=	modified-bsd

.include "../../security/openssl/buildlink3.mk"
.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
