# $NetBSD$
DISTNAME=	hopenssl-1.2
PKGREVISION=	1
CATEGORIES=	security

MAINTAINER=	esg@sdf.lonestar.org
COMMENT=	FFI bindings to OpenSSL's EVP digest interface
LICENSE=	modified-bsd

.include "../../security/openssl/buildlink3.mk"
.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
