# $NetBSD$

DISTNAME=		sysjail-1.0.4
CATEGORIES=		sysutils
MASTER_SITES=		http://sysjail.bsd.lv/dist/

MAINTAINER=		lkundrak@skosi.org
HOMEPAGE=		http://sysjail.bsd.lv/
COMMENT=		User-space replacement of FreeBSD jail

ONLY_FOR_PLATFORM=	NetBSD-*-* OpenBSD-*-*

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
