# $NetBSD$

DISTNAME=	wrcs-0.99.3
PKGREVISION=	2
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=wrcs/}

MAINTAINER=	lkundrak@skosi.org
HOMEPAGE=	http://wrcs.sourceforge.net/
COMMENT=	Wiki Revision Control System

PKG_DESTDIR_SUPPORT=	none

GNU_CONFIGURE=	yes

.include "../../textproc/xmlrpc-c/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
