# $NetBSD$
BUILDLINK_TREE+=	GeoIP

.if !defined(GEOIP_BUILDLINK3_MK)
GEOIP_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.GeoIP+=	GeoIP>=1.4.6
BUILDLINK_PKGSRCDIR.GeoIP?=	../../wip/GeoIP
.endif	# GEOIP_BUILDLINK3_MK

BUILDLINK_TREE+=	-GeoIP
