# $NetBSD$
#

CATEGORIES=             math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/pixmap.html}
COMMENT=		Functions for import, export, and other manipulations of bitmaps with R

R_PKGNAME=		pixmap
R_PKGVER=               0.4-1

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
