# $NetBSD$
#

DISTNAME=	network-2.3.0.2
CATEGORIES=	net

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell Low-level networking interface
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
