# $NetBSD$
#

DISTNAME=	network-2.2.1.2
CATEGORIES=	net

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell networking-related facilities

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
