# $NetBSD$
#

DISTNAME=	network-2.2.0.1
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell networking-related facilities

.include "../../wip/mk/haskell.mk"
.include "../../wip/parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
