# $NetBSD: Makefile,v 1.1.1.1 2006/05/15 21:53:25 tonio Exp $

DISTNAME=		mmm-mode-0.4.8
CATEGORIES=		textproc editors
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=mmm-mode/}

MAINTAINER=		airhead@users.sourceforge.net
HOMEPAGE=		http://mmm-mode.sourceforge.net/
COMMENT=		Multiple Major Modes for emacs

USE_TOOLS+=		makeinfo
GNU_CONFIGURE=		yes
EMACS_VERSIONS_ACCEPTED= emacs21 emacs21nox

.include "../../editors/emacs/modules.mk"
.include "../../mk/bsd.pkg.mk"
