# $NetBSD$

HEIRLOOM_VER=	070715
DISTNAME=	heirloom-${HEIRLOOM_VER}
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=heirloom/}
EXTRACT_SUFX=	.tar.bz2

HOMEPAGE=		http://heirloom.sourceforge.net/

PKG_DESTDIR_SUPPORT=	user-destdir

PATCHDIR=	${.CURDIR}/../../wip/heirloom-common/patches
DISTINFO_FILE=	${.CURDIR}/../../wip/heirloom-common/distinfo
