# $NetBSD$

DISTNAME=	stm-2.4.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Modular composable concurrency abstraction
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
