# $NetBSD$
#

DISTNAME=	stm-2.4.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Modular composable concurrency abstraction
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
