# $NetBSD$
#

DISTNAME=	haskell-src-1.0.1.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Manipulating Haskell source code

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
