# $NetBSD$
#

DISTNAME=	wsmake-0.6.4
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=wsmake/}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://sourceforge.net/projects/wsmake/
COMMENT=	Software for production and maintenance of web sites
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++
#USE_BZIP2=	yes
TEST_TARGET=	check

.include "../../mk/bsd.pkg.mk"
