#define HOSTOS "NetBSD"
#define HOSTARCH "amd64"
#define HOSTREL "5.0.2"
#define MYSQL "/usr/pkg/bin/mysql"
#define XARGS "/usr/pkgsrc/wip/ldapuseradd/work/.tools/bin/xargs"
#define FIND "/usr/bin/find"
#define STTY "/bin/stty"
#define RM "/bin/rm"
#define CP "/bin/cp"
#define CHGRP "/usr/pkgsrc/wip/ldapuseradd/work/.tools/bin/chgrp"
#define CHOWN "/usr/pkgsrc/wip/ldapuseradd/work/.tools/bin/chown"
#define CHMOD "/bin/chmod"
#define CONFIG_DIR "/usr/pkg/etc/ldapuseradd"
#define CONFIG_FILE CONFIG_DIR "/ldapuseradd.conf"
#define LIB_DIR "/usr/pkg/lib/ldapuseradd"
#define BIN_DIR "/usr/pkg/sbin"

