# $NetBSD$

PKGNAME=	pike-gdbm-${PIKE_VERSION}
CATEGORIES=	lang
COMMENT=	GDBM module for Pike programming language

MODULE_NAMES=	Gdbm
MODULE_DIRS=	modules/Gdbm
MODULE_SO=	Gdbm.so

.include "../../wip/pike-core/Makefile.common"
.include "../../wip/pike-core/Makefile.modules_common"

.include "../../databases/gdbm/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
