# $NetBSD$

.include "Makefile.common"

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	GTK+2 symbols and convience functions for indicators

.include "../../x11/gtk2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
