# $NetBSD$

DISTNAME=	Encode-IMAPUTF7-1.00
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	converters perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=Encode/}

MAINTAINER=	shattered@users.sourceforge.net
HOMEPAGE=	http://search.cpan.org/dist/Encode-IMAPUTF7/
COMMENT=	Modified UTF7 encoding (for IMAP)

PERL5_PACKLIST=	auto/Encode/IMAPUTF7/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
