# $NetBSD$

DISTNAME=	highlighting-kate-0.5.6.1
CATEGORIES=	textproc

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Syntax highlighting
LICENSE=	gnu-gpl-v2


.include "../../wip/mk/haskell.mk"
.include "../../textproc/hs-blaze-html/buildlink3.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../textproc/hs-parsec/buildlink3.mk"
.include "../../wip/hs-pcre-light/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
