# $NetBSD: Makefile,v 1.21 2010/04/20 19:23:14 zafer Exp $
#

.include "../../wip/mawk-uxre/Makefile.common"

PKGNAMESUF=	uxre

LIBS=		-luxre

DESCR_SRC+=	${.CURDIR}/DESCR.addon

.include "../../devel/libuxre/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
