# $NetBSD$
#

DISTNAME=	mod_lisp-2.43
PKGNAME=	${DISTNAME:S/mod_/ap-/}

COMMENT=	Apache module to easily write web applications in Lisp

PKG_APACHE_ACCEPTED=    apache13
LIBRARY_EXTENSION=	so

.include "../../wip/ap-lisp/Makefile.common"
