# $NetBSD$
#

DISTNAME=	HUnit-1.2.2.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://hunit.sourceforge.net/
COMMENT=	Unit testing framework for Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
