# $NetBSD$
#

DISTNAME=	HUnit-1.2.5.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Unit testing framework for Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
