# $NetBSD$
#

DISTNAME=	xhtml-3000.2.1
CATEGORIES=	www

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	https://github.com/haskell/xhtml
COMMENT=	XHTML combinator library
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
