# $NetBSD$

DISTNAME=	timezone-series-0.1.2
CATEGORIES=	time

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	http://projects.haskell.org/time-ng/
COMMENT=	Enhanced timezone handling for Data.Time
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
