# $NetBSD$

DISTNAME=	timezone-series-0.1.3
CATEGORIES=	time

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Enhanced timezone handling for Data.Time
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
