# $NetBSD$

.include "../xfce4/Makefile.common"

DISTNAME=	xfce4-themes-${XFCE4_VERSION}
CATEGORIES=	x11
COMMENT=	XFce4 themes

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../textproc/libxml2/buildlink2.mk"
.include "../../wip/xfce4-panel/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
