# $NetBSD$
#

DISTNAME=		bluez-hcidump-1.32
CATEGORIES=		net
MASTER_SITES=		http://bluez.sourceforge.net/download/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.bluez.org/
COMMENT=		Bluetooth packet analyzer
LICENSE=		gnu-gpl-v2

USE_LANGUAGES=		c

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../wip/bluez-libs/Makefile.common"
.include "../../mk/bsd.pkg.mk"
