# $NetBSD$
#

DISTNAME=		bluez-hcidump-1.12
CATEGORIES=		wip net
MASTER_SITES=		http://bluez.sf.net/download/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://bluez.sf.net/download/
COMMENT=		Bluetooth packet analyzer

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../wip/bluez-libs/Makefile.common"
.include "../../mk/bsd.pkg.mk"
