# $NetBSD$

BUILDLINK_TREE+=	io-vm

.if !defined(IOVM_BUILDLINK3_MK)
IOVM_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.io-vm+=		io-vm>=20080904
BUILDLINK_ABI_DEPENDS.io-vm+=		io-vm>=20080904
BUILDLINK_PKGSRCDIR.io-vm?=		../../wip/io-vm

BUILDLINK_INCDIRS.io-vm+=		include/io
.endif # IOVM_BUILDLINK3_MK

BUILDLINK_TREE+=	-io-vm
