# $NetBSD$

DISTNAME=	yams-0.39.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc www
MASTER_SITES=	https://pypi.python.org/packages/source/y/yams/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://www.logilab.org/project/yams
COMMENT=	Entity / relation schema
#LICENSE=	gnu-lgpl-v2.1

USE_LANGUAGES=	# none

.include "../../devel/py-logilab-common/buildlink3.mk"
.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
