# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
WAVPACK_BUILDLINK3_MK:=	${WAVPACK_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	wavpack
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nwavpack}
BUILDLINK_PACKAGES+=	wavpack
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}wavpack

.if ${WAVPACK_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.wavpack+=	wavpack>=4.32
BUILDLINK_PKGSRCDIR.wavpack?=	../../wip/wavpack
.endif	# WAVPACK_BUILDLINK3_MK

.include "../../converters/libiconv/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
