# $NetBSD: Makefile,v 1.1 2004/05/30 18:03:49 plunky $
#

DISTNAME=		lcab-1.0b10
CATEGORIES=		archivers
MASTER_SITES=		http://www.geekshop.be/rien/lcab/files/

MAINTAINER=		plunky@rya-online.net
HOMEPAGE=		http://www.geekshop.be/rien/lcab
COMMENT=		Microsoft cabinet (.CAB) file creator

GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
