# $NetBSD$

CATEGORIES=	devel math
MASTER_SITES=	http://www.bioconductor.org/packages/release/bioc/src/contrib/

MAINTAINER=	mishka@NetBSD.org
HOMEPAGE=	http://www.bioconductor.org/
COMMENT=	Generic functions for Bioconductor
LICENSE=	artistic-2.0

R_PKGNAME=	BiocGenerics
R_PKGVER=	0.4.0

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
