# $NetBSD$
#

DISTNAME=	progsreiserfs-0.3.0.4
CATEGORIES=	sysutils
MASTER_SITES=	http://reiserfs.osdn.org.ua/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://reiserfs.osdn.org.ua/
COMMENT=	Library to manipulate reiserfs filesystems

PKG_DESTDIR_SUPPORT=	none

USE_LIBTOOL=	yes
GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
