# $NetBSD$
#

DISTNAME=	progsreiserfs-0.3.0.4
CATEGORIES=	sysutils
MASTER_SITES=	http://reiserfs.osdn.org.ua/

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://reiserfs.osdn.org.ua/
COMMENT=	Library to manipulate reiserfs filesystems

USE_BUILDLINK3=	yes
USE_LIBTOOL=	yes
GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
