# $NetBSD$
#

DISTNAME=		heimdal-0.6
CATEGORIES=		wip
MASTER_SITES=		ftp://ftp.pdc.kth.se/pub/heimdal/src/

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		ftp://ftp.pdc.kth.se/pub/heimdal/
COMMENT=		Heimdal is a free implementation of Kerberos V

.include "../../mk/bsd.pkg.mk"
