# $NetBSD$
#

DISTNAME=	quickcheck-instances-0.3.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Common quickcheck instances
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-QuickCheck/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
