# $NetBSD$
# used by wip/lua-stdlib-doc/Makefile

DISTNAME=		stdlib-8
CATEGORIES=		devel
MASTER_SITES=		http://luaforge.net/frs/download.php/3740/

MAINTAINER=		cheusov@tut.by
HOMEPAGE=		http://luaforge.net/projects/stdlib/

PKG_DESTDIR_SUPPORT=	user-destdir

#DIST_SUBDIR=		lua

WRKSRC=			${WRKDIR}/stdlib

NO_BUILD=		yes
NO_CONFIGURE=		yes
