# $NetBSD$

DISTNAME=	semigroupoids-4.2
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Semigroupoids: Category sans id
LICENSE=	2-clause-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-comonad/buildlink3.mk"
.include "../../wip/hs-contravariant/buildlink3.mk"
.include "../../math/hs-distributive/buildlink3.mk"
.include "../../math/hs-semigroups/buildlink3.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
