# $NetBSD$
#

DISTNAME=	time-w3c-0.1
CATEGORIES=	time

MAINTAINER=	pho@cielonegro.org
COMMENT=	Parse, format and convert W3C Date and Time

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-convertible/buildlink3.mk"
.include "../../wip/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
