# $NetBSD$
#

DISTNAME=	monads-tf-0.1.0.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Monad classes, using type families
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
