# $NetBSD$
#

DISTNAME=	logfmon-1.0
CATEGORIES=	wip
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=logfmon/}

MAINTAINER=	clamiax@gmail.com
HOMEPAGE=	http://logfmon.sourceforge.net/
COMMENT=	Log files monitor and processing system

.include "../../mk/bsd.pkg.mk"
