# $NetBSD$
#

DISTNAME=	vamp-2.0.4
CATEGORIES=	physics
MASTER_SITES=	http://www.hepforge.org/archive/whizard/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://projects.hepforge.org/whizard/
COMMENT=	VAMP is WHIZARD's adaptive multi-channel integrator
LICENSE=	gnu-gpl-v2

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_TOOLS+=	gmake
USE_LANGUAGES= c fortran

.include "../../mk/bsd.pkg.mk"
