# $NetBSD$
#

DISTNAME=	ascii-0.0.2.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Type-safe, bytestring-based ASCII values
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-blaze-builder/buildlink3.mk"
.include "../../wip/hs-case-insensitive/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
