# $NetBSD$
#

DISTNAME=		nfdump-1.4.1
CATEGORIES=		net
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=nfdump/}

MAINTAINER=		cg@cgall.de
HOMEPAGE=		http://nfdump.sourceforge.net/
COMMENT=		Netflow processing tools

GNU_CONFIGURE=		yes
REPLACE_PERL=		nfclean.pl

.include "../../mk/bsd.pkg.mk"
