# $NetBSD$
#

VERS=			0.19.0
DISTNAME=		pylint-${VERS}
PKGREVISION=    1
#PKGNAME=		py-lint-${VERS}
CATEGORIES=		devel
MASTER_SITES=		http://pypi.python.org/packages/source/p/pylint/

MAINTAINER=		helgoman@users.sourceforge.net
HOMEPAGE=		http://pypi.python.org/packages/source/p/pylint/
COMMENT=		python code static checker
LICENSE=		gnu-gpl-v2

PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
