# $NetBSD$
#

VERS=						0.19.0
DISTNAME=					pylint-${VERS}
PKGREVISION=    			1
CATEGORIES=					devel
MASTER_SITES=				http://pypi.python.org/packages/source/p/pylint/

MAINTAINER=					helgoman@users.sourceforge.net
HOMEPAGE=					http://www.logilab.org/857
COMMENT=					Python code static checker
LICENSE=					gnu-gpl-v2

PKG_DESTDIR_SUPPORT=		user-destdir

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
