# $NetBSD$

DISTNAME=	elegent-1.2.1
CATEGORIES=	math
MASTER_SITES=	http://www.hepforge.org/archive/elegent/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://elegent.hepforge.org/
COMMENT=	Generator of elastic (anti)proton-proton collisions
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}

USE_LANGUAGES=	c++

.include "../../mk/bsd.pkg.mk"
