#!/bin/sh
# $NetBSD$

PKGNAME=$1
STAGE=$2

SPECIALMAP=@TEXMFDIRS@/fonts/map/fontname/special.map
TTFONTSMAP=@TEXMFDIRS@/ttf2tfm/base/ttfonts.map

case ${STAGE} in
DEINSTALL)
	;;
POST-DEINSTALL)
	echo "Edit ${SPECIALMAP}"
	sed -e "/rphic/d" ${SPECIALMAP} > ${SPECIALMAP}.tmp
	mv -f ${SPECIALMAP}.tmp ${SPECIALMAP}

	echo "Edit ${TTFONTSMAP}"
	sed -e "/Arphic/d" ${TTFONTSMAP} > ${TTFONTSMAP}.tmp
	sed -e "/UBig5/d" ${TTFONTSMAP}.tmp > ${TTFONTSMAP}
	sed -e "/UGB/d" ${TTFONTSMAP} > ${TTFONTSMAP}.tmp
	mv -f ${TTFONTSMAP}.tmp ${TTFONTSMAP}
	;;
*)
	echo "Unexpected argument: ${STAGE}"
	exit 1
	;;
esac
