# $NetBSD$
#

DISTNAME=	io-storage-0.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Key-value store in the IO monad
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
