# $NetBSD$
#

DISTNAME=	cityhash-1.1.0
CATEGORIES=	devel security textproc
MASTER_SITES=	http://cityhash.googlecode.com/files/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://cityhash.googlecode.com/files/
COMMENT=	Provides hash functions for strings
LICENSE=	mit

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
