# $NetBSD$

DISTNAME=	parallel-io-0.3.3
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Combinators for executing IO actions in parallel on a thread pool
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-random/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
