# $NetBSD$
.include "../../wip/nvtv/Makefile.common"

PKGDIR=		../../wip/nvtv
PATCHDIR=	../../wip/nvtv/patches
FILESDIR=	../../wip/nvtv/files

.include "../../x11/gtk2/buildlink2.mk"

.include "../../mk/bsd.pkg.mk"
