# $NetBSD$

VERSION=	20050505
DISTNAME=	es_MX
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Spanish (Mexico) dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
