# $NetBSD$
#

DISTNAME=	markov-chain-0.0.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Markov Chains for generating random sequences
LICENSE=	gnu-gpl-v3

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
