# $NetBSD$

DISTNAME=	data-default-instances-containers-0.0.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Default instances for types in containers
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-data-default-class/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
