# $NetBSD$
#

DISTNAME=	transformers-0.1.4.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Concrete monad transformers
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
