# $NetBSD$
#

DISTNAME=	transformers-0.2.2.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Concrete functor and monad transformers
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
