# $NetBSD$
#

DISTNAME=	mmap-0.5.7
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Memory mapped files for POSIX and Windows
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
