# $NetBSD$
#

DISTNAME=	utf8-string-0.3.3
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	converters

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell UTF-8 layer for IO and Strings

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
