# $NetBSD$
#

DISTNAME=	utf8-string-0.3.5
CATEGORIES=	converters

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell UTF-8 layer for IO and Strings
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
