# $NetBSD$
#

DISTNAME=		nclidar-utm
PKGNAME=		grass-JockeyRidge-20040302
CATEGORIES=		geography
MASTER_SITES=		http://mpa.itc.it/grasstutor/grasslocations/

MAINTAINER=		mchittur@cs.nmsu.edu
HOMEPAGE=		http://mpa.itc.it/grasstutor/
COMMENT=		Example grass dataset for North Carolina

WRKSRC=			${WRKDIR}/nclidar-utm/

.include "../../wip/grass/Makefile.dataset"
.include "../../mk/bsd.pkg.mk"
