# $NetBSD$
#

DISTNAME=	ispell-dictionaries-1.0
CATEGORIES=	meta-pkgs textproc
MASTER_SITES=	# blank
DISTFILES=	# empty

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ficus-www.cs.ucla.edu/geoff/ispell.html
COMMENT=	"meta-package" for ispell spell checker dictionaries
LICENSE=	# blank

USE_LANGUAGES=	# none

DEPENDS+=	ispell-base>=3.3.02:../../textproc/ispell-base

.include "options.mk"

WRKSRC=		# blank

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
