# $NetBSD$
#

DISTNAME=	parallel-1.1.0.0
PKGREVISION=	1
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Library for parallel haskell programming

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
