# $NetBSD$
#

DISTNAME=	parallel-1.1.0.1
CATEGORIES=	parallel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Library for parallel haskell programming

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
