# $NetBSD$
#

DISTNAME=		qcad-manual-en-2.0.4.0-1.html
PKGNAME=		qcad-manual-en-2.0.4.0

.include "../qcad/Makefile.common"

COMMENT=		Online manual for QCad 2D CAD package, English

CONFLICTS=		qcad-manual-{[!e]?,?[!n]}-[0-9]*

.include "./Makefile.common"
