# $NetBSD$

DISTNAME=		xa-2.3.5
PKGNAME=		${DISTNAME:S/xa/&65/}
CATEGORIES=		devel
MASTER_SITES=		http://www.floodgap.com/retrotech/xa/dists/

MAINTAINER=		mwilhelmy@users.sourceforge.net
HOMEPAGE=		http://www.floodgap.com/retrotech/xa/
COMMENT=		Cross assembler for MOS Technologies 6502
LICENSE=		gnu-gpl-v2

NO_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
