# $NetBSD$
#

DISTNAME=	pymetrics-0.8.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	http://garr.dl.sourceforge.net/project/pymetrics/pymetrics/pymetrics-0.8.1/

MAINTAINER=	 jihbed.research@gmail.com
HOMEPAGE=	http://sourceforge.net/projects/pymetrics/
COMMENT=	Metrics for python files
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none
PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
