# $NetBSD$

.include "../../wip/heirloom-common/Makefile.prog2.common"

PKGNAME=	heirloom-what-${HEIRLOOM_VER}
CATEGORIES=	textproc

MAKE_FLAGS+=	SUBDIRS="libcommon build what"

.include "../../mk/bsd.pkg.mk"
