# $NetBSD$

DISTNAME=	ar7-0.1
CATEGORIES=	net
MASTER_SITES=	http://home.arcor.de/volpol/ar7/ \
		http://ftp.backschues.net/pub/driver/sphairon_ar860/

MAINTAINER=	schwarz@NetBSD.org
HOMEPAGE=	${MASTER_SITES}
COMMENT=	Diagnosis tool for certain ADSL modems

GNU_CONFIGURE=	YES
INSTALLATION_DIRS=	bin

.include "../../mk/bsd.pkg.mk"
