# $NetBSD$

DISTNAME=	cvxpy-0.2.7
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://pypi.python.org/packages/source/c/cvxpy/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://github.com/cvxgrp/cvxpy/
COMMENT=	DSL for modeling convex optimization problems in Python
LICENSE=	gnu-gpl-v3

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
