# $NetBSD$
#

DISTNAME=	cereal-0.4.0.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Binary serialization library
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
