# $NetBSD: Makefile$

DISTNAME=		hcidump-1.5.1
CATEGORIES=		sysutils
MASTER_SITES=		http://www.geocities.com/m_evmenkin/

MAINTAINER=		plunky@rya-online.net
COMMENT=		Bluetooth traffic dumper, similar to tcpdump

ONLY_FOR_PLATFORM=	NetBSD-*-*

WRKSRC=			${WRKDIR}/hcidump

INSTALLATION_DIRS=	${PKGMANDIR}/man1

.include "../../mk/bsd.pkg.mk"
