# $NetBSD$

DISTNAME=   digest-0.0.1.2
CATEGORIES= lang

MAINTAINER= zecrazytux@zecrazytux.net
COMMENT=    Various cryptographic hashes for bytestrings; CRC32 and Adler32 for now.
LICENSE=    modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
