# $NetBSD$
#

DISTNAME=	feynmf.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.08
TEXLIVE_REV=	17259

MAINTAINER=	kamelderouiche@yahoo.com
COMMENT=	Documentation for tex-feynmf


.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
