# $NetBSD$

DISTNAME=	vector-space-0.8.6
CATEGORIES=	math

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Vector & affine spaces, linear maps, and derivatives
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-Boolean/buildlink3.mk"
.include "../../wip/hs-MemoTrie/buildlink3.mk"
.include "../../wip/hs-NumInstances/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
