# $NetBSD$

DISTNAME=	affine-1.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	https://pypi.python.org/packages/source/a/affine/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/sgillies/affine
COMMENT=	Matrices describing affine transformation of the plane
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
