# $NetBSD$
#

DISTNAME=	ncdu-1.8
CATEGORIES=	filesystems
MASTER_SITES=	http://sourceforge.net/projects/ncdu/files/ncdu/ncdu-1.8/

COMMENT=	Disk usage visualization tool
LICENSE=	modified-bsd

MAINTAINER=	slitvinov@gmail.com
HOMEPAGE=	http://dev.yorhel.nl/ncdu

GNU_CONFIGURE=	yes

.include "../../devel/ncurses/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
