# $NetBSD$

DISTNAME=	vcversioner-2.14.0.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://pypi.python.org/packages/source/v/vcversioner/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/habnabit/vcversioner
COMMENT=	Use version control tags to discover version numbers
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
