# $NetBSD$
#

DISTNAME=	yajl-1.0.9
CATEGORIES=	devel
MASTER_SITES=	http://github.com/downloads/lloyd/yajl/

MAINTAINER=	pallegra@gmail.com
HOMEPAGE=	http://lloyd.github.com/yajl/
COMMENT=	Small JSON library written in ANSI C
LICENSE=	modified-bsd

PKG_DESTDIR_SUPPORT=	user-destdir

USE_TOOLS+=	gmake
USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
