# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
C_ARES_BUILDLINK3_MK:=	${C_ARES_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	c-ares
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nc-ares}
BUILDLINK_PACKAGES+=	c-ares

.if !empty(C_ARES_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.c-ares+=	c-ares>=1.2.0
BUILDLINK_PKGSRCDIR.c-ares?=	../../wip/c-ares
.endif	# C_ARES_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
