# $NetBSD$
#

DISTNAME=	data-accessor-mtl-0.2.0.3
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Use Accessor to access state in mtl State monad class
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-data-accessor/buildlink3.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
