# $NetBSD$

DISTNAME=	geographiclib-1.31
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	geography
MASTER_SITES=	https://pypi.python.org/packages/source/g/geographiclib/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://geographiclib.sourceforge.net/
COMMENT=	Translation of the GeographicLib::Geodesic class to Python
LICENSE=	mit

WRKSRC=		${WRKDIR}/geographiclib-1.31

USE_LANGUAGES=	# none

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
