# $NetBSD$
#

DISTNAME=		slovakia
PKGNAME=		grass-Slovakia-20040302
CATEGORIES=		geography
MASTER_SITES=		http://mpa.itc.it/grasstutor/grasslocations/

MAINTAINER=		mchittur@cs.nmsu.edu
HOMEPAGE=		http://mpa.itc.it/grasstutor/grasslocations/
COMMENT=		Example data set for grass 5.0

WRKSRC=			${WRKDIR}/slovakia

.include "../../wip/grass/Makefile.dataset"
.include "../../mk/bsd.pkg.mk"
