# $NetBSD$

DISTNAME=	semigroupoid-extras-3.0.1
CATEGORIES=	math

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Semigroupoids requiring Haskell extensions
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-comonad/buildlink3.mk"
.include "../../wip/hs-distributive/buildlink3.mk"
.include "../../wip/hs-groupoids/buildlink3.mk"
.include "../../wip/hs-semigroupoids/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
