# $NetBSD$
#

DISTNAME=		cops104+
PKGNAME=		cops-1.04
WRKSRC=			${WRKDIR}/cops_104+
CATEGORIES=		security
MASTER_SITES=	http://www.fish.com/cops/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.fish.com/cops/
COMMENT=		Computer Oracle and Password System

MAKEFILE=		makefile

USE_GNU_TOOLS+=	make

.include "../../mk/bsd.pkg.mk"
