# $NetBSD$

DISTNAME=	Log-1.7.0

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://www.csh.rit.edu/~jon/projects/pear_log/
COMMENT=	PHP Log framework provides an abstracted logging system

.include "../../wip/php4/pear.mk"
.include "../../mk/bsd.pkg.mk"
