# $NetBSD$

.include "../xfce4/Makefile.common"

DISTNAME=	xfce4-iconbox-${XFCE4_VERSION}
COMMENT=	XFce4 icon displayer

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../wip/xfce4-mcs-plugins/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
