# $NetBSD$

DISTNAME=	Net_LDAP2-2.0.7
CATEGORIES+=	net

MAINTAINER=	wenheping@gmail.com
COMMENT=	Object oriented interface for searching and manipulating LDAP-entries
LICENSE=	gnu-lgpl-v3

PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
