# $NetBSD$
#

DISTNAME=	void-0.5.12
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	http://github.com/ekmett/void
COMMENT=	Haskell 98 logically uninhabited data type
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-semigroups/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
