# $NetBSD$
#

DISTNAME=	Cython-0.11.2
PKGNAME=	cython-0.11.2
CATEGORIES=	lang python
MASTER_SITES=	http://cython.org/

MAINTAINER=	kamel.derouiche@gmail.com
HOMEPAGE=	http://cython.org/
COMMENT=	The Cython compiler for writing C extensions for the Python language
LICENSE=	apache-1.1


PKG_DESTDIR_SUPPORT=	user-destdir

PYDISTUTILSPKG= yes
PY_PATCHPLIST=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
