# $NetBSD$
#

DISTNAME=	text-icu-0.6.3.4
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Bindings to the ICU library
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../textproc/icu/buildlink3.mk"
.include "../../devel/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
