# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
MINGW_BINUTILS_BUILDLINK3_MK:=	${MINGW_BINUTILS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	mingw-binutils
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmingw-binutils}
BUILDLINK_PACKAGES+=	mingw-binutils
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mingw-binutils

.if ${MINGW_BINUTILS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.mingw-binutils+=	mingw-binutils>=2.18
BUILDLINK_PKGSRCDIR.mingw-binutils?=	../../wip/mingw-binutils
.endif	# MINGW_BINUTILS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
