# $NetBSD$
#

DISTNAME=	arabxetex.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.1.4

MAINTAINER=	kamelderouiche@yahoo.com
COMMENT=	Documentation for tex-arabxetex


.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
