# $NetBSD$
#

DISTNAME=	base-unicode-symbols-0.2.2.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Unicode alternatives for common functions and operators
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
