# $NetBSD$

.include "../../wip/heirloom-common/Makefile.prog2.common"

PKGNAME=	heirloom-xargs-${HEIRLOOM_VER}
CATEGORIES=	sysutils

MAKE_FLAGS+=	SUBDIRS="build xargs"

.include "../../wip/heirloom-libcommon/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
