# $NetBSD$
#

PKGNAME=	${DISTNAME:S/.src//}
PKGREVISION=	1
COMMENT=	Tron clone in 3D with advanced gameplay and multiplayer

.include "../../devel/SDL/buildlink3.mk"
.include "../../graphics/SDL_image/buildlink3.mk"
.include "../../graphics/png/buildlink3.mk"
.include "../../mk/jpeg.buildlink3.mk"
.include "../../wip/armagetronad/Makefile.common"
