# $NetBSD$
#

DISTNAME=		aircrack-ng-0.3
CATEGORIES=		security
MASTER_SITES=		http://tinyshell.be/aircrackng/download/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://tinyshell.be/aircrackng/
COMMENT=		Tools for auditing wireless networks

ONLY_FOR_PLATFORM+=	Linux-*-*

.include "../../mk/bsd.pkg.mk"
