# $NetBSD$

DISTNAME=	Crypt_Blowfish-1.0.1
CATEGORIES=	security

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Two-way blowfish encryption

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
