# $NetBSD$
#

DISTNAME=	ansi-terminal-0.5.5
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Simple ANSI terminal support for Haskell

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
