# $NetBSD$

DISTNAME=	ansi-terminal-0.6.1.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Simple ANSI terminal support for Haskell
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
