# $NetBSD$
#

DISTNAME=	rosegarden-4-0.9.1
CATEGORIES=	audio	
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=rosegarden/}

MAINTAINER=	virtus@wanadoo.nl
HOMEPAGE=	http://www.all-day-breakfast.cm/rosegarden/
COMMENT=	Development release of rosegarden

USE_BUILDLINK2=	YES
GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
