# $NetBSD$

.include "../xfce4/Makefile.common"

BROKEN=     Not working yet

DISTNAME=	xfce4-toys-0.2.0
COMMENT=	XFce4 toys

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../textproc/libxml2/buildlink2.mk"
.include "../../wip/xfce4-panel/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
