# $NetBSD$
#

DISTNAME=	test-framework-hunit-0.3.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	HUnit support for the test-framework package
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-extensible-exceptions/buildlink3.mk"
.include "../../wip/hs-HUnit/buildlink3.mk"
.include "../../wip/hs-test-framework/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
