# $NetBSD$

DISTNAME=	${MOZILLA}-${MOZ_DISTVER}
MOZ_DISTDIR=	releases/${MOZ_DIR}/linux-i686/en-US
MASTER_SITES=	http://ftp.mozilla.org/pub/mozilla.org/thunderbird/${MOZ_DISTDIR}/

MOZ_PLATFORM=	linux
