# $NetBSD: Makefile,v 1.16 2011/01/23 07:55:13 markd Exp $

DISTNAME=	kdegraphics-strigi-analyzer-${_KDE_VERSION}
CATEGORIES=	graphics
COMMENT=	graphics file format plugins for Strigi Desktop Search

.include "../../wip/kde4/Makefile.kde4"

.include "../../wip/kde4/kde4.mk"

.include "../../graphics/tiff/buildlink3.mk"
.include "../../wip/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
