# $NetBSD$
#

MODNAME=	mongo
PECL_VERSION=	1.6.7
CATEGORIES=	databases

MAINTAINER=	bartosz.kuzma@gmail.com
COMMENT=	MongoDB database driver
LICENSE=	apache-2.0

USE_LANGUAGES=	c c++

.include "../../lang/php/ext.mk"
.include "../../mk/bsd.pkg.mk"
