# $NetBSD$
#

DISTNAME=	mime-0.3.0
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell MIME Type Library

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
