# $NetBSD$
#

DISTNAME=	arabi.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.1


MAINTAINER=	kamelderouiche@yahoo.com
COMMENT=	Documentation for tex-arabi

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
