# $NetBSD$
#

DISTNAME=	blaze-builder-0.3.1.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficient buffered output
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
