# $NetBSD$

.include "../../wip/xfce4/Makefile.common"

XFCE4_VERSION=	2.4.1

DISTNAME=	gtk-xfce-engine-${XFCE4_VERSION}
PKGNAME=	xfce4-gtk2-engine-${XFCE4_VERSION}
CATEGORIES=	x11
COMMENT=	Xfce GTK2 themes


.include "../../x11/gtk2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
