# $NetBSD$
#

DISTNAME=	egenix-mx-base-3.1.3
PKGNAME=	${PYPKGPREFIX}-mx-base-3.1.3
CATEGORIES=	devel
MASTER_SITES=	http://downloads.egenix.com/python/

MAINTAINER=	wenheping@gmail.com
HOMEPAGE=	http://www.egenix.com/products/python/mxBase/
COMMENT=	Contains the Open Source parts of the eGenix mx Extension series
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
