# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-sqlite3-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		databases

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		SQLite3 addon for Io

ADDON_NAME=		SQLite3

.include "../../databases/sqlite3/buildlink3.mk"
.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
