# $NetBSD$
#

DISTNAME=	FileManip-0.3.2
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_HASKELL_HACKAGE:=FileManip/0.3.2/}

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://hackage.haskell.org/cgi-bin/hackage-scripts/package/FileManip
COMMENT=	Haskell library for working with files and directories

.include "../../wip/mk/haskell.mk" # This should be "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
