# $NetBSD$
#

DISTNAME=	FileManip-0.3.2
CATEGORIES=	devel
PKGREVISION= 1

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell library for working with files and directories

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
