# $NetBSD$
#

DISTNAME=	pcp-2.2
CATEGORIES=	math
MASTER_SITES=	http://garr.dl.sourceforge.net/project/pcp/pcp/2.2/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://pcp.sourceforge.net/
COMMENT=	Machine learning program for pattern classification
LICENSE=	mit

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++ fortran

.include "../../mk/bsd.pkg.mk"
