# $NetBSD$

DISTNAME=	MemoTrie-0.6.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	http://haskell.org/haskellwiki/MemoTrie
COMMENT=	Trie-based memo functions
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-void//buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
