# $NetBSD$
#

PKGNAME=		${DISTNAME:S/-/-pgsql-/}

# Postgresql dependencies
DEPENDS+=	p5-DBD-postgresql>=1.22:../../databases/p5-DBD-postgresql

RT_DB_TYPE=		Pg
DB_DBA?=		postgres

.include "Makefile.common"
