# $NetBSD$

DISTNAME=	mpc-0.10.3
CATEGORIES=	audio
MASTER_SITES=	http://mercury.chem.pitt.edu/~shank/

MAINTAINER=	pkg@burningsoda.com
HOMEPAGE=	http://www.musicpd.org/
COMMENT=	Command line client for the fantastic Music Player Daemon

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
