# $NetBSD$
#

DISTNAME=	bindings-DSL-1.0.8
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	FFI domain specific language on top of hsc2hs
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
