# $Id$

DISTNAME=	File-1.4.1
CATEGORIES=	devel

MAINTAINER=	noud4@users.sourceforge.net
HOMEPAGE=	http://pear.php.net/package/File/
COMMENT=	Common file and directory routines

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
