# $NetBSD$

DISTNAME=	mando-0.3.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	https://pypi.python.org/packages/source/m/mando/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://mando.readthedocs.org/
COMMENT=	Create Python CLI apps with little to no effort at all
LICENSE=	mit

WRKSRC=		${WRKDIR}/mando-0.3.2

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
