# $NetBSD$
#

DISTNAME=	AeroCalc-0.11
PKGNAME=	${PYPKGPREFIX}-arepcalc-0.11
CATEGORIES=	science python
MASTER_SITES=	http://www.kilohotel.com/python/aerocalc/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://www.kilohotel.com/python/aerocalc/
COMMENT=	Aeronautical Engineering Calculations
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

USE_LANGUAGES=	# none

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
