# $NetBSD$
#

DISTNAME=	bytestring-trie-0.1.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficient finite map from (byte)strings to values

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-binary/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
