# $NetBSD$
#

DISTNAME=		ecasound-2.4.1
CATEGORIES=		wip audio
MASTER_SITES=		http://ecasound.seul.org/download/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://ecasound.seul.org/
COMMENT=		multitrack audio processor.

USE_PKGLOCALEDIR=	yes
USE_LIBTOOL=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
