# $NetBSD$

DISTNAME=	uqwk-2.21
CATEGORIES=	news
MASTER_SITES=	http://www.xs4all.nl/~js/warez/

HOMEPAGE=	http://www.xs4all.nl/~js/warez/	
COMMENT=	tool to collect news and mail packets for offline reading
MAINTAINER=	schwarz@netbsd.org

GNU_CONFIGURE=	YES
USE_BUILDLINK3=	YES

INSTALLATION_DIRS=	bin man/man1

.include "../../mk/bsd.pkg.mk"
