# $NetBSD$

.include "../../wip/gd/Makefile.common"

PKGNAME=	gd-nox11-${DIST_VER}
COMMENT=	Graphics library for the dynamic creation of images

CONFIGURE_ARGS+=	--without-x
CONFIGURE_ARGS+=	--without-xpm

.include "../../mk/bsd.pkg.mk"
