# $NetBSD$

DISTNAME=	PyMarkovChain-1.7.5
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/Py//:tl}
CATEGORIES=	math
MASTER_SITES=	https://pypi.python.org/packages/source/P/PyMarkovChain/


MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://pypi.python.org/packages/source/P/PyMarkovChain/
COMMENT=	Simple markov chain implementation
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none


.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
