# $NetBSD$

DISTNAME=	knob-0.1.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Memory-backed handles
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
