# $NetBSD$
#

PEAR_CHANNEL=		pear.swiftmailer.org
PEAR_CHANNEL_ALIAS=	swiftmailer
PEAR_CHANNEL_VERSION=	2013.08.13

MAINTAINER=		noud4@home.nl

.include "../../wip/mk/pear-channel.mk"
.include "../../mk/bsd.pkg.mk"
