# $NetBSD$
#

DISTNAME=	arabxetex
PKGNAME=	tex-${DISTNAME}-1.1.4
TEXLIVE_REV= 17470

MAINTAINER=	kamelderouiche@yahoo.com
COMMENT=	ArabTeX-like interface for XeLaTeX

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
