# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBTEXTCAT_BUILDLINK3_MK:=	${LIBTEXTCAT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libtextcat
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibtextcat}
BUILDLINK_PACKAGES+=	libtextcat
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libtextcat

.if ${LIBTEXTCAT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libtextcat+=	libtextcat>=2.2
BUILDLINK_PKGSRCDIR.libtextcat?=	../../category/libtextcat
.endif	# LIBTEXTCAT_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
