# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ORTP_BUILDLINK3_MK:=	${ORTP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	ortp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nortp}
BUILDLINK_PACKAGES+=	ortp
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ortp

.if ${ORTP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.ortp+=	ortp>=0.13.1
BUILDLINK_PKGSRCDIR.ortp?=	../../wip/ortp
.endif	# ORTP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
