# $NetBSD$
#

DISTNAME=	monoid-transformer-0.0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Monoid counterparts to some ubiquitous monad transformers
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
