# $NetBSD$
#

DISTNAME=	anyjson-0.2.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc python
MASTER_SITES=	http://pypi.python.org/packages/source/a/anyjson/

MAINTAINER=	pkgsrc-users@netbsd.org
HOMEPAGE=	http://pypi.python.org/pypi/anyjson
COMMENT=	Wraps the JSON implementation available in a common interface
LICENSE=		modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
