# $NetBSD$
#

DISTNAME=	Diff-0.1.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	O(ND) diff algorithm in haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
