# $NetBSD$
#

DISTNAME=		activation-1.0
PKGNAME=		java-gnujaf-1.0
CATEGORIES=		wip
MASTER_SITES=	http://ftp.gnu.org/gnu/classpathx/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://ftp.gnu.org/gnu/classpathx/
COMMENT=		GNU Java Activation Framework

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes
USE_GNU_TOOLS+=		make

.include "../../mk/java-env.mk"
.include "../../mk/bsd.pkg.mk"
