# $NetBSD$
#

PEAR_CHANNEL=		pear.phpunit.de
PEAR_CHANNEL_ALIAS=	phpunit
PEAR_CHANNEL_VERSION=	2010.05.12

MAINTAINER=		pkgsrc-users@NetBSD.org

.include "../../wip/mk/pear-channel.mk"
.include "../../mk/bsd.pkg.mk"
