# $NetBSD$

BUILDLINK_TREE+=	uthash

.if !defined(UTHASH_BUILDLINK3_MK)
UTHASH_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.uthash+=	uthash>=1.9.4
BUILDLINK_PKGSRCDIR.uthash?=	../../wip/uthash

.endif # UTHASH_BUILDLINK3_MK

BUILDLINK_TREE+=	-uthash
