# $NetBSD$
#
# Determine if libbsd can be built on this platform
#
# if so, USELIBBSD will be defined and including buildlink3.mk will
# link your package against it if not, including buildlink3.mk will be a
# noop.
#
# define here for which platforms libbsd is available
LIBBSD.only_for_platform=	Linux-*-*
# stop editing here

.include "../../mk/bsd.prefs.mk"
.for p in ${LIBBSD.only_for_platform}
.    if !empty(MACHINE_PLATFORM:M${p})
USE_LIBBSD=		yes
.    endif
.endfor
