# $NetBSD$

DISTNAME=	pyliblzma-0.5.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/py//}
CATEGORIES=	archivers python
MASTER_SITES=	https://pypi.python.org/packages/source/p/pyliblzma/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://pypi.python.org/packages/source/p/pyliblzma/
COMMENT=	Python bindings for liblzma
LICENSE=	gnu-lgpl-v3

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
