# $NetBSD$
#

DISTNAME=	hscolour-1.11
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.cs.york.ac.uk/fp/darcs/hscolour/
COMMENT=	Colourise Haskell code

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
