# $NetBSD$

.include "../xfce4/Makefile.common"

PKGNAME=	xfce4-print-${XFCE4_VERSION}
COMMENT=	XFce4 print dialog

WRKSRC=		${WRKDIR}/xfce-devel/xfprint

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../wip/xfce4-mcs-plugins/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
