# $NetBSD$
#

DISTNAME=	argtable2-10
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=argtable/}

MAINTAINER=	kamel.derouiche@gmail.com
HOMEPAGE=	http://argtable.sourceforge.net/
COMMENT=	ANSI C library for parsing GNU style command line options

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES =	c c++

.include "../../mk/bsd.pkg.mk"
