# $NetBSD$
#

DISTNAME=		scmail-1.3
CATEGORIES=		wip
MASTER_SITES=		http://namazu.org/~satoru/scmail/

MAINTAINER=		nel@soraneko.com
HOMEPAGE=		http://namazu.org/~satoru/scmail/
COMMENT=		The scmail is a mail filter using Gauche

.include "../../lang/gauche/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
