# $NetBSD$
#

DISTNAME=	clustershell-1.2.83
CATEGORIES=	shells
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=clustershell/}
EXTRACT_SUFX=	.tgz

MAINTAINER=	wenheping@gmail.com
HOMEPAGE=	http://clustershell.sourceforge.net/
COMMENT=	Python library to execute commands on local or distant cluster nodes

PYDISTUTILSPKG= yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
