# $NetBSD: Makefile,v 1.2 2002/10/30 10:24:57 kleink Exp $

DISTNAME=	dircproxy-1.1.0
CATEGORIES=	chat
MASTER_SITES=  	http://www.dircproxy.net/download/1.1/

MAINTAINER=     sb125499@ohiou.edu
HOMEPAGE=	http://www.dircproxy.net/
COMMENT=	detachable internet relay chat proxy server

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
