# $NetBSD$

DISTNAME=	http-attoparsec-0.1.1
CATEGORIES=	www

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Attoparsec parsers for http-types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../textproc/hs-attoparsec/buildlink3.mk"
.include "../../wip/hs-http-types/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
