# $NetBSD$

DISTNAME=	http-attoparsec-0.1.0
CATEGORIES=	www

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Attoparsec parsers for http-types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-attoparsec/buildlink3.mk"
.include "../../wip/hs-http-types/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
