# $NetBSD$
#

DISTNAME=	teamocil-0.1.5
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	ishit@users.sourceforce.net
HOMEPAGE=	http://github.com/remiprev/teamocil
COMMENT=	Easy window and split layouts for tmux
#LICENSE=	teamocil-license

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
