# $NetBSD$

DISTNAME=	PyZenity-0.1.4
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/Py//:tl}
CATEGORIES=	x11 python
MASTER_SITES=	http://www.brianramos.com/software/PyZenity/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://www.brianramos.com/software/PyZenity/
COMMENT=	Easy to use frontend to Zenity
LICENSE=	mit

USE_LANGUAGES=	# none

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
