# $NetBSD$
#

DISTNAME=	mod_lisp2-1.2
PKGNAME=	${DISTNAME:S/lisp2/lisp/:S/mod_/ap2-/1}

COMMENT=	Apache2 module to easily write web applications in Lisp

PKG_APACHE_ACCEPTED=    apache2 apache22
USE_LIBTOOL=		yes
LIBRARY_EXTENSION=	la

.include "../../wip/ap-lisp/Makefile.common"
