# $NetBSD$

DISTNAME=	iesd-1.2.2
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	ruby sysutils
EXTRACT_SUFX=	.gem

MAINTAINER=	sevan@NetBSD.org
HOMEPAGE=	https://rubygems.org/gems/iesd
COMMENT=	Tool to customize OS X InstallESD
LICENSE=	2-clause-bsd

RUBY_VERSION_SUPPORTED=	193 200 21

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
