# $NetBSD: Makefile,v 1.27 2004/03/13 16:54:06 kristerw Exp $

SWIPLVERS=		5.2.13
DISTNAME=		pl-${SWIPLVERS}
CATEGORIES=		lang
MASTER_SITES=		ftp://ftp.swi.psy.uva.nl/SWI-Prolog/

HOMEPAGE=		http://www.swi-prolog.org/

DIST_SUBDIR=		swi-prolog
DISTINFO_FILE=		${.CURDIR}/../../wip/swi-prolog-lite/distinfo
PATCHDIR=		${.CURDIR}/../../wip/swi-prolog-lite/patches

PLIST_SUBST+=           APPEND_ELF=${APPEND_ELF}
