# $NetBSD$

DISTNAME=	Boolean-0.2
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Generalized booleans and numbers
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
