# $NetBSD$
#

PLUGINSVERSION=	1.3.1
DISTNAME=	nagios-plugins-${PLUGINSVERSION}

.include "../../wip/nagios-base/Makefile.common"

CONFIGURE_ARGS+=	--with-nagios-user=${NAGIOS_USER}
CONFIGURE_ARGS+=	--with-nagios-group=${NAGIOS_GROUP}
