# $NetBSD$

VERSION=	20021015
DISTNAME=	ca_ES
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Catalan dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
