# $NetBSD$

DISTNAME=	reflection-1.4
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Reifies arbitrary terms into types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-tagged/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
