# $NetBSD$

DISTNAME=	reflection-1.3.2
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	http://github.com/ekmett/reflection
COMMENT=	Reifies arbitrary terms into types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-tagged/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
