# $NetBSD$

DISTNAME=		cabal-install-0.10.2
PKGNAME=		${DISTNAME}
CATEGORIES=		devel

MAINTAINER=		pho@cielonegro.org
COMMENT=		Command-line interface for Cabal and Hackage
LICENSE=		modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-HTTP/buildlink3.mk"
.include "../../wip/hs-network/buildlink3.mk"
.include "../../wip/hs-zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
