# $NetBSD$

DISTNAME=	shunt-1.7.2
CATEGORIES=	sysutils
MASTER_SITES=	http://www.serice.net/shunt/

MAINTAINER=	fgudin@nerim.net
HOMEPAGE=	http://www.serice.net/shunt/
COMMENT=	Burning multi-set CDROM backups

PKG_DESTDIR_SUPPORT=	none

NO_CONFIGURE=	yes
USE_TOOLS+=	gmake

WRKSRC=		${WRKDIR}/${DISTNAME}

.include "../../mk/bsd.pkg.mk"
