# $NetBSD: $

.include "../../wip/nagios-base/Makefile.common"

NRPE_USER?=		${NAGIOS_USER}
NRPE_GROUP?=		${NAGIOS_GROUP}

CONFIGURE_ARGS+=	--with-nrpe-user=${NRPE_USER}
CONFIGURE_ARGS+=	--with-nrpe-group=${NRPE_GROUP}

.include "../../mk/bsd.prefs.mk"

PKG_OPTIONS_VAR=	PKG_OPTIONS.nrpe
PKG_SUPPORTED_OPTIONS=	args

.include "../../mk/bsd.options.mk"

.if !empty(PKG_OPTIONS:Margs)
CONFIGURE_ARGS+=	--enable-command-args
.endif
