# $NetBSD: $
#
LIBISCXX=yes
MKSTATICLIB=yes
MKDEBUGLIB=no
MKPICINSTALL=no
MKPROFILE=no

LIB =	tinyxml
SRCS=	tinystr.cpp tinyxmlerror.cpp tinyxml.cpp tinyxmlparser.cpp
INCS=	tinyxml.h

LIBDIR=		${PREFIX}/lib
INCSDIR=	${PREFIX}/include

.include <bsd.lib.mk>
