# $NetBSD$

DISTNAME=	fancybox.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.3
TEXLIVE_REV=	15878

MAINTAINER=	nico@orgrim.net
COMMENT=	Documentation for tex-fancybox

CONFLICTS+=	teTeX-texmf-[0-9]*

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
