# $NetBSD$

DISTNAME=		grdc-20031019
CATEGORIES=		wip time
MASTER_SITES=		ftp://ftp.terabyte.com.ua/pub/software/time/

MAINTAINER=		mishka@terabyte.com.ua
HOMEPAGE=		http://www.FreeBSD.org/
COMMENT=		Grand digital clock from FreeBSD-current games

.include "../../mk/bsd.pkg.mk"
