.TH ldapusermod 8 User Manuals
.SH NAME
ldapusermod \- LDAP User Modify
.SH SYNOPSIS
\fBldapusermod [\fIoptions\fB] username
\f1
.SH DESCRIPTION
ldapuseradd is a set of utilities that aid in the management of users and groups in LDAP directories. Their syntax is identical to the UNIX useradd toolset. 
.SH OPTIONS
.TP
\fB -a STRING\f1
first name
.TP
\fB -b STRING\f1
last name
.TP
\fB -c STRING\f1
comment/gecos
.TP
\fB -d STRING\f1
home directory
.TP
\fB -e LONG\f1
expiration date
.TP
\fB -E STRING\f1
e-mail address
.TP
\fB -f LONG\f1
inactive days
.TP
\fB -g INT\f1
primary groups
.TP
\fB -G INT\f1
secondary groups
.TP
\fB -h | --help\f1
Print help and exit
.TP
\fB -l STRING\f1
New Username
.TP
\fB -m\f1
unsupported
.TP
\fB -n STRING\f1
config stanza (account profile)
.TP
\fB -o\f1
unsupported
.TP
\fB -p STRING\f1
password
.TP
\fB -s STRING\f1
shell
.TP
\fB -u INT\f1
userid number
.TP
\fB -v | --verbose\f1
Increase Verbosity (use up to 4 times)
.TP
\fB -x | --dump\f1
Dump run-time config and exit
.SH FILES
\fI/usr/local/etc/ldapuseradd/ldapuseradd.conf\f1 The config file.

\fI/usr/local/etc/ldapuseradd/users.ldap\f1 User Schema.

\fI/usr/local/etc/ldapuseradd/groups.ldap\f1 Group Schema.
.SH AUTHOR
ldapuseradd was written by Greg Schenzel <inittab@unixdev.net>
.SH SEE ALSO
\fBldapuseradd(8)\f1

\fBldapuserdel(8)\f1

\fBldapgroupmod(8)\f1

\fBldapgroupdel(8)\f1

\fBldapgroupadd(8)\f1

\fBldapuseradd.conf(5)\f1

\fBusers.ldap(5)\f1

\fBgroups.ldap(5)\f1
.SH COMMENTS
This man page was originally written using \fBxmltoman(1)\f1.
