# $NetBSD$
#

DISTNAME=	MonadCatchIO-mtl-0.3.0.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Monad-transformer version of the Control.Exception module
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-extensible-exceptions/buildlink3.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
