# $NetBSD$

DISTNAME=	memo-1.6
CATEGORIES=	misc
MASTER_SITES=	http://www.getmemo.org/

MAINTAINER=	cfkoch@users.sourceforge.net
HOMEPAGE=	http://www.getmemo.org/
COMMENT=	Note-taking software
LICENSE=	gnu-gpl-v3

USE_LANGUAGES+=	c
NO_CONFIGURE=	yes
USE_TOOLS+=	gmake

MAKE_FLAGS+=	PREFIX=${PREFIX}
INSTALLATION_DIRS=	bin

.include "../../mk/bsd.pkg.mk"
