# $NetBSD$
#

DISTNAME=	gkrellmlaunch-0.4
CATEGORIES=	misc x11
MASTER_SITES=	http://belnet.dl.sourceforge.net/sourceforge/gkrellmlaunch/

MAINTAINER=	ptiJo <ptiJo@noos.fr>
HOMEPAGE=	http://gkrellmlaunch.sourceforge.net/
COMMENT=	plugin which allows one-click access to frequently used applications

DEPENDS+=       gkrellm-1.2.*:../../sysutils/gkrellm

.include "../../mk/bsd.pkg.mk"
