# $NetBSD$

BUILDLINK_TREE+=	cpphs

.if !defined(CPPHS_BUILDLINK3_MK)
CPPHS_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.cpphs?=	build
BUILDLINK_API_DEPENDS.cpphs+=	cpphs>=1.6
BUILDLINK_PKGSRCDIR.cpphs?=	../../wip/cpphs
.endif # CPPHS_BUILDLINK3_MK

BUILDLINK_TREE+=	-cpphs
