# $NetBSD$

VERSION=	20050117
DISTNAME=	ms_MY
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Malay dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
