# $NetBSD$

DISTNAME=	data-default-instances-dlist-0.0.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Default instances for types in dlist
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../wip/hs-data-default-class/buildlink3.mk"
.include "../../wip/hs-dlist/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
