# $NetBSD$
#

DISTNAME=	hinstaller-2008.2.16
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Installer wrapper for Haskell applications
LICENSE=	gnu-lgpl-v2.1

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
