# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-contracts-${IO_VERSION}
CATEGORIES=		devel

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		Contracts addon for Io

ADDON_NAME=		Contracts

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
