# $NetBSD$
#

DISTNAME=	binary-strict-0.4.8
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Binary deserialisation using strict ByteStrings

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
