# $NetBSD$

DISTNAME=	mahotas-1.1.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	graphics python
MASTER_SITES=	https://pypi.python.org/packages/source/m/mahotas/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://luispedro.org/software/mahotas
COMMENT=	Mahotas: Computer Vision Library
LICENSE=	mit

USE_LANGUAGES=	c++

.include "../../lang/python/egg.mk"
.include "../../math/py-numpy/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
