# $NetBSD$

CATEGORIES=		audio
MASTER_SITES=		http://www.xmms.org/files/Skins/

MAINTAINER=		cheusov@tut.by
HOMEPAGE=		http://www.xmms.org/skins.php
COMMENT=		Skin for XMMS

PKG_DESTDIR_SUPPORT=	user-destdir

DEPENDS+=		xmms>=1.2.0:../../audio/xmms

NO_CONFIGURE=		yes
NO_BUILD=		yes
NO_EXTRACT=		yes

WRKSRC=			${WRKDIR}

SKIN_DIR=		${PREFIX}/share/xmms/Skins

INSTALLATION_DIRS+=	${SKIN_DIR}

do-install:
	${INSTALL_DATA} ${DISTDIR}/${DISTNAME}${EXTRACT_SUFX} ${DESTDIR}${SKIN_DIR}
