# $NetBSD$

DISTNAME=		pdns-2.9.20
CATEGORIES=		net
MASTER_SITES=		http://downloads.powerdns.com/releases/

MAINTAINER=		aniou@smutek.pl
HOMEPAGE=		http://www.powerdns.com/
COMMENT=		Modern, advanced and high performance nameserver

USE_TOOLS+=		gmake
USE_LANGUAGES+=		c++
GNU_CONFIGURE=		YES

.include "../../devel/boost-headers/buildlink3.mk"
