# $NetBSD$

DISTNAME=	libyubikey-1.5
CATEGORIES=	security
MASTER_SITES=	http://yubico-c.googlecode.com/files/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://code.google.com/p/yubico-c/
COMMENT=	Yubikey library

LICENSE=	modified-bsd

PKG_DESTDIR_SUPPORT=	user-destdir
GNU_CONFIGURE=		yes
USE_LIBTOOL=		yes

.include "../../mk/bsd.pkg.mk"
