# $NetBSD$
#

DISTNAME=		ruby-gnome2-all-${VERSION}
CATEGORIES=		x11 ruby
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=ruby-gnome2/}

DISTINFO_FILE=		${.CURDIR}/../../wip/ruby-gnome2-all/distinfo

MAINTAINER=		dieter.NetBSD@pandora.be
HOMEPAGE=		http://ruby-gnome2.sourceforge.jp/

VERSION=		0.14.1
USE_RUBY_EXTCONF=	YES

.include "../../lang/ruby/modules.mk"
.include "../../mk/bsd.pkg.mk"
