# $NetBSD$
#

DISTNAME=	clips-6.24
CATEGORIES=	devel
MASTER_SITES=	http://www.ghg.net/clips/download/archive/

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	http://www.ghg.net/clips/CLIPS.html
COMMENT=	Tool for Building Expert Systems

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
