# $NetBSD$

VERSION=	20040405
DISTNAME=	bg_BG
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Bulgarian dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
