# $NetBSD$
#

DISTNAME=	ObjectName-1.0.0.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.haskell.org/HOpenGL/
COMMENT=	Explicitly handled object names
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
