# $NetBSD$
#

DISTNAME=		libhttpd-1.4
CATEGORIES=		wip
MASTER_SITES=		http://www.hughes.com.au/products/libhttpd/

MAINTAINER=		packages@NetBSD.org
HOMEPAGE=		http://www.hughes.com.au/products/libhttpd/
COMMENT=		Library that provides basic web server capabilities

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
