# $NetBSD$
#

DISTNAME=	binary-0.4.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://code.haskell.org/binary/
COMMENT=	Binary serialisation for Haskell values

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
