# $NetBSD$
#

DISTNAME=	binary-0.5.0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Binary serialisation for Haskell values

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
