# $NetBSD$

DISTNAME=	monad-control-0.3.3.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Lift control operations through monad transformers
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../devel/hs-transformers-base/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
