# $NetBSD$
#

DISTNAME=		ifstat-1.1
CATEGORIES=		net sysutils
MASTER_SITES=		${HOMEPAGE}

MAINTAINER=		charlie@rubberduck.com, florian@geiges.net
HOMEPAGE=		http://gael.roualland.free.fr/ifstat/
COMMENT=		Tool to report network interface bandwidth
LICENSE=		gnu-gpl-v2

PKG_DESTDIR_SUPPORT=	none
GNU_CONFIGURE=		yes

.include		"./options.mk"
.include		"../../mk/bsd.pkg.mk"
