# $NetBSD$
#

DISTNAME=		nsd-2.0.2
CATEGORIES=		wip
MASTER_SITES=		http://www.nlnetlabs.nl/downloads/nsd/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.nlnetlabs.nl/nsd/
COMMENT=		Name Server Daemon

USE_BUILDLINK2=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
