# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PTHREAD_STUBS_BUILDLINK3_MK:=	${PTHREAD_STUBS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	pthread-stubs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npthread-stubs}
BUILDLINK_PACKAGES+=	pthread-stubs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}pthread-stubs

.if ${PTHREAD_STUBS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.pthread-stubs+=	pthread-stubs>=0.1
BUILDLINK_PKGSRCDIR.pthread-stubs?=	../../wip/pthread-stubs
.endif	# PTHREAD_STUBS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
