# $NetBSD$
#

DISTNAME=	libinotify-20120113
CATEGORIES=	wip
MASTER_SITES=	http://on.encoreinteractive.ca/opensource/

MAINTAINER=	msporleder@gmail.com
HOMEPAGE=	http://on.encoreinteractive.ca/opensource/
COMMENT=	portable inotify userland lib
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=          yes

.include "../../mk/bsd.pkg.mk"
