# $NetBSD$
.include "../../wip/dwb-gtk3/Makefile.common"

PKGNAME=        ${DISTNAME:S/dwb/dwb-gtk2/}
COMMENT=	Dynamic WebKit browser, gtk2 version

.include "../../www/webkit24-gtk/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
