# $NetBSD$
#

DISTNAME=		alex-2.3.2
PKGNAME=		${DISTNAME}
CATEGORIES=		devel
MAINTAINER=		emil@math.su.se
HOMEPAGE=		http://www.haskell.org/alex/
COMMENT=		Tool for generating lexical analysers in Haskell

USE_TOOLS+=		perl


.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
