# $NetBSD$
#

DISTNAME=	alex-2.3.5
PKGNAME=	${DISTNAME}
CATEGORIES=	devel
MAINTAINER=	emil@math.su.se
HOMEPAGE=	http://www.haskell.org/alex/
COMMENT=	Tool for generating lexical analysers in Haskell
LICENSE=	modified-bsd

USE_TOOLS+=	perl

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
