# $NetBSD$
#

DISTNAME=	alex-3.0.4
PKGNAME=	${DISTNAME}
CATEGORIES=	devel
MAINTAINER=	esg@sdf.lonestar.org
HOMEPAGE=	http://www.haskell.org/alex/
COMMENT=	Tool for generating lexical analysers in Haskell
LICENSE=	modified-bsd

USE_TOOLS+=	perl

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-QuickCheck/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
