# $NetBSD$
#

DISTNAME=	HList-0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell Heterogeneous Lists
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
