# $NetBSD$

DISTNAME=	transformers-compat-0.3
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Small compatibility shim exposing the new types
LICENSE=	modified-bsd


.include "../../mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
