# $NetBSD$
#

DISTNAME=	transformers-compat-0.1.1.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	http://github.com/ekmett/transformers-compat/
COMMENT=	Small compatibility shim exposing the new types
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
