# $NetBSD$
#

DISTNAME=		qcad-manual-hu-2.0.4.0-1.html
PKGNAME=		qcad-manual-hu-2.0.4.0

.include "../qcad/Makefile.common"

COMMENT=		Online manual for QCad 2D CAD package, Hungarian

CONFLICTS=		qcad-manual-{[!h]?,?[!u]}-[0-9]*

.include "../qcad-manual-en/Makefile.common"
