# $NetBSD$
#

DISTNAME=	HDBC-2.1.0
CATEGORIES=	databases

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell Database Connectivity

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-convertible/buildlink3.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-time/buildlink3.mk"
.include "../../wip/hs-utf8-string/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
