# $NetBSD$

DISTNAME=	pylzma-0.4.4
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/py//}
CATEGORIES=	archivers python
MASTER_SITES=	https://pypi.python.org/packages/source/p/pylzma/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://www.joachim-bauch.de/projects/pylzma/
COMMENT=	Python bindings for the LZMA library by Igor Pavlov
LICENSE=	gnu-lgpl-v3

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
