# $NetBSD$
#

DISTNAME=	hztool-4.3
CATEGORIES=	misc
MASTER_SITES=	http://www.hepforge.org/archive/hztool/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://projects.hepforge.org/hztool//
COMMENT=	Robust model-to-data comparisons
LICENSE=	gnu-gpl-v2

CHECK_PORTABILITY_SKIP=  configure

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++ fortran

.include "../../mk/bsd.pkg.mk"
