# $NetBSD$

BUILDLINK_TREE+=	clang

.if !defined(CLANG_BUILDLINK3_MK)
CLANG_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.clang+=	clang>=2.6nb2
BUILDLINK_PKGSRCDIR.clang?=	../../wip/clang

.endif	# CLANG_BUILDLINK3_MK

BUILDLINK_TREE+=	-clang
