# $NetBSD$
#

DISTNAME=	storablevector-0.2.7.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast, packed, strict storable arrays
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-QuickCheck/buildlink3.mk"
.include "../../wip/hs-non-negative/buildlink3.mk"
.include "../../wip/hs-syb/buildlink3.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../wip/hs-utility-ht/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
