# $NetBSD$
#

DISTNAME=	attoparsec-0.10.4.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast combinator parsing for bytestrings
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
