# $NetBSD$
#

DISTNAME=	attoparsec-0.9.1.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast combinator parsing for bytestrings
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-deepseq/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
