# $NetBSD$

MOZILLA=		firefox2
EXTRACT_SUFX=		.tar.bz2
COMMENT=		Lightweight gecko-based web browser

MOZILLA_USE_GTK2=	# yes
MOZILLA_USE_XFT=	YES

.include "../../wip/firefox2/Makefile-firefox.common"
.include "../../mk/bsd.pkg.mk"
