# $NetBSD$

DISTNAME=	Date-1.3

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://pear.php.net/package/Date
COMMENT=	PHP Date and Time Zone Classes

.include "../../wip/php4/pear.mk"
.include "../../mk/bsd.pkg.mk"
