# $NetBSD$
#

DISTNAME=	fingertree-0.0.1.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Generic finger-tree structure, with example instances
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
