# $NetBSD$
#

DISTNAME=		blueproxy-1.3
CATEGORIES=		net
MASTER_SITES=		http://anil.recoil.org/projects/

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://anil.recoil.org/projects/blueproxy.html
COMMENT=		RFCOMM <-> TCP proxy
#LICENSE=		# TODO

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../wip/bluez-libs/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
