# $NetBSD$

PKGNAME=	pike-MIME-${PIKE_VERSION}
CATEGORIES=	lang
COMMENT=	MIME module for Pike programming language

MODULE_NAMES=	MIME
MODULE_DIRS=	modules/MIME
MODULE_SO=	___MIME.so

.include "../../wip/pike-core/Makefile.common"
.include "../../wip/pike-core/Makefile.modules_common"

.include "../../mk/bsd.pkg.mk"
