# $NetBSD$

DISTNAME=		Text-German-0.03
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=../../authors/id/U/UL/ULPFR/}

MAINTAINER=	kuli0020@umn.edu
HOMEPAGE=	http://search.cpan.org/dist/Text-German/
COMMENT=		German grundform reduction

PERL5_PACKLIST= ${PERL5_SITEARCH}/auto/Text/German/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
