# $NetBSD$
#

PKGNAME=	php-${PHP5_VERSION}
CATEGORIES=	www

MAINTAINER=	pancake@phreaker.net
HOMEPAGE=	http://www.php.net/
COMMENT=	PHP Hypertext Preprocessor version 5

USE_BUILDLINK3=	YES
GNU_CONFIGURE=	YES
USE_GNU_TOOLS+=	make

.include "Makefile.common"
.include "../../mk/bsd.pkg.mk"
