# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBNMS_BUILDLINK3_MK:=	${LIBNMS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libnms
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibnms}
BUILDLINK_PACKAGES+=	libnms
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libnms

.if ${LIBNMS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libnms+=	libnms>=0.6.0
BUILDLINK_PKGSRCDIR.libnms?=	../../wip/libnms
.endif	# LIBNMS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
