# $NetBSD$

DISTNAME=	libparsifal-0.7.3
CATEGORIES=	textproc
MASTER_SITES=	http://www.saunalahti.fi/~samiuus/toni/xmlproc/

MAINTAINER=	josediazfer@yahoo.es
HOMEPAGE=	http://www.saunalahti.fi/~samiuus/toni/xmlproc/
COMMENT= 	XML parser with implementation SAX2

HAS_CONFIGURE=  YES

CONFIGURE_ARGS+=--prefix=${LOCALBASE}

.include "../../mk/bsd.pkg.mk"
