# $NetBSD$
#

DISTNAME=		blassic-0.8.1
CATEGORIES=		lang
MASTER_SITES=		http://www.arrakis.es/~ninsesabe/blassic/
EXTRACT_SUFX=		.tgz

MAINTAINER=		ivaniclixx@terra.es
HOMEPAGE=		http://www.arrakis.es/~ninsesabe/blassic/
COMMENT=		Blassic is a classic Basic interpreter

USE_BUILDLINK3=		yes
GNU_CONFIGURE=		yes
USE_X11=                yes

.include "../../mk/bsd.pkg.mk"
