# $NetBSD$
#

DISTNAME=	hostname-1.0
CATEGORIES=	sysutils

MAINTAINER=	pho@cielonegro.org
COMMENT=	Package providing a cross-platform means of determining the hostname
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
