# $NetBSD$

DISTNAME=	pandoc-types-1.12.3.2
CATEGORIES=	textproc

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Types for representing a structured document
LICENSE=	gnu-gpl-v2


.include "../../wip/mk/haskell.mk"
.include "../../converters/hs-aeson/buildlink3.mk"
.include "../../devel/hs-syb/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
