# $NetBSD$
#

DISTNAME=	hxt-curl-9.1.1
CATEGORIES=	www

MAINTAINER=	pho@cielonegro.org
COMMENT=	LibCurl interface for HXT
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-curl/buildlink3.mk"
.include "../../wip/hs-hxt/buildlink3.mk"
.include "../../wip/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
