# $NetBSD$

DISTNAME=	param-1.3.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://pypi.python.org/packages/source/p/param/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://ioam.github.com/param/
COMMENT=	Declarative Python programming using Parameters
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
