# $NetBSD$
#

DISTNAME=		dxmake-2.11
CATEGORIES=		devel
MASTER_SITES=		http://apollo.backplane.com/FreeBSDPorts/

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://apollo.backplane.com/FreeBSDPorts/
COMMENT=		Yet another make tool

.include "../../mk/bsd.pkg.mk"
