# $NetBSD$

.include "../../wip/heirloom-dirs/Makefile.prog2.common"

PKGNAME=	heirloom-tsort-${HEIRLOOM_VER}
CATEGORIES=	textsproc

MAKE_FLAGS+=	SUBDIRS="libcommon build tsort"

.include "../../mk/bsd.pkg.mk"
