# $NetBSD$
#

DISTNAME=		Kahua-0.3.2
CATEGORIES=		wip
MASTER_SITES=		http://www.kahua.org/download/kahua/
EXTRACT_SUFX=		.tgz

MAINTAINER=		nel@soraneko.com
HOMEPAGE=		http://www.kahua.org/download/kahua/
COMMENT=		Kahua is a web application framework for Gauche

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../lang/gauche/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
