# $NetBSD$
#

DISTNAME=	zlib-0.5.4.0
CATEGORIES=	archivers

MAINTAINER=	pho@cielonegro.org
COMMENT=	Zlib binding for Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
