# $NetBSD$
#

DISTNAME=	zlib-0.5.0.0
PKGREVISION=	1
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Zlib binding for Haskell

.include "../../wip/mk/haskell.mk"
.include "../../devel/zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
