# $NetBSD$

DISTNAME=	dwb-2013.03.30
CATEGORIES=	wip
MASTER_SITES=	https://bitbucket.org/portix/dwb/downloads/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://bitbucket.org/portix/dwb/downloads/
COMMENT=	webkit browser
LICENSE=	gnu-gpl-v3

USE_TOOLS=	gmake

.include "../../x11/gtk3/buildlink3.mk"
.include "../../net/libsoup24/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
