# $NetBSD$
#

DISTNAME=	stringsearch-0.3.6.2
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast searching, splitting and replacing of ByteStrings
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
