# $NetBSD$

DISTNAME=	stringsearch-0.3.6.5
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast searching, splitting and replacing of ByteStrings
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
