# $NetBSD$
#

DISTNAME=	syb-0.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.cs.uu.nl/wiki/GenericProgramming/SYB
COMMENT=	Haskell "Scrap Your Boilerplate" Library
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
