# $NetBSD$

PKGNAME=	pike-Pipe-${PIKE_VERSION}
CATEGORIES=	lang
COMMENT=	PIPE module for Pike programming language

MODULE_NAMES=	Pipe
MODULE_DIRS=	modules/Pipe
MODULE_SO=	Pipe.so

.include "../../wip/pike-core/Makefile.common"
.include "../../wip/pike-core/Makefile.modules_common"

.include "../../mk/bsd.pkg.mk"
