# $NetBSD$
#

DISTNAME=	AOPython-1.0.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/AOP/aop/}
CATEGORIES=	devel
MASTER_SITES=	http://pypi.python.org/packages/source/A/AOPython/
EXTRACT_SUFX=	.zip

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://pieces.openpolitics.com/?s=AOPython
COMMENT=	Aspect Oriented Python
LICENSE=	python-software-foundation

USE_LANGUAGES=	# none
PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
