# $NetBSD$
#

DISTNAME=	hxt-regex-xmlschema-9.1.0
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Regular expression library for W3C XML Schema regular expressions
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-hxt-charproperties/buildlink3.mk"
.include "../../wip/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
