# $NetBSD$
#

DISTNAME=	cautious-file-1.0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Ways to write a file cautiously to reduce the chances of data loss
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
