# $NetBSD$

DISTNAME=	msdas-0.0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://pypi.python.org/packages/source/m/msdas/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://pythonhosted.org/msdas/
COMMENT=	Mass Spectrometry analysis
LICENSE=	gnu-lgpl-v3

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
