# $NetBSD$
#

DISTNAME=	HSH-1.2.6
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_HASKELL_HACKAGE:=HSH/1.2.6/}

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://software.complete.org/hsh
COMMENT=	Library to mix shell scripting with Haskell programs

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk" # This should be "../../mk/haskell.mk"
.include "../../wip/MissingH/buildlink3.mk"
.include "../../wip/hslogger/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
