# $NetBSD$

PKGNAME=	ocaml-${DISTNAME}
DISTNAME=	ounit-2.0.0
CATEGORIES=	devel
MASTER_SITES=	http://forge.ocamlcore.org/frs/download.php/1258/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ounit.forge.ocamlcore.org/
COMMENT=	Unit test framework for OCaml
LICENSE=	mit

OCAML_USE_OASIS=	yes

.include "../../mk/ocaml.mk"
.include "../../mk/bsd.pkg.mk"
