# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBHARU_BUILDLINK3_MK:=	${LIBHARU_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libharu
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibharu}
BUILDLINK_PACKAGES+=	libharu
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libharu

.if ${LIBHARU_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libharu+=	libharu>=2.1.0
BUILDLINK_PKGSRCDIR.libharu?=	../../wip/libharu
.endif	# LIBHARU_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
