# $NetBSD$

DISTNAME=	system-filepath-0.4.7
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	High-level, byte-based file and directory path manipulations
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
