# $NetBSD$
#

DISTNAME=	memoize-1.3.1
CATEGORIES=	misc
MASTER_SITES=	http://rubyforge.org/frs/download.php/61792/

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	http://www.rubyforge.org/projects/shards
COMMENT=	Speeds up methods at the cost of memory (or disk space)
LICENSE=	artistic-2.0

PKG_DESTDIR_SUPPORT=	user-destdir

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
