# $Id$

DISTNAME=	pygeoip-0.3.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://pypi.python.org/packages/source/p/pygeoip/

MAINTAINER=	bartosz.kuzma@gmail.com
HOMEPAGE=	https://github.com/appliedsec/pygeoip
COMMENT=	Pure Python GeoIP API
LICENSE=	gnu-lgpl-v3

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
