# $NetBSD$
#

DISTNAME=	arabtex
PKGNAME=	tex-${DISTNAME}-3.11s
TEXLIVE_REV=	17095

MAINTAINER=	kamelderouiche@yahoo.com
COMMENT=	Macros and fonts for typesetting Arabic

CONFLICTS+=	teTeX-texmf<=3.0nb22

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
