# $NetBSD$
#

DISTNAME=	numeric-quest-0.1.1
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Math and quantum mechanics
LICENSE=	gnu-gpl-v3

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
