# $NetBSD$
#

DISTNAME=	non-negative-0.1
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Non-negative numbers
LICENSE=	gnu-gpl-v3

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-QuickCheck/buildlink3.mk"
.include "../../wip/hs-utility-ht/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
