# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBDRM_BUILDLINK3_MK:=	${LIBDRM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libdrm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdrm}
BUILDLINK_PACKAGES+=	libdrm

.if !empty(LIBDRM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libdrm+=	libdrm>=1.0.5
BUILDLINK_PKGSRCDIR.libdrm?=	../../wip/libdrm
.endif	# LIBDRM_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
