# $NetBSD$
#

PEAR_CHANNEL=		pear.symfony.com
PEAR_CHANNEL_ALIAS=	symfony2
PEAR_CHANNEL_VERSION=	2013.07.12

MAINTAINER=		noud4@home.nl

.include "../../wip/mk/pear-channel.mk"
.include "../../mk/bsd.pkg.mk"
