# $NetBSD$
#

DISTNAME=	convertible-text-0.4.0.1
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Typeclasses and instances for converting between types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-attempt/buildlink3.mk"
.include "../../devel/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
