# $NetBSD$
#

DISTNAME=		matanza-0.13
CATEGORIES=		games
MASTER_SITES=		http://bachue.com/matanza/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://freshmeat.net/redir/matanza/6227/url_tgz/
COMMENT=		Multiplayer space shooter ascii-art game

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
