# $NetBSD$

DISTNAME=	nullpop-0.2
CATEGORIES=	mail
MASTER_SITES=	http://memberwebs.com/nielsen/software/nullpop/

HOMEPAGE=	http://memberwebs.com/nielsen/software/nullpop/

MAINTAINER=	shaun@inerd.com
COMMENT=	POP3 server that allows logins, but never returns any email

PKG_DESTDIR_SUPPORT=	none

GNU_CONFIGURE=	yes

CONFIGURE_ARGS+=--libexecdir="${PREFIX}/bin"

.include "../../mk/bsd.pkg.mk"
