# $NetBSD$
#

CATEGORIES=             databases math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/ISwR.html}
COMMENT=		Data sets and scripts for 'Introductory Statistics with R'

R_PKGNAME=              ISwR
R_PKGVER=               1.0-3

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
