# $NetBSD$
#

DISTNAME=		e00pg-1.0.1
CATEGORIES=		wip
MASTER_SITES=		http://easynews.dl.sourceforge.net/sourceforge/e00pg/

MAINTAINER=		mchittur@cs.nmsu.edu
HOMEPAGE=		http://e00pg.sourceforge.net/
COMMENT=		Converting ESRI-E00 coverages into PostgreSQL/PostGIS sql instructions

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
