# $NetBSD$
#

DISTNAME=		e00pg-1.0.1
CATEGORIES=		geography
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=e00pg/}

MAINTAINER=		mchittur@cs.nmsu.edu
HOMEPAGE=		http://e00pg.sourceforge.net/
COMMENT=		Converting ESRI-E00 coverages into PostgreSQL/PostGIS sql instructions
LICENSE=		gnu-gpl-v2

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes
USE_FEATURES+=		snprintf

.include "../../mk/bsd.pkg.mk"
