# $NetBSD$
#

CATEGORIES=             math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/date.html}
COMMENT=		Functions for handling dates

R_PKGNAME=              date
R_PKGVER=               1.2-18

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
