# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-lzo-${IO_VERSION}
PKGREVISION=		1
CATEGORIES=		archivers

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		LZO addon for Io.

ADDON_NAME=		LZO

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
