# $NetBSD$

DISTNAME=	happy-1.19.4
PKGNAME=	${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	esg@sdf.lonestar.org
COMMENT=	LALR(1) parser generator for the functional language Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
