# $NetBSD$

DISTNAME=	clint-0.4.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	x11 python
MASTER_SITES=	https://pypi.python.org/packages/source/c/clint/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/kennethreitz/clint
COMMENT=	Python Command-line Application Tools
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
