# $NetBSD$

NEED_LIBCRYPT=	1

.include "../../wip/heirloom-common/Makefile.prog2.common"

PKGNAME=	heirloom-su-${HEIRLOOM_VER}
CATEGORIES=	textproc

MAKE_FLAGS+=	SUBDIRS="libcommon build su"

.include "../../mk/bsd.pkg.mk"
