# $NetBSD$

BUILDLINK_TREE+=	iksemel

.if !defined(IKSEMEL_BUILDLINK3_MK)
IKSEMEL_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.iksemel+=	iksemel>=1.3
BUILDLINK_PKGSRCDIR.iksemel?=	../../wip/iksemel
.endif # IKSEMEL_BUILDLINK3_MK

BUILDLINK_TREE+=	-iksemel
