# $NetBSD$

CVS_SITES=		mplayer ffmpeg
CVS_REPOSITORY.mplayer=	:pserver:anonymous:@mplayerhq.hu:/cvsroot/mplayer
CVS_MODULE.mplayer=	main
CVS_REPOSITORY.ffmpeg=	:pserver:anonymous:@mplayerhq.hu:/cvsroot/ffmpeg
CVS_MODULE.ffmpeg=	ffmpeg

post-extract:
	${MV} ${WRKDIR}/ffmpeg/libav* ${WRKDIR}/mplayer/

.include "../../wip/mk/cvs-package.mk"
