# $NetBSD$
#

DISTNAME=	tagsoup-0.13
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www-users.cs.york.ac.uk/~ndm/tagsoup/
COMMENT=	Haskell library for parsing unstructured HTML code
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
