# $NetBSD: Makefile $
#

DISTNAME=	ccrypt-1.4
CATEGORIES=	security
MASTER_SITES=	http://www.mathstat.dal.ca/~selinger/ccrypt/download/

MAINTAINER=	poff@sixbit.org
HOMEPAGE=	http://www.mathstat.dal.ca/~selinger/ccrypt/
COMMENT=	Encrypts/decrypts files using Rijndael block cipher

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
