# $NetBSD$

DISTNAME=	Pint-0.3.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:tl}
CATEGORIES=	math
MASTER_SITES=	https://pypi.python.org/packages/source/P/Pint/
EXTRACT_SUFX=	.zip#md5=511e5f5a057d4859998270eed46ea927
FETCH_USING=	curl

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://pypi.python.org/packages/source/P/Pint/
COMMENT=	Physical quantities module
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
