# $NetBSD$

BUILDLINK_TREE+=	botan

.if !defined(BOTAN_BUILDLINK3_MK)
BOTAN_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.botan+=	botan>=1.8.6
BUILDLINK_PKGSRCDIR.botan?=	../../wip/botan
.endif	# BOTAN_BUILDLINK3_MK

BUILDLINK_TREE+=	-botan
