# $NetBSD$
#

DISTNAME=	${FILTER_NAME}-1.40.00
CATEGORIES=	mail
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=logreporters/}
EXTRACT_SUFX=	.tgz

MAINTAINER=	noud4@home.nl
HOMEPAGE=	http://logreporters.sourceforge.net/
COMMENT=	Postfix log reporting utility
LICENSE=	mit

FILTER_NAME=	postfix-logwatch

.include "options.mk"

.include "../../wip/postfix-logwatch/Makefile.common"

.include "../../mk/bsd.pkg.mk"
