# $NetBSD$

DISTNAME=	lazy-io-0.1.0
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
HOMEPAGE=	https://github.com/kawu/lazy-io
COMMENT=	Lazy IO
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
