# $NetBSD$
#

DISTNAME=	topless-1.46
CATEGORIES=	sysutils
MASTER_SITES=	http://people.freebsd.org/~daichi/src/

MAINTAINER=	obata@lins.jp
HOMEPAGE=	http://www.ongs.net/~daichi/#topless
COMMENT=	Display and update information of target command like 'top'

USE_TOOLS+=	perl

.include "../../mk/bsd.pkg.mk"
