# $NetBSD$

VERSION=	20060607
DISTNAME=	hr_HR
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Croatian dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
