# $NetBSD$
#

DISTNAME=	parsec-3.1.3
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Monadic parser combinators
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
