# $NetBSD$
#

DISTNAME=	parsec-3.1.0
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.cs.uu.nl/~daan/parsec.html
COMMENT=	Monadic parser combinators
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-syb/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
