# $NetBSD$
#

DISTNAME=	hashed-storage-0.3.8
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Hashed file storage support code
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-extensible-exceptions/buildlink3.mk"
.include "../../wip/hs-mmap/buildlink3.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
