# $NetBSD$

DISTNAME=	exceptions-0.6.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Extensible optionally-pure exceptions
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
