# $NetBSD$
#

DISTNAME=		typhoon-1.11.0
CATEGORIES=		databases
MASTER_SITES=		http://users.footprints.net/~kaz/

MAINTAINER=		adam@monkeybyte.org
HOMEPAGE=		http://users.footprints.net/~kaz/
COMMENT=		Database management system

.include "../../mk/bsd.pkg.mk"
