# $NetBSD$
#

DISTNAME=		mesure-0.3
CATEGORIES=		wip sysutils
MASTER_SITES=		ftp://ftp.nopcode.org/prj/mesure/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.nopcode.org/?t=mesure
COMMENT=		Tool to measure different kind of streams
GNU_CONFIGURE=		yes
USE_GNU_TOOLS+=		make
USE_BUILDLINK3=		yes

.include "../../mk/bsd.pkg.mk"
