# $NetBSD$
#

VERS=				1.1.1
DISTNAME=			errorhandler-${VERS}
PKGNAME=			${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=			textproc
MASTER_SITES=		http://pypi.python.org/packages/source/e/errorhandler/

MAINTAINER=			helgoman@users.sourceforge.net
HOMEPAGE=			http://www.simplistix.co.uk/software/python/errorhandler
COMMENT=			Logging framework handler
LICENSE=			mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
