# $NetBSD: Makefile,v 1.20 2007/12/02 00:11:10 wiz Exp $
#

.include "../../wip/mawk-uxre/Makefile.common"

PKGNAMESUF=	rxspencer

LIBS=		-lrxspencer

DESCR_SRC+=	${.CURDIR}/DESCR.addon

.include "../../devel/librxspencer/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
