# $NetBSD$
#

DISTNAME=	uniplate-1.6
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Help writing simple, concise and fast generic operations

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-syb/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
