# $NetBSD$
#

DISTNAME=	hxt-charproperties-9.1.1.1
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Character properties and classes for XML and Unicode
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
