# $NetBSD$

DISTNAME=	mcl-12-135
CATEGORIES=	math
MASTER_SITES=	http://micans.org/mcl/src/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://micans.org/mcl/src/
COMMENT=	Markov Cluster algorithm
LICENSE=	gnu-gpl-v3

GNU_CONFIGURE=	yes

.include "../../mk/pthread.buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
