# $NetBSD: Makefile $
#

DISTNAME=	wmclockmon-0.8.1
CATEGORIES=	time x11
MASTER_SITES=   http://tnemeth.free.fr/projets/programmes/

MAINTAINER=	poff@sixbit.org
HOMEPAGE=	http://tnemeth.free.fr/projets/dockapps.html
COMMENT=	Windowmaker dockapp for time/date

GNU_CONFIGURE=	yes

.include "../../mk/x11.buildlink3.mk"
.include "../../x11/gtk/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
