# $NetBSD$
#

DISTNAME=		db.1.86
PKGNAME=		db1-1.86
CATEGORIES=		databases
MASTER_SITES=		http://www.sleepycat.com/update/snapshot/

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://www.sleepycat.com/
COMMENT=		Berkeley DB 1.86

.include "../../mk/bsd.pkg.mk"
