# $NetBSD$

DISTNAME=	jewish-0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	time python
MASTER_SITES=	https://pypi.python.org/packages/source/j/jewish/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/emosenkis/jewish
COMMENT=	Jewish calendar calculations
LICENSE=	mit

USE_LANGUAGES=	# none

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
