# $NetBSD$
#

DISTNAME=	pyserial-2.6
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	comms
MASTER_SITES=	http://pypi.python.org/packages/source/p/pyserial/

MAINTAINER=	frederic@fauberteau.org
HOMEPAGE=	http://pyserial.sourceforge.net/
COMMENT=	Access for the serial port
LICENSE=	python-software-foundation

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
