# $NetBSD$

BUILDLINK_TREE+=	omniORB

.if !defined(OMNIORB_BUILDLINK3_MK)
OMNIORB_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.omniORB+=	omniORB>=4.1.2
BUILDLINK_PKGSRCDIR.omniORB?=	../../wip/omniORB
.endif # OMNIORB_BUILDLINK3_MK

BUILDLINK_TREE+=	-omniORB
