# $NetBSD: Makefile,v 1.16 2011/01/23 07:55:13 markd Exp $

DISTNAME=	konsole-${_KDE_VERSION}
CATEGORIES=	x11
COMMENT=	a terminal emulator for the K Desktop Environment

.include "../../wip/kde4/Makefile.kde4"

.include "../../wip/kde4/kde4.mk"

.include "../../wip/kdelibs4/buildlink3.mk"
.include "../../wip/kde-baseapps4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
