# $NetBSD$
#

DISTNAME=	arrow-list-0.2.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	List arrows for Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
