# $NetBSD$

DISTNAME=	yaml_waml-0.3.0
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	https://github.com/kakutani/yaml_waml
COMMENT=	YAML WorkAround for Multibyte Language
LICENSE=	mit

DEPENDS+=	${RUBY_PKGPREFIX}-rspec>=1.2.9:../../devel/ruby-rspec

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
