# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HS_SHA_BUILDLINK3_MK:=	${HS_SHA_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-SHA
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-SHA}
BUILDLINK_PACKAGES+=	hs-SHA
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-SHA

.if ${HS_SHA_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-SHA?=	build
BUILDLINK_API_DEPENDS.hs-SHA+=	hs-SHA>=1.0.3
BUILDLINK_PKGSRCDIR.hs-SHA?=	../../wip/hs-SHA
.endif	# HS_SHA_BUILDLINK3_MK

.include "../../wip/QuickCheck/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
