# $NetBSD$
#

DISTNAME=	SHA-1.4.0
CATEGORIES=	security

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell implementation of SHA digest functions
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-binary/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
