# $NetBSD$
#

DISTNAME=	SHA-1.0.3
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	security

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell implementation of SHA digest functions

.include "../../wip/mk/haskell.mk"
.include "../../wip/QuickCheck/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
