# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-blowfish-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		crypto

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		Blowfish addon for Io.

ADDON_NAME=		Blowfish

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
