# $NetBSD$
#

BUILDLINK_TREE+=	libpgf

.if !defined(LIBPGF_BUILDLINK3_MK)
LIBPGF_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.libpgf+=	libpgf>=6.14.12
BUILDLINK_PKGSRCDIR.libpgf?=	../../wip/libpgf
.endif	# LIBPGF_BUILDLINK3_MK

BUILDLINK_TREE+=	-libpgf
