# $NetBSD$
#

DISTNAME=	ghc-paths-0.1.0.9
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Knowledge of GHC's installation directories
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
