# $NetBSD$
#

DISTNAME=	curl-1.3.5
CATEGORIES=	www

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell binding to libcurl

.include "../../wip/mk/haskell.mk"
.include "../../www/curl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
