# $NetBSD$
#

DISTNAME=		pyxdg-0.15
PKGNAME=		${PYPKGPREFIX}-xdg-0.15
CATEGORIES=		sysutils python
MASTER_SITES=		http://www.freedesktop.org/~lanius/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://pyxdg.freedesktop.org/
COMMENT=		XDG handling library

PKG_DESTDIR_SUPPORT=	user-destdir

USE_TOOLS+=		pkg-config
PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
