# $NetBSD$
#

DISTNAME=		pyxdg-0.15
PKGNAME=	py23-xdg-0.15 # XXX
CATEGORIES=		wip sysutils python
MASTER_SITES=		http://www.freedesktop.org/~lanius/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://pyxdg.freedesktop.org/
COMMENT=		XDG handling library

USE_TOOLS+=		pkg-config
PYDISTUTILSPKG= yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
