# $NetBSD$

DISTNAME=	simplegeneric-0.8.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://pypi.python.org/packages/source/s/simplegeneric/
EXTRACT_SUFX=	.zip

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://cheeseshop.python.org/pypi/simplegeneric
COMMENT=	Simple generic functions for Python
LICENSE=	zpl

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
