# $NetBSD$
#

CATEGORIES=             databases math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/DAAG.html}
COMMENT=		Interface between GRASS 5.0 geographical information system and R

R_PKGNAME=              GRASS
R_PKGVER=               0.2-20

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
