# $NetBSD$

DISTNAME=		xyssl-0.1
CATEGORIES=		devel
MASTER_SITES=		http://xyssl.org/code/download/
EXTRACT_SUFX=		.tgz

MAINTAINER=		kh.p@no-log.org
HOMEPAGE=		http://xyssl.org/
COMMENT=		SSL minimalist library

NO_CONFIGURE=		yes
USE_TOOLS+=		gmake
USE_LANGUAGES=		c c++

.include "../../mk/bsd.pkg.mk"
