# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-continuedfraction-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		math

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		ContinuedFraction addon for Io.

ADDON_NAME=		ContinuedFraction

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
