# $NetBSD$
#

DISTNAME=	emelfm2-0.0.9
CATEGORIES=	sysutils
MASTER_SITES=	http://emelfm2.org/rel/

MAINTAINER=	lems@gmx.net
HOMEPAGE=	http://emelfm2.org/
COMMENT=	Fast, two-pane filemanager using GTK2

USE_DIRS+=	xdg-1.1
USE_TOOLS+=	gmake

.include "../../x11/gtk2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
