# $NetBSD$
#

CATEGORIES=             math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/abind.html}
COMMENT=		Combine multi-dimensional arrays

R_PKGNAME=		abind
R_PKGVER=               1.1-0

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
