# $NetBSD$
#

DISTNAME=	data-accessor-0.2.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.haskell.org/haskellwiki/Record_access
COMMENT=	Utilities for accessing and manipulating field of records
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
