# $NetBSD$

.include "../xfce4/Makefile.common"

DISTNAME=	xfce4-mixer-0.1
CATEGORIES=	audio
COMMENT=	XFce4 mixer plugin

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../textproc/libxml2/buildlink2.mk"
.include "../../wip/xfce4-panel/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
