# $NetBSD$
#

DISTNAME=	Mail_Mime-1.8.8
CATEGORIES=	mail

MAINTAINER=	khorben@defora.org
HOMEPAGE=	http://pear.php.net/package/Mail_Mime/
COMMENT=	Mail_Mime provides classes to create MIME messages

LICENSE=	modified-bsd

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
