# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-systemcall-${IO_VERSION}
CATEGORIES=		sysutils

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		SystemCall addon for Io

ADDON_NAME=		SystemCall

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
