# $NetBSD$
#

DISTNAME=	parseargs-0.1.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Command-line argument parsing library for Haskell programs

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
