# $NetBSD$

DISTNAME=	primitive-0.5.3.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Wrappers for primitive operations
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
