# $NetBSD$
#

DISTNAME=	primitive-0.3.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Wrappers for primitive array operations from GHC.Prim
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
