# $NetBSD$
#

DISTNAME=	primitive-0.5.1.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Wrappers for primitive operations
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
