# $NetBSD$
#

DISTNAME=	regex-posix-0.94.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Replaces/Enhances Haskell Text.Regex

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-regex-base/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
