# $NetBSD$
#

DISTNAME=	regex-posix-0.95.2
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Replaces/Enhances Haskell Text.Regex
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-regex-base/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
