# $NetBSD$

DISTNAME=		shed-1.12
CATEGORIES=		sysutils
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=shed/}

MAINTAINER=		lkundrak@skosi.org
HOMEPAGE=		http://shed.sourceforge.net/
COMMENT=		Simple curses-based hexadecimal editor

GNU_CONFIGURE=		yes

.include "../../devel/ncurses/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
