# $NetBSD$
#

DISTNAME=	mkcabal-0.4.1.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://code.haskell.org/~dons/code/mkcabal
COMMENT=	Generate cabal files for a Haskell project

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-pcre-light/buildlink3.mk"
.include "../../wip/hs-readline/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
