# $NetBSD$
#
# used by x11/py-keybinder/Makefile

DISTNAME=	keybinder-0.3.0
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_GENTOO:=distfiles/}

HOMEPAGE=	https://github.com/engla/keybinder
LICENSE=	gnu-gpl-v2

PKGCONFIG_OVERRIDE+=	libkeybinder/keybinder.pc.in
