# $NetBSD$
#

DISTNAME=	Net_URL2-2.0.0
CATEGORIES=	www

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Class for parsing and handling URL
LICENSE=	2-clause-bsd

USE_LANGUAGES=	# none

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
