# $NetBSD$
#

DISTNAME=		p3nfs-5.16
CATEGORIES=		wip
MASTER_SITES=		http://www.koeniglich.de/packages/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.koeniglich.de/packages/
COMMENT=		Symbian to UNIX NFS daemon

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
