# $NetBSD$

.include "../../mail/squirrelmail/plugin.mk"

PLUGIN_NAME=	compatibility
PLUGIN_VERSION=	1.3

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.squirrelmail.org/plugin_view.php?id=152
COMMENT=	Provides backward compatibility to SquirrelMail plugins

.include "../../mk/bsd.pkg.mk"
