# $NetBSD$
#

DISTNAME=	gtk2hs-buildtools-0.12.0
PKGNAME=	${DISTNAME}
CATEGORIES=	x11

MAINTAINER=	pho@cielonegro.org
COMMENT=	Tools to build the Gtk2Hs suite of User Interface libraries
LICENSE=	gnu-gpl-v2

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
