# $NetBSD$

DISTNAME=	openpyxl-1.6.2
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc
MASTER_SITES=	https://pypi.python.org/packages/source/o/openpyxl/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://openpyxl.readthedocs.org/
COMMENT=	Python library to read/write Excel 2007 xlsx/xlsm files
LICENSE=	mit

FETCH_USING=    curl

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
