# $NetBSD$
#

DISTNAME=	hxt-xslt-9.1.1
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	The XSLT modules for HXT
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-hxt/buildlink3.mk"
.include "../../wip/hs-hxt-xpath/buildlink3.mk"
.include "../../wip/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
