# $NetBSD$

.include "../xfce4/Makefile.common"

PKGNAME=	xfce4-fm-icons-${XFCE4_VERSION}
DISTNAME=	xffm-icons-${XFCE4_VERSION}
COMMENT=	XFce4 filemanager icons

.include "../../wip/xfce4-fm/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
