# $NetBSD$

.include "../xfce4/Makefile.common"

PKGNAME=	xfce4-fm-icons-${XFCE4_VERSION}
COMMENT=	XFce4 filemanager icons

WRKSRC=		${WRKDIR}/xfce4-extras/xffm-icons

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../textproc/libxml2/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
