# $NetBSD$

BUILDLINK_TREE+=	libsmf

.if !defined(LIBSMF_BUILDLINK3_MK)
LIBSMF_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.libsmf+=	libsmf>=1.3
BUILDLINK_PKGSRCDIR.libsmf?=	../../wip/libsmf

.endif	# LIBSMF_BUILDLINK3_MK

BUILDLINK_TREE+=	-libsmf
