# $NetBSD$
#

DISTNAME=	Test-MockModule-0.05
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	devel perl5
MASTER_SITES=	http://search.cpan.org/CPAN/authors/id/S/SI/SIMONFLK/

MAINTAINER=	ficovh@yahoo.com
HOMEPAGE=	http://search.cpan.org/CPAN/authors/id/S/SI/SIMONFLK/
COMMENT=	Override subroutines in a module for unit testing

PERL5_PACKLIST=	auto/Test/MockModule/.packlist
USE_LANGUAGES=	# none

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
