# $NetBSD: Makefile,v 1.7 2005/11/07 21:46:25 tv Exp $

DISTNAME=	pptp-1.7.0
CATEGORIES=	net
MASTER_SITES= 	${MASTER_SITE_SOURCEFORGE:=pptpclient/}

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://pptpclient.sourceforge.net/
COMMENT=	PPTP client package for Microsoft VPN servers

NOT_FOR_PLATFORM=	Interix-*-*

.include "../../mk/bsd.prefs.mk"
.include "../../mk/bsd.pkg.mk"
