# $NetBSD$
#

DISTNAME=		mingw-3.3.1
CATEGORIES=		cross
MASTER_SITES=		# empty
DISTFILES=		# empty

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://mingw.sf.net/
COMMENT=		GNU C Compiler for win32 cross development

.include "../../wip/mingw-binutils/buildlink2.mk"
.include "../../wip/mingw-gcc/buildlink2.mk"
.include "../../wip/mingw-libtool/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
