# $NetBSD$
#

DISTNAME=	pyface-4.2.0
PKGNAME=        ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	x11 python
MASTER_SITES=	https://www.enthought.com/repo/ets/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://www.enthought.com/repo/ets/
COMMENT=	Traits-capable windowing framewor
LICENSE=	modified-bsd

FETCH_USING=	curl

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
