# $NetBSD$
#

DISTNAME=		physfs-1.0.1
PKGNAME=		physicsfs
CATEGORIES=		devel
MASTER_SITES=		http://www.icculus.org/physfs/downloads/
EXTRACT_SUFX=		.tar.gz

MAINTAINER=		hugor@users.sourceforge.net
HOMEPAGE=		http://www.icculus.org/physfs/
COMMENT=		Library to provide abstract access to various archives

GNU_CONFIGURE=		yes
CONFIGURE_ARGS+=	--disable-testprog

.include		"../../mk/bsd.pkg.mk"
