# $NetBSD$
#

DISTNAME=	tcpflow-0.20
CATEGORIES=	security net
MASTER_SITES=	http://www.circlemud.org/pub/jelson/tcpflow/

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://www.circlemud.org/~jelson/software/tcpflow/
COMMENT=	Captures data transmitted as part of TCP connections

USE_BUILDLINK2=	YES

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
