# $NetBSD$

.include "../../wip/heirloom-dirs/Makefile.prog2.common"

PKGNAME=	heirloom-diff3-${HEIRLOOM_VER}
CATEGORIES=	textproc

MAKE_FLAGS+=	SUBDIRS="libcommon build diff3"

.include "../../mk/bsd.pkg.mk"
