# $NetBSD$

DISTNAME=	zip-archive-0.1.3.4
CATEGORIES=	lang

MAINTAINER=	zecrazytux@zecrazytux.net
COMMENT=	Haskell library providing functions for manipulating zip archives
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-digest/buildlink3.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-utf8-string/buildlink3.mk"
.include "../../wip/hs-zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
