# $NetBSD$
#

DISTNAME=	split-0.1.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Combinator library for splitting lists
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
