# $NetBSD$

DISTNAME=	Math_BigInteger-1.0.0
CATEGORIES=	math

MAINTAINER=	wenheping@gmail.com
HOMEPAGE=	http://pear.php.net/package/Math_BigInteger/
COMMENT=	Pure-PHP arbitrary precission integer arithmetic library

CONFLICTS=	php-pear-Math_BigInteger-[0-9]*

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
