# $NetBSD$

DISTNAME=	pyrr-0.2.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math python
MASTER_SITES=	https://pypi.python.org/packages/source/p/pyrr/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/adamlwgriffiths/Pyrr
COMMENT=	3D mathematical functions using NumPy
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../math/py-numpy/buildlink3.mk"
.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
