# $NetBSD$
#

DISTNAME=	cryptohash-0.9.0
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
HOMEPAGE=	http://github.com/vincenthz/hs-cryptohash
COMMENT=	Collection of crypto hashes, fast, pure and practical
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
