# $NetBSD$

BUILDLINK_TREE+=	tagsoup

.if !defined(TAGSOUP_BUILDLINK3_MK)
TAGSOUP_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.tagsoup?=	build
BUILDLINK_API_DEPENDS.tagsoup+=	tagsoup>=0.6
BUILDLINK_PKGSRCDIR.tagsoup?=	../../wip/tagsoup
.endif # TAGSOUP_BUILDLINK3_MK

BUILDLINK_TREE+=	-tagsoup
