# $NetBSD$
#

DISTNAME=	tagsoup-0.6
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www-users.cs.york.ac.uk/~ndm/tagsoup/
COMMENT=	Haskell library for parsing unstructured HTML code

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-network/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
