# $NetBSD$
#

DISTNAME=	concrete-typerep-0.1.0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Binary and Hashable instances for TypeRep
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-hashable/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
