# $NetBSD$
#

DISTNAME=	pnmcurve-0.0.1
CATEGORIES=	graphics
MASTER_SITES=	http://www.ecademix.com/JohannesHofmann/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.ecademix.com/JohannesHofmann/
COMMENT=	Apply tone curves to pnm images

GNU_CONFIGURE=	yes

.include "../../math/gsl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
