# $NetBSD$

DISTNAME=	eurosym.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-1.4
TEXLIVE_REV=	17265

MAINTAINER=	nico@orgrim.net
COMMENT=	Documentation for tex-eurosym

CONFLICTS+=	teTeX-texmf-[0-9]*

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
