# $NetBSD$
#

DISTNAME=		BeautifulSoup-3.0.4
PKGNAME=                ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		textproc
MASTER_SITES=		http://www.crummy.com/software/BeautifulSoup/download/

MAINTAINER=		dhowland@users.sourceforge.net
HOMEPAGE=		http://www.crummy.com/software/BeautifulSoup/
COMMENT=		HTML and XML parser for Python

DISTFILES=		BeautifulSoup.tar.gz

PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
