# $NetBSD$
#

DISTNAME=	QIO-1.2
CATEGORIES=	math

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=   http://www.cs.nott.ac.uk/~asg/QIO/
COMMENT=	QIO Monad is a library for defining quantum computations
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-random/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
