# $NetBSD$

DISTNAME=	nlib-0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	https://pypi.python.org/packages/source/n/nlib/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/mdipierro/canvas
COMMENT=	Numeric/scientific algorithms which do not required numpy
LICENSE=	modified-bsd


USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
