# $NetBSD$

DISTNAME=	heirloom-doctools-150406
CATEGORIES=	textproc
MASTER_SITES=	http://github.com/n-t-roff/heirloom-doctools/releases/download/150406/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	carsten.kunze@arcor.de
HOMEPAGE=	http://n-t-roff.github.io/heirloom/doctools.html
COMMENT=	Modernized troff implementation
LICENSE=	cddl-1.0

USE_LANGUAGES=	c c++

MAKE_FILE=	makefile
BUILD_TARGET=	dummy

.include "../../mk/bsd.pkg.mk"
