# $NetBSD$
#

DISTNAME=	random-1.0.1.1
CATEGORIES=	devel
LICENSE=	modified-bsd

MAINTAINER=	pho@cielonegro.org
COMMENT=	Random number library

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
