# $NetBSD$

PKGNAME=	ocaml-${DISTNAME}
DISTNAME=	type_conv-109.60.00
CATEGORIES=	converters
MASTER_SITES=	https://ocaml.janestreet.com/ocaml-core/109.60.00/individual/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/janestreet/type_conv/
COMMENT=	Generate code from type specifications
LICENSE=	apache-2.0

.include "../../devel/ocaml-findlib/buildlink3.mk"
.include "../../wip/mk/ocaml-oasis.mk"
.include "../../mk/bsd.pkg.mk"
