# $NetBSD$
#

DISTNAME=	mtl-2.0.1.0
CATEGORIES=	devel
LICENSE=	modified-bsd

MAINTAINER=	pho@cielonegro.org
COMMENT=	Monad classes using functional dependencies

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
