# $NetBSD$
#

DISTNAME=	mtl-1.1.0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Monad transformer library

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
