# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBLO_BUILDLINK3_MK:=	${LIBLO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	liblo
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nliblo}
BUILDLINK_PACKAGES+=	liblo
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}liblo

.if ${LIBLO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.liblo+=	liblo>=0.23
BUILDLINK_PKGSRCDIR.liblo?=	../../wip/liblo
BUILDLINK_DEPMETHOD.liblo?=	build
.endif	# LIBLO_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
