# $NetBSD$
#

DISTNAME=	asterisk-0.4.0
CATEGORIES=	chat
MASTER_SITES=	ftp://ftp.asterisk.org/pub/telephony/asterisk/ \
		ftp://ftp.asterisk.org/pub/telephony/asterisk/old-releases/

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://www.asteriskpbx.com/
COMMENT=	Open source PBX

USE_GNU_TOOLS+=	make

.include "../../mk/bsd.pkg.mk"
