# $NetBSD$
#

DISTNAME=	asterisk-0.4.0
CATEGORIES=	chat
MASTER_SITES=	ftp://ftp.asterisk.org/pub/telephony/asterisk/ \
		ftp://ftp.asterisk.org/pub/telephony/asterisk/old-releases/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.asteriskpbx.com/
COMMENT=	Open source PBX

USE_GMAKE=	yes

.include "../../mk/bsd.pkg.mk"
