# $NetBSD$
#

DISTNAME=		outguess-0.2
CATEGORIES=		security
MASTER_SITES=	http://mirror.sweon.net/madchat/crypto/stegano/unix/jpeg/ \
				http://www.outguess.org/ \
				ftp://ftp.fu-berlin.de/unix/security/outguess/ \
				http://www.mirrors.wiretapped.net/security/steganography/outguess/

MAINTAINER=		adam.hoka@gmail.com
HOMEPAGE=		http://www.outguess.org/
COMMENT=		JPEG steganography tool

WRKSRC=			${WRKDIR}/outguess
GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
