# $NetBSD$

DISTNAME=	mlmmj-1.2.11
CATEGORIES=	mail
MASTER_SITES=	${HOMEPAGE:=files/}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	uebayasi@NetBSD.org
HOMEPAGE=	http://mlmmj.mmj.dk/
COMMENT=	Mailing list managing made joyful

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
