# $NetBSD$

DISTNAME=	mlmmj-1.2.18.0
CATEGORIES=	mail
MASTER_SITES=	${HOMEPAGE:=releases/}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	uebayasi@NetBSD.org
HOMEPAGE=	http://mlmmj.org/
COMMENT=	Mailing list managing made joyful

PKG_DESTDIR_SUPPORT=	none

GNU_CONFIGURE=	yes
USE_TOOLS=	gmake

.include "../../mk/bsd.pkg.mk"
