# $NetBSD$
#

DISTNAME=	uClibc-0.9.20
CATEGORIES=	sysutils
MASTER_SITES=	http://www.uclibc.org/downloads/

MAINTAINER=	pancake@phreaker.net
HOMEPAGE=	http://www.uclibc.org/
COMMENT=	C library for developing embedded Linux systems

PKG_DESTDIR_SUPPORT=	none

USE_TOOLS+=	gmake

ONLY_FOR_PLATFORM=	Linux-*-*

.include "../../mk/bsd.pkg.mk"
