# $NetBSD$

MOZILLA=		thunderbird
COMMENT=		Mozilla mail client

MOZILLA_USE_GTK2=	# yes
MOZILLA_USE_XFT=	YES

.include "../../wip/thunderbird2/Makefile-thunderbird.common"
.include "../../mk/bsd.pkg.mk"
