# $NetBSD$

DISTNAME=	wai-1.4.1
CATEGORIES=	www

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Web Application Interface
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-blaze-builder/buildlink3.mk"
.include "../../wip/hs-conduit/buildlink3.mk"
.include "../../wip/hs-http-types/buildlink3.mk"
.include "../../net/hs-network/buildlink3.mk"
.include "../../devel/hs-text/buildlink3.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../devel/hs-vault/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
