# $NetBSD$
#

DISTNAME=	containers-unicode-symbols-0.3.0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Unicode alternatives for common functions and operators
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-base-unicode-symbols/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
