# $NetBSD$

BUILDLINK_TREE+=	stm

.if !defined(STM_BUILDLINK3_MK)
STM_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.stm?=	build
BUILDLINK_API_DEPENDS.stm+=	stm>=2.1.1.2
BUILDLINK_PKGSRCDIR.stm?=	../../wip/stm
.endif # STM_BUILDLINK3_MK

BUILDLINK_TREE+=	-stm
