# $NetBSD$
#

DISTNAME=	stm-2.1.1.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Modular composable concurrency abstraction

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
