# $NetBSD$
#

DISTNAME=	pep8-0.6.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	http://pypi.python.org/packages/source/p/pep8/

MAINTAINER=	kamel.derouiche@gmail.com
HOMEPAGE=	http://github.com/jcrocholl/pep8
COMMENT=	Python style guide checker

PKG_DESTDIR_SUPPORT=	user-destdir

WRKSRC=		${WRKDIR}/pep8-0.6.1
USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
