# $NetBSD$
#

DISTNAME=	explicit-iomodes-0.5
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	File handles with explicit IOModes
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-base-unicode-symbols/buildlink3.mk"
.include "../../wip/hs-tagged/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
