# $NetBSD$
#

DISTNAME=							rope-0.9.2
PKGREVISION=    					1
CATEGORIES=							devel
MASTER_SITES=						http://downloads.sourceforge.net/project/rope/rope/0.9.2/

MAINTAINER=							helgoman@users.sourceforge.net
HOMEPAGE=							http://rope.sourceforge.net/
COMMENT=							Rope is a python refactoring library
LICENSE=							gnu-gpl-v2

PKG_DESTDIR_SUPPORT=    			user-destdir

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
