# $NetBSD$
#

.include "../xfce4/Makefile.common"

XFCE4_VERSION=	2.1.1

PKGNAME=	xfce4-gtk2-engine-${XFCE4_VERSION}
DISTNAME=	gtk-xfce-engine-${XFCE4_VERSION}
CATEGORIES=	x11
COMMENT=	XFce4 GTK2 themes

.include "../../x11/gtk2/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
