# $NetBSD$
#

.include "../xfce4/Makefile.common"

VERSION=	2.1.1
PKGNAME=	xfce4-gtk2-engine-${VERSION}
DISTNAME=	gtk-xfce-engine-${VERSION}
CATEGORIES=	x11
COMMENT=	XFce4 GTK2 themes

.include "../../x11/gtk2/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
