# $NetBSD$
#

.include "../xfce4/Makefile.common"

PKGNAME=	xfce4-gtk2-engines-${XFCE4_VERSION}
COMMENT=	XFce4 GTK2 themes

WRKSRC=		${WRKDIR}/xfce-devel/gtk-xfce-engine-2

.include "../../x11/gtk2/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
