# $NetBSD$
#

DISTNAME=	arabi
PKGNAME=	tex-${DISTNAME}-1.1
TEXLIVE_REV=	15878

MAINTAINER=	kamelderouiche@yahoo.com
COMMENT=	(La)TeX support for Arabic and Farsi, compliant with Babel

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
