# $NetBSD$
#

DISTNAME=	HCL-1.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	High-level Haskell library for building command line interfaces
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-QuickCheck1/buildlink3.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
