# $NetBSD$

DISTNAME=	pydns-2.3.3
PKGNAME=	${PYPKGPREFIX}-DNS-2.3.3
CATEGORIES=	net python
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=pydns/}

MAINTAINER=	mishka@NetBSD.org
HOMEPAGE=	http://pydns.sourceforge.net/
COMMENT=	Python DNS library

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
