# $NetBSD$

VERSION=	20050510
DISTNAME=	es_ES
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Spanish (Spain) dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
