# $NetBSD$

VERSION=	20050510
DISTNAME=	es_ES
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Spanish (Spain) dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
