# $NetBSD: Makefile,v 1.53 2004/05/25 14:55:34 adam Exp $

.include "Makefile.common"

USE_X11=	yes
COMMENT=	Graphics library for the dynamic creation of images (X11)

.include "../../graphics/xpm/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
