# $NetBSD$

DISTNAME=	picocom-1.4
PKGREVISION=	1
CATEGORIES=	misc

MAINTAINER=	inittab@unixdev.net
MASTER_SITES=   http://efault.net/npat/hacks/picocom/dist/

HOMEPAGE=       http://efault.net/npat/hacks/picocom/
COMMENT=        Serial Console

USE_TOOLS+=             gmake
BUILD_TARGET=		picocom

INSTALLATION_DIRS=      bin ${PKGMANDIR}/man8

.include "../../mk/bsd.pkg.mk"
