# $NetBSD$

DISTNAME=	PyAMF-0.5.1
PKGNAME=	${PYPKGPREFIX}-pyamf-0.5.1
CATEGORIES=	www
MASTER_SITES=	http://pypi.python.org/packages/source/P/PyAMF/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://www.pyamf.org/
COMMENT=	Action Message Format support for Python
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
