# $NetBSD$
#

DISTNAME=	hslogger-1.1.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Logging framework for Haskell
LICENSE=	gnu-lgpl-v2.1

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../net/hs-network/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
