# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-socket-${IO_VERSION}
PKGREVISION=		1
CATEGORIES=		net

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		Socket addon for Io.

ADDON_NAME=		Socket
ADDON_INSTALL_HEADERS=	yes

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
