# $NetBSD$
#

DISTNAME=	haskell-src-exts-1.14.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Manipulating Haskell source
LICENSE=	modified-bsd

BUILD_DEPENDS=	happy:../../wip/happy

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-cpphs/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
