# $NetBSD$
#

DISTNAME=	haskell-src-exts-1.1.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Manipulating Haskell source
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-cpphs/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
