# $NetBSD$

BUILDLINK_TREE+=	viper

.if !defined(PY_VIPER_BUILDLINK3_MK)
PY_VIPER_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.viper+=	${PYPKGPREFIX}-viper>=1.0.0
BUILDLINK_PKGSRCDIR.viper?=	../../wip/py-viper
.endif	# PY_VIPER_BUILDLINK3_MK

BUILDLINK_TREE+=	-viper
