# $NetBSD$

DISTNAME=	groupoids-3.0.1.1
CATEGORIES=	math

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Haskell 98 Groupoids
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-semigroupoids/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
