# $NetBSD$
#

DISTNAME=		time-1.7
CATEGORIES=		time
MASTER_SITES=		${MASTER_SITE_GNU:=time/}

MAINTAINER=		reed@reedmedia.net
HOMEPAGE=		http://www.gnu.org/directory/GNU/time.html
COMMENT=		Report user, system, and real time used by a process

USE_BUILDLINK3=		yes
GNU_CONFIGURE=		yes
INFO_FILES=		time.info

.include "../../mk/bsd.pkg.mk"
