# $NetBSD$
#

DISTNAME=	stringtable-atom-0.0.6.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Memorize Strings as Atoms for fast comparison and sorting
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-syb/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
