# $NetBSD$

BUILDLINK_TREE+=	py26-CherryPy

.if !defined(PY26_CHERRYPY_BUILDLINK3_MK)
PY26_CHERRYPY_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.py26-CherryPy+=	py26-CherryPy>=3.1.2
BUILDLINK_PKGSRCDIR.py26-CherryPy?=	../../wip/py-CherryPy
.endif	# PY26_CHERRYPY_BUILDLINK3_MK

BUILDLINK_TREE+=	-py26-CherryPy
