# $NetBSD$
#

DISTNAME=	ghc-syb-utils-0.2.1.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Scrap Your Boilerplate utilities for the GHC API
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-syb/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
