# $NetBSD$
#

DISTNAME=	pnetC-0.6.0
CATEGORIES=	lang
MASTER_SITES=	http://www.southern-storm.com.au/download/

MAINTAINER=	pancake@phreaker.net
HOMEPAGE=	http://www.dotgnu.org/
COMMENT=	C language binding for DotGNU

USE_GMAKE=	yes
GNU_CONFIGURE=	yes
USE_BUILDLINK2=	yes

.include "../../wip/pnet/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
