# $NetBSD$

.include "../xfce4/Makefile.common"

PKGNAME=	xfce4-mcs-manager-${XFCE4_VERSION}
DISTNAME=	xfce-mcs-manager-${XFCE4_VERSION}
CATEGORIES=	x11
COMMENT=	XFce4 settings manager

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../wip/libxfce4gui/buildlink2.mk"
.include "../../wip/libxfce4mcs/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
