# $NetBSD$
#

DISTNAME=	dataenc-0.13.0.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Data encoding library for Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
