# $NetBSD$
#

DISTNAME=	dataenc-0.14.0.5
CATEGORIES=	converters

MAINTAINER=	pho@cielonegro.org
COMMENT=	Data encoding library for Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
