# $NetBSD$
#

DISTNAME=	dataenc-0.11.1
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.haskell.org/haskellwiki/Library/Data_encoding
COMMENT=	Data encoding library for Haskell

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
