# $NetBSD$
#

DISTNAME=	csv-1.0
PKGNAME=	${PYPKGPREFIX}-csv-1.0
CATEGORIES=	textproc
MASTER_SITES=	http://www.object-craft.com.au/projects/csv/download/

MAINTAINER=	marc@informatik.uni-bremen.de
HOMEPAGE=	http://www.object-craft.com.au/projects/csv/
COMMENT=	CSV reading module for Python

USE_BUILDLINK2=	YES

PYDISTUTILSPKG=	yes
PYBINMODULE=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
