# $NetBSD$

DISTNAME=	multimethods-1.0.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	python
MASTER_SITES=	https://pypi.python.org/packages/source/m/multimethods/

MAINTAINER=	root@zta.lk
HOMEPAGE=	https://github.com/weissjeffm/multimethods
COMMENT=	Multimethods for Python
LICENSE=	

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
