# $NetBSD$
#

DISTNAME=	libdfui-4.1
CATEGORIES=	sysutils
MASTER_SITES=	ftp://packages.stura.uni-rostock.de/bsdinstaller/distfiles/

MAINTAINER=	joerg@NetBSD.org
HOMEPAGE=	http://www.bsdinstaller.com/
COMMENT=	Abstract user interface protocol library

USE_LIBTOOL=	yes

.include "../../wip/libaura/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
