# $NetBSD$
#

DISTNAME=	strict-io-0.2.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Library wrapping standard IO modules to provide strict IO
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
