# $NetBSD$
#

DISTNAME=		libvc-003
CATEGORIES=		mail
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=rolo/}

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://rolo.sourceforge.net/
COMMENT=		VCard library

PKG_DESTDIR_SUPPORT=	none

USE_PKGLOCALEDIR=	yes
USE_LIBTOOL=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
