# $NetBSD$

DISTNAME=	libspf2-1.0.4
CATEGORIES=	mail
MASTER_SITES=	http://www.libspf2.org/spf/

MAINTAINER=	adrianp@NetBSD.org
HOMEPAGE=	http://www.libspf2.org/
COMMENT=	Implementation of the Sender Policy Framework

USE_BUILDLINK3=	YES
GNU_CONFIGURE=	YES
USE_LIBTOOL=	YES

.include "../../mk/bsd.pkg.mk"
