# $NetBSD$

DISTNAME=	wgetpro-0.1.3
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=wgetpro/}
EXTRACT_SUFX=	.tgz

MAINTAINER=	clamiax@gmail.com
HOMEPAGE=	http://wgetpro.sourceforge.net/
COMMENT=	Wget with "PRO" features

PKG_DESTDIR_SUPPORT=	user-destdir
GNU_CONFIGURE=		yes

INSTALLATION_DIRS=	bin ${PKGMANDIR}/man1

.include "../../mk/bsd.pkg.mk"
