# $NetBSD$
#

DISTNAME=	trollop-1.15
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://trollop.rubyforge.org/
COMMENT=	Commandline option parser for Ruby that gets out of your way
LICENSE=	ruby-license

.include "../../misc/rubygems/rubygem.mk"
.include "../../mk/bsd.pkg.mk"
