# $NetBSD$
#

DISTNAME=	test-framework-quickcheck2-0.3.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	QuickCheck2 support for the test-framework package
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-QuickCheck/buildlink3.mk"
.include "../../wip/hs-extensible-exceptions/buildlink3.mk"
.include "../../wip/hs-test-framework/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
