# $NetBSD$
#

DISTNAME=	network-bytestring-0.1.2.1
CATEGORIES=	net

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast, memory-efficient, low-level networking

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-network/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
