# $NetBSD$

DISTNAME=	network-conduit-1.0.0
CATEGORIES=	net

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Stream socket data using conduits
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-conduit/buildlink3.mk"
.include "../../wip/hs-lifted-base/buildlink3.mk"
.include "../../wip/hs-monad-control/buildlink3.mk"
.include "../../wip/hs-network/buildlink3.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
