# $NetBSD$
#

DISTNAME=	Math-Complex-1.59
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=Math/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://search.cpan.org/~zefram/Math-Complex-1.59/lib/Math/Complex.pm
COMMENT=	Complex numbers and associated mathematical functions
LICENSE=	${PERL5_LICENSE}

USE_LANGUAGES=		# none

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
