# $NetBSD$
#

DISTNAME=	punycode-0.0.1.0
CATEGORIES=	www

MAINTAINER=	pho@cielonegro.org
COMMENT=	Punycode encoder
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../textproc/hs-parsec/buildlink3.mk"
.include "../../devel/hs-text/buildlink3.mk"
.include "../../wip/hs-text-icu/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
