# $NetBSD$
#

DISTNAME=	QuickCheck-1.2.0.0
PKGNAME=	hs-QuichCheck1-1.2.0.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.math.chalmers.se/~rjmh/QuickCheck/
COMMENT=	Automatic testing of Haskell programs (Old version)

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
