# $NetBSD$
#

CATEGORIES=             math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/hwde.html}
COMMENT=		Models and tests for departure from Hardy-Weinberg equilibrium

R_PKGNAME=		hwde
R_PKGVER=               0.3

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
