#
# $NetBSD$
#
# Common Makefile for packages that are installed using scsh-install-lib
#

NO_BUILD=		yes

do-install:
	cd ${WRKSRC}; \
	scsh-install-pkg --bindir ${PREFIX}/bin	\
			 --prefix=${PREFIX}/lib/scsh \
			 --layout fhs \
			 --verbose
