# $NetBSD$
#

DISTNAME=	actionmessenger-0.2.0
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	chat
MASTER_SITES=	http://cloud.github.com/downloads/trejkaz/actionmessenger/
EXTRACT_SUFX=	.gem

MAINTAINER=	yuripoloni@gmail.com
HOMEPAGE=	http://trypticon.org/software/actionmessenger/
COMMENT=	Ruby convenience framework for instant messaging
LICENSE=	mit

PKG_DESTDIR_SUPPORT=	user-destdir

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
