# $NetBSD$
#

DISTNAME=		gate-2.06
CATEGORIES=		editors
MASTER_SITES=		http://www.unixpapa.com/software/

MAINTAINER=		hugor@users.sourceforge.net
HOMEPAGE=		http://www.unixpapa.com/gate.html
COMMENT=		Lightweight text editor

GNU_CONFIGURE=		yes
BUILD_TARGET=		# empty

.include	"../../mk/bsd.pkg.mk"
