# $NetBSD: Makefile,v 1.6 2008/09/18 12:42:47 taca Exp $

DISTNAME=	term-ansicolor-1.0.4
PKGNAME=	${RUBY_PKGPREFIX}-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	filip@joyent.com
HOMEPAGE=	http://term-ansicolor.rubyforge.org/
COMMENT=	Small Ruby library that colors strings using ANSI escape sequences
LICENSE=	gnu-gpl-v2

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
