# $NetBSD$
#

DISTNAME=		egenix-mx-base-2.0.4
PKGNAME=                ${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		wip
MASTER_SITES=		http://www.egenix.com/files/python/

MAINTAINER=		adam@monkeybyte.org
HOMEPAGE=		http://www.egenix.com/files/python/
COMMENT=		mx Extensions for Python

PYDISTUTILSPKG=
PYTHON_VERSION_REQD=    22pth
USE_BUILDLINK2= yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
