# $NetBSD$
#

DISTNAME=		textile-2
PKGNAME=		${PYPKGPREFIX}-textile-2.0
CATEGORIES=		textproc
MASTER_SITES=		http://dealmeida.net/code/

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://dealmeida.net/projects/textile/
COMMENT=		XHTML generator using a simple markup

PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
