# $NetBSD$
#

DISTNAME=	partonevolution-1.1.2
CATEGORIES=	science
MASTER_SITES=	http://wwwthep.physik.uni-mainz.de/~stefanw/download/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://wwwthep.physik.uni-mainz.de/~stefanw/partonevolution
COMMENT=	Fast Evolution of Parton Distributions
LICENSE=	gnu-gpl-v2

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++ fortran77

.include "../../mk/bsd.pkg.mk"
