# $NetBSD$
#

DISTNAME=	MonadCatchIO-transformers-0.3.1.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Monad-transformer compatible version of the Control.Exception module
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-extensible-exceptions/buildlink3.mk"
.include "../../wip/hs-monads-tf/buildlink3.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
