# $NetBSD$
#

DISTNAME=	MonadCatchIO-transformers-0.2.2.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Monad-transformer compatible version of the Control.Exception module
LICENSE=	public-domain

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
