# $NetBSD$
#

DISTNAME=	busybox-0.60.5
CATEGORIES=	sysutils
MASTER_SITES=	http://www.busybox.net/downloads/

MAINTAINER=	pancake@phreaker.net
HOMEPAGE=	http://www.busybox.net/
COMMENT=	The Swiss Army Knife of Embedded Linux

USE_TOOLS+=	gmake

ONLY_FOR_PLATFORM=	Linux-*-*

.include "../../mk/bsd.pkg.mk"
