# $NetBSD$
#

DISTNAME=		autossh-1.4b
CATEGORIES=		security
MASTER_SITES=		http://www.harding.motd.ca/autossh/
EXTRACT_SUFX=		.tgz

MAINTAINER=		mj@mjturner.net
HOMEPAGE=		http://www.harding.motd.ca/autossh/
COMMENT=		Monitor and automatically restart SSH sessions and tunnels

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=		yes

.include "../../mk/bsd.prefs.mk"
.include "../../mk/bsd.pkg.mk"
