# $NetBSD$
#

DISTNAME=		drow-0.2.22
CATEGORIES=		wip
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=drow/}

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://drow.sourceforge.net/
COMMENT=		low-level ELF file analyzer

GNU_CONFIGURE=		YES

USE_BUILDLINK2=		yes
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
