# $NetBSD$
#

DISTNAME=		drow-0.2.22
CATEGORIES=		sysutils
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=drow/}

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://drow.sourceforge.net/
COMMENT=		Low-level ELF file analyzer
LICENSE=		gnu-gpl-v2

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=		YES

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
