# $NetBSD$
#

DISTNAME=	rdflib-2.4.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc python
MASTER_SITES=	http://rdflib.net/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://rdflib.net/
COMMENT=	RDFLib is a Python library for working with RDF
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
