# $NetBSD$
#

DISTNAME=	rthread-0.1.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	http://www.cs.tut.fi/~ask/rthread/

MAINTAINER=	kamel.derouiche@gmail.com
HOMEPAGE=	http://www.cs.tut.fi/~ask/rthread/
COMMENT=	Distributed computing with remote threads in Python
LICENSE=	gnu-lgpl-v2

PKG_DESTDIR_SUPPORT=	user-destdir

USE_LANGUAGES=	# none
PYDISTUTILSPKG= yes


.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
