# $NetBSD$
#

CATEGORIES=             math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/httpRequest.html}
COMMENT=		Implements the GET, POST and multipart POST request

R_PKGNAME=		httpRequest
R_PKGVER=               0.0.5

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
