# $NetBSD$
#

DISTNAME=	bindings-librrd-0.1
PKGREVISION=	1
CATEGORIES=	databases

MAINTAINER=	pho@cielonegro.org
COMMENT=	Low level Haskell bindings to RRDtool
LICENSE=	public-domain

.include "../../wip/mk/haskell.mk"
.include "../../databases/rrdtool/buildlink3.mk"
.include "../../wip/hs-bindings-DSL/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
