# $NetBSD$
#

.include "../../wip/mecab/Makefile.common"

DISTNAME=	mecab-ipadic-2.7.0-20060707
PKGNAME=	mecab-ipadic-2.7.0.20060707

COMMENT=	Japanese Morphological Dictionary for MeCab

GNU_CONFIGURE=	yes

.include "../../wip/mecab-base/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
