# $NetBSD$
#

DISTNAME=	util-macros-1.1.5
CATEGORIES=	devel
MASTER_SITES=	http://xorg.freedesktop.org/releases/individual/util/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	blair.sadewitz@gmail.com
HOMEPAGE=	http://xorg.freedesktop.org/
COMMENT=	GNU autoconf macros for the modular X.org source tree

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
