# $NetBSD$
#

DISTNAME=	vault-0.2.0.4
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	https://github.com/HeinrichApfelmus/vault
COMMENT=	Persistent store for values of arbitrary types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
