# $NetBSD$
#

DISTNAME=	vault-0.3.0.2
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	https://github.com/HeinrichApfelmus/vault
COMMENT=	Persistent store for values of arbitrary types
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-hashable/buildlink3.mk"
.include "../../wip/hs-unordered-containers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
