# $NetBSD$
#

DISTNAME=	contravariant-0.4.4
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Contravariant functors
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-tagged/buildlink3.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../wip/hs-transformers-compat/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
