# $NetBSD$

DISTNAME=	contravariant-0.5.2
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Contravariant functors
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../devel/hs-tagged/buildlink3.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../devel/hs-transformers-compat/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
