# $NetBSD$
#

DISTNAME=	magic-1.0.7
PKGREVISION=	1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell interface to the C libmagic library
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../sysutils/file/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
