# $NetBSD$
#

DISTNAME=	magic-1.0.7
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell interface to the C libmagic library

.include "../../sysutils/file/buildlink3.mk"
.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
