# $NetBSD$

VERSION=	20050307
DISTNAME=	fo_FO
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Faroese dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
