# $NetBSD: Makefile.version,v 1.1.1.1 2008/10/25 00:32:23 bjs Exp $
#
# CVS repo:	:pserver:anonymous@bdwgc.cvs.sourceforge.net:/cvsroot/bdwgc
# CVS module:	bdwgc

#LIBATOMIC_OPS_VERSION=	7.2alpha7
LIBATOMIC_OPS_SNAPDATE=	20110807
