# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EMBRYO_BUILDLINK3_MK:=	${EMBRYO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	embryo
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nembryo}
BUILDLINK_PACKAGES+=	embryo
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}embryo

.if ${EMBRYO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.embryo+=	embryo>=0.9.1.037
BUILDLINK_PKGSRCDIR.embryo?=	../../wip/embryo
.endif	# EMBRYO_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
