# $NetBSD$
#

DISTNAME=		embryo-0.9.0
CATEGORIES=		wip lang
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=enlightenment/}

MAINTAINER=		Peter.Bex@student.kun.nl
HOMEPAGE=		http://www.enlightenment.org/pages/embryo.html
COMMENT=		Tiny scripting language for Enlightenment

GNU_CONFIGURE=		YES
USE_BUILDLINK3=		YES
USE_LIBTOOL=		YES

.include "../../devel/libtool/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
