# $NetBSD$
#

DISTNAME=	entropy-0.2.2.2
CATEGORIES=	security

MAINTAINER=	pho@cielonegro.org
COMMENT=	Platform independent entropy source
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
