# $NetBSD$
#

DISTNAME=		xdiskusage-1.48
CATEGORIES=		sysutils
MASTER_SITES=		http://xdiskusage.sourceforge.net/
EXTRACT_SUFX=		.tgz

MAINTAINER=		ccatrian@eml.cc
HOMEPAGE=		http://xdiskusage.sourceforge.net/
COMMENT=		Graphical space disk viewer

USE_LANGUAGES=		c c++
USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../x11/fltk/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
