# $NetBSD$

MODNAME=		mysql4

.include "../../databases/php4-mysql/Makefile.common"
.include "../../www/php4/Makefile.module"
.include "../../wip/mysql4-client/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
