# $NetBSD$

.include "../../wip/xfce4/Makefile.common"

DISTNAME=	xfce4-appfinder-${XFCE4_VERSION}
CATEGORIES=	sysutils
COMMENT=	Xfce application finder

.include "../../wip/libxfce4gui/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
