# $NetBSD: Makefile,v 1.8 2014/06/01 17:04:15 tsutsui Exp $

DISTNAME=	kakasi-1.0.2
CATEGORIES=	textproc

MAINTAINER=	ishit@users.sourceforge.net
HOMEPAGE=	https://github.com/eitoball/kakasi-ruby/
COMMENT=	Ruby binding for KAKASI implemented with Fiddle/DL/FFI
LICENSE=	2-clause-bsd OR ruby-license

RUBY_VERSION_SUPPORTED=	200 193 21

.include "../../textproc/kakasi/buildlink3.mk"
.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
