# $NetBSD$

.include "../../wip/xfce4/Makefile.common"

DISTNAME=	xfce4-icon-theme-${XFCE4_VERSION}
CATEGORIES=	graphics
COMMENT=	Xfce icon themes

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
