# $NetBSD$
#

DISTNAME=	rci-20050720
CATEGORIES=	wip
MASTER_SITES=	http://wmi.modprobe.de/snaps/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	lems@gmx.net
HOMEPAGE=	http://wmi.modprobe.de/
COMMENT=	Shell based on UNIX rc version 1.4 and 1.7.x

.include "../../mk/bsd.pkg.mk"
