# $NetBSD$

DISTNAME=	categories-1.0.6
CATEGORIES=	math

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Categories
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-void/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
