# $NetBSD$

DISTNAME=	categories-1.0.6
CATEGORIES=	math

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Categories
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-void/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
