# $NetBSD$
#

CATEGORIES=             math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/CGIwithR.html}
COMMENT=		Facilities for the use of R to write CGI scripts

R_PKGNAME=              CGIwithR
R_PKGVER=               0.61

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
