# $NetBSD$
#

DISTNAME=	uconv-0.0.3
PKGREVISION=	2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell interface to ICU's uconv library

.include "../../wip/mk/haskell.mk"
.include "../../textproc/icu/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
