# $NetBSD$
DISTNAME=	gkrellm-2.1.8a
CATEGORIES=	sysutils
MASTER_SITES=	http://web.wt.net/~billw/gkrellm/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	cube@cubidou.net
HOMEPAGE=	http://gkrellm.net/

ONLY_FOR_PLATFORM=	NetBSD-*

OSVERSION_SPECIFIC=	YES
USE_GMAKE=		YES
USE_PKGLOCALEDIR=	YES

MAKE_ENV+=		LOCALEDIR=${PREFIX}/${PKGLOCALEDIR}/locale \
			enable_nls=1
