# $NetBSD$
#

DISTNAME=	scew-0.3.1
CATEGORIES=	devel
MASTER_SITES=	http://savannah.nongnu.org/download/scew/scew.pkg/0.3.1/

MAINTAINER=	thorbjorn@jemander.net
HOMEPAGE=	http://www.nongnu.org/scew/
COMMENT=	Light-weight DOM-like object model API for Expat

USE_BUILDLINK2=	YES
GNU_CONFIGURE=	YES

.include "../../textproc/expat/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
