# $NetBSD$

VERSION=	20031231
DISTNAME=	lt_LT
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Lithuanian dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
