# $NetBSD$
#

PEAR_CHANNEL=		pearhub.org
PEAR_CHANNEL_ALIAS=	pearhub
PEAR_CHANNEL_VERSION=	2013.09.24

MAINTAINER=		noud4@home.nl

.include "../../wip/mk/pear-channel.mk"
.include "../../mk/bsd.pkg.mk"
