# $NetBSD$
#

DISTNAME=	generic-deriving-1.5.0
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Generic programming library for generalised deriving
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
