# $NetBSD$
#

DISTNAME=	generic-deriving-1.6.2
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Generic programming library for generalised deriving
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
