# $NetBSD$

DISTNAME=	tf-random-0.5
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	High-quality splittable pseudorandom number generator
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-primitive/buildlink3.mk"
.include "../../devel/hs-random/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
