# $NetBSD$

VERSION=	20050112
DISTNAME=	he_IL
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Hebrew dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
