# $NetBSD$

VERSION=	20050112
DISTNAME=	he_IL
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Hebrew dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
