# $NetBSD$

.if !defined(QUANTA_BUILDLINK2_MK)
QUANTA_BUILDLINK2_MK=		#defined

BUILDLINK_PACKAGES+=		QUANTA
BUILDLINK_PKGBASE.QUANTA=	QUANTA
BUILDLINK_DEPENDS.QUANTA?=	QUANTA>=0.3
BUILDLINK_PKGSRCDIR.QUANTA?=	../../wip/QUANTA

EVAL_PREFIX+=			BUILDLINK_PREFIX.QUANTA=QUANTA
BUILDLINK_PREFIX.QUANTA_DEFAULT=${LOCALBASE}
BUILDLINK_FILES.QUANTA+=	include/QUANTA/*.hxx
BUILDLINK_FILES.QUANTA+=	lib/libquanta_32.*

BUILDLINK_TARGETS+=		QUANTA-buildlink

QUANTA-buildlink: _BUILDLINK_USE
.endif # QUANTA_BUILDLINK2_MK
