# $NetBSD$
#

DISTNAME=	bindings-audiofile-0.1.0.1
CATEGORIES=	audio

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell low-level bindings to libaudiofile
LICENSE=	modified-bsd

.include "../../audio/libaudiofile/buildlink3.mk"
.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-bindings-DSL/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
