# $NetBSD$
#

DISTNAME=	onig-5.9.1
PKGNAME=	${DISTNAME:S/onig/oniguruma/}
CATEGORIES=	devel
MASTER_SITES=	http://www.geocities.jp/kosako3/oniguruma/archive/

PKG_DESTDIR_SUPPORT=	user-destdir

MAINTAINER=	adam.hoka@gmail.com
HOMEPAGE=	http://www.geocities.jp/kosako3/oniguruma/
COMMENT=	Regular expressions library

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes

.include "../../mk/bsd.pkg.mk"
