# $NetBSD$
#

DISTNAME=	xml-1.3.13
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Simple XML library
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
