# $NetBSD$
#

DISTNAME=	rosezipper-0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Generic zipper implementation for Data.Tree
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
