# $NetBSD$

VERSION=	20090125
DISTNAME=	uk_UA
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Ukraine dictionary for hunspell

.include "../../textproc/hunspell/Makefile.common"

.include "../../mk/bsd.pkg.mk"
