# $NetBSD$
#

DISTNAME=	muttprint-0.72d
CATEGORIES=	print
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=muttprint/}

MAINTAINER=	mayuresh@acm.org
HOMEPAGE=	http://muttprint.sourceforge.net/
COMMENT=	Utility to pretty print email
LICENSE=	gnu-gpl-v1

DEPENDS+=	p5-Text-Iconv>=1.7:../../converters/p5-Text-Iconv

.include "../../mk/bsd.pkg.mk"
