# $NetBSD$
#

DISTNAME=	tfp-0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Type-level programming library using type families
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
