# $NetBSD$

DISTNAME=	I2util-1.2
CATEGORIES=	wip
MASTER_SITES=	http://software.internet2.edu/sources/I2util/

MAINTAINER=	mbowie@rocketspace.com
HOMEPAGE=	https://github.com/fintler/ndt/tree/master/I2util
COMMENT=	I2 Utility library
#LICENSE=	# TODO

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
