# $NetBSD$
DISTNAME=	libexecinfo-1.1
CATEGORIES=	devel
MASTER_SITES=	ftp://ftp.freebsd.org/pub/FreeBSD/distfiles

MAINTAINER=	ober@netbsd.org
HOMEPAGE=       http://www.freebsdsoftware.org/devel/libexecinfo.html
COMMENT=	BSD Licensed clone of backtrace facility found in GNU libc.
EXTRACT_SUFX=	.tar.bz2


.include "../../mk/bsd.prefs.mk"

USE_LANGUAGES+=	c
DESTDIR=${LOCALBASE}

.include "../../mk/bsd.pkg.mk"

