# $NetBSD$

DISTNAME=	selenium-2.41.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://pypi.python.org/packages/source/s/selenium/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	 http://code.google.com/p/selenium/
COMMENT=	Python bindings for Selenium
LICENSE=	apache-2.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
