# $NetBSD$
#

DISTNAME=	freecell-1.0
CATEGORIES=	games
MASTER_SITES=	http://www.linusakesson.net/files/

MAINTAINER=	esg@sdf.lonestar.org
HOMEPAGE=	http://www.linusakesson.net/software/freecell.php
COMMENT=	Console version of the solitaire game Freecell

LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes

.include "../../mk/curses.buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
