# $NetBSD$
#

DISTNAME=	haskell-src-1.0.1.5
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Manipulating Haskell source code
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/happy/buildlink3.mk"
.include "../../devel/hs-syb/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
