# $NetBSD$

DISTNAME=	parameters-0.2.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	biology
MASTER_SITES=	https://pypi.python.org/packages/source/p/parameters/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://neuralensemble.org/parameters
COMMENT=	Hierarchical parameter sets for modelling and simulation
LICENSE=	gnu-gpl-v2

USE_LANGUAGES=	# none

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
