# $NetBSD$

TEXLIVE_VERSION=	2007
# Update PKG_REVISION when this is updated
TEXLIVE_GENERATION=	g0

# This can most likely just be added to the default
# list of acceptable licenses since texlive includes
# only libre software
LICENSE=		texlive-license
LICENSE_FILE=		LICENSE
