# $NetBSD$

BUILDLINK_TREE+=	xqilla

.if !defined(XQILLA_BUILDLINK3_MK)
XQILLA_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.xqilla+=	xqilla>=2.2.4
BUILDLINK_PKGSRCDIR.xqilla?=	../../wip/xqilla
.endif	# XQILLA_BUILDLINK3_MK

BUILDLINK_TREE+=	-xqilla
