# $NetBSD$
#

DISTNAME=	irc-0.4.4.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell library for parsing IRC messages

.include "../../wip/mk/haskell.mk"
.include "../../textproc/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
