# $NetBSD$
#

DISTNAME=	irc-0.4.3
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_HASKELL_HACKAGE:=irc/0.4.3/}

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://hackage.haskell.org/cgi-bin/hackage-scripts/package/irc
COMMENT=	Haskell library for parsing IRC messages

.include "../../wip/mk/haskell.mk" # This should be "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
