# $NetBSD$
#

DISTNAME=	pointfree-1.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://haskell.org/haskellwiki/Pointfree
COMMENT=	Convert Haskell expressions to pointfree form

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
