# $NetBSD$
#

DISTNAME=	matchbox-nest-0.3
CATEGORIES=	x11
MASTER_SITES=	http://matchbox.handhelds.org/sources/matchbox-nest/0.3/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://matchbox.handhelds.org/
COMMENT=	Matchbox Xnest wrapper

USE_BUILDLINK3=		yes
USE_X11=		yes
GNU_CONFIGURE=		yes

.include "../../wip/libmatchbox/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
