# $NetBSD$
#

DISTNAME=	lbt-1.2.2
CATEGORIES=	math
MASTER_SITES=	http://www.tcs.hut.fi/Software/maria/src/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://www.tcs.hut.fi/Software/maria/tools/lbt/
COMMENT=	Converts from LTL formulas to Büchi automata
LICENSE=	gnu-gpl-v2

USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
