# $NetBSD$
#

DISTNAME=       ripmime-1.3.0.4
CATEGORIES=	mail
MASTER_SITES=	http://www.pldaniels.com/ripmime/

MAINTAINER=	reed@reedmedia.net
HOMEPAGE=	http://www.pldaniels.com/ripmime/
COMMENT=	Extract the attached files out of a MIME encoded email package

.include "../../mk/bsd.pkg.mk"
