# $NetBSD$

BUILDLINK_TREE+=	ETL

.if !defined(ETL_BUILDLINK3_MK)
ETL_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.ETL?=	build
BUILDLINK_API_DEPENDS.ETL+=	ETL>=0.04.11
BUILDLINK_PKGSRCDIR.ETL?=	../../wip/ETL
.endif # ETL_BUILDLINK3_MK

BUILDLINK_TREE+=	-ETL
