# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ETL_BUILDLINK3_MK:=	${ETL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	ETL
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NETL}
BUILDLINK_PACKAGES+=	ETL
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ETL

.if ${ETL_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.ETL?=	build
BUILDLINK_API_DEPENDS.ETL+=	ETL>=0.04.11
BUILDLINK_PKGSRCDIR.ETL?=	../../wip/ETL
.endif	# ETL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
