# $NetBSD$

DISTNAME=	XML_Parser-1.3.2
CATEGORIES+=	textproc

MAINTAINER=	wenheping@gmail.com
COMMENT=	XML parsing class based on PHP's bundled expat
LICENSE=	original-bsd

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
