# $NetBSD$

DISTNAME=	pysphere-0.1.8
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	sysutils
MASTER_SITES=	http://pysphere.googlecode.com/files/
EXTRACT_SUFX=	.zip

MAINTAINER=	ahp-nils@users.sourceforge.net
HOMEPAGE=	http://pysphere.googlecode.com/
COMMENT=	Python API for interacting with the vSphere Web Services SDK
LICENSE=	modified-bsd

PYTHON_VERSIONS_ACCEPTED=	27

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
