# $NetBSD$

.include "../../wip/xfce4/Makefile.common"

XFCE4_VERSION=	0.3.9.2beta2

DISTNAME=	xarchiver-${XFCE4_VERSION}
PKGNAME=	xfce4-xarchiver-${XFCE4_VERSION}
CATEGORIES=	sysutils
COMMENT=	Xfce archiver handler

.include "../../wip/libxfce4gui/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
