# $NetBSD$

VERSION=	20060117
DISTNAME=	af_ZA
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Afrikaans dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
