# $NetBSD$

BUILDLINK_TREE+=	Rgraph

.if !defined(RGRAPH_BUILDLINK3_MK)
RGRAPH_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.Rgraph+=	R-graph>=1.34.0
BUILDLINK_ABI_DEPENDS.Rgraph+=	R-graph>=1.34.0
BUILDLINK_PKGSRCDIR.Rgraph?=	../../wip/R-graph
.endif # RGRAPH_BUILDLINK3_MK

BUILDLINK_TREE+=	-Rgraph
