# $NetBSD$

VERSION=	20040406
DISTNAME=	ru_RU
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Russian dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
