# $NetBSD$

DISTNAME=	validictory-1.0.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc
MASTER_SITES=	https://pypi.python.org/packages/source/v/validictory/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://github.com/sunlightlabs/validictory
COMMENT=	General purpose python data validator
LICENSE=	mit

WRKSRC=		${WRKDIR}/validictory-1.0.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
