# $NetBSD$
#

PKGREVISION=	1
CATEGORIES=	net
MAINTAINER=	ryoon@NetBSD.org
HOMEPAGE=	http://www.rasterbar.com/products/libtorrent/index.html
COMMENT=	The rasterbar libtorrent is a feature complete C++ bittorrent library

PKGCONFIG_OVERRIDE=	libtorrent-rasterbar.pc.in

.include "../../wip/libtorrent-rasterbar/Makefile.common"
