# $NetBSD$

.  include "../../mk/bsd.fast.prefs.mk"

CFLAGS+=		-D__GLX_ALIGN64

CFLAGS.NetBSD+=		-D_NETBSD_SOURCE
CFLAGS.NetBSD+=		-DUSE_NATIVE_LIBM_FUNCS
CFLAGS.FreeBSD+=	-DUSE_NATIVE_LIBM_FUNCS
CFLAGS.DragonFly+=	-DUSE_NATIVE_LIBM_FUNCS
