# $NetBSD$

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
NETCLASSES_BUILDLINK3_MK:=	${NETCLASSES_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	netclasses
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nnetclasses}
BUILDLINK_PACKAGES+=	netclasses
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}netclasses

.if ${NETCLASSES_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.netclasses+=	netclasses>=1.06
BUILDLINK_PKGSRCDIR.netclasses?=	../../wip/netclasses
.endif	# NETCLASSES_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
