# $Id: Makefile,v 1.1 2004/03/09 13:12:33 mpasternak Exp $
# $NetBSD: Makefile,v 1.53 2003/12/08 14:41:39 wiz Exp $
#

.include "Makefile.common"

CONFIGURE_ARGS+=	--disable-esd

.include "../../mk/bsd.pkg.mk"
