# $NetBSD$

DISTNAME=		toppler-1.0.2
CATEGORIES=		games
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=toppler/}

MAINTAINER=		soren@blef.org
HOMEPAGE=		http://topple.sf.net/
COMMENT=		Tower climbing game

USE_BUILDLINK2=		yes
GNU_CONFIGURE=		yes

.include "../../audio/SDL_mixer/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
