# $NetBSD$
#

DISTNAME=	axe-0.2.0
CATEGORIES=	emulators cross
MASTER_SITES=	http://www.hardcoders.org/axe/

MAINTAINER=	virtus@wanadoo.nl
HOMEPAGE=	http://www.hardcoders.org/axe/
COMMENT=	Manipulate contents of Atari 8bit disk image files (.ATR, .XFD)

PKG_DESTDIR_SUPPORT=	none

NO_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
