# $NetBSD$
#

DISTNAME=	axe-0.2.0
CATEGORIES=	emulators cross
MASTER_SITES=	http://www.hardcoders.org/axe/

MAINTAINER=	packages@netbsd.org
HOMEPAGE=	http://www.hardcoders.org/axe/
COMMENT=	Manipulate contents of Atari 8bit disk image files (.ATR, .XFD)

NO_CONFIGURE=  YES

USE_BUILDLINK2=	YES

.include "../../mk/bsd.pkg.mk"
