# $NetBSD$

BUILDLINK_TREE+=	remctl

.if !defined(REMCTL_BUILDLINK3_MK)
REMCTL_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.remctl+=	remctl>=2.13
BUILDLINK_PKGSRCDIR.remctl?=	../../wip/remctl
.endif # REMCTL_BUILDLINK3_MK

BUILDLINK_TREE+=	-remctl
