# $NetBSD$
#

DISTNAME=	storable-record-0.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Elegant definition of Storable instances for records
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../wip/hs-utility-ht/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
