# $NetBSD$
#

DISTNAME=	regex-compat-0.95.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Replaces/Enhances Haskell Text.Regex
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../textproc/hs-regex-base/buildlink3.mk"
.include "../../textproc/hs-regex-posix/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
