# $NetBSD$
#

DISTNAME=	zoem-10-265
PKGNAME=	${DISTNAME:S/10-/10./}
CATEGORIES=	textproc
MASTER_SITES=	http://www.micans.org/zoem/src/

MAINTAINER=	cheusov@tut.by
HOMEPAGE=	http://www.micans.org/zoem/
COMMENT=	Interpretive macro/programming language

LICENSE=	gnu-gpl-v3

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
