# $NetBSD$
#

DISTNAME=	collections-base-instances-1.0.0.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Useful standard collections types and related functions
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-collections-api/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
