# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-sha1-${IO_VERSION}
CATEGORIES=		devel

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		SHA1 addon for Io

ADDON_NAME=		SHA1

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
