# $NetBSD$
#

DISTNAME=	logilab-doctools-0.2.5
CATEGORIES=	category
MASTER_SITES=	http://ftp.logilab.org/pub/doctools/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	http://ftp.logilab.org/pub/doctools/
COMMENT=	SHORT_DESCRIPTION_OF_THE_PACKAGE
LICENSE=	LICENSE

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
