# $NetBSD$
#

DISTNAME=	ansi-wl-pprint-0.6.7.1
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	The Wadler/Leijen Pretty Printer with colour support
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-ansi-terminal/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
