# $NetBSD$
#

DISTNAME=		chora-1.2
CATEGORIES=		devel
MASTER_SITES=		ftp://ftp.horde.org/pub/chora/

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://www.horde.org/chora/
COMMENT=		Another CVS-via-web system

DEPENDS+=		horde>=2.2.4:../../www/horde

.include "../../mk/bsd.pkg.mk"
