# $NetBSD$

DISTNAME=	rpaths-0.8
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	https://pypi.python.org/packages/source/r/rpaths/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://github.com/remram44/rpaths
COMMENT=	Path manipulation library
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
