# $NetBSD$

BUILDLINK_TREE+=	libvips

.if !defined(LIBVIPS_BUILDLINK3_MK)
LIBVIPS_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.libvips+=	libvips>=8.2.2
BUILDLINK_PKGSRCDIR.libvips?=	../../wip/libvips

.endif	# LIBVIPS_BUILDLINK3_MK

BUILDLINK_TREE+=	-libvips
