# $NetBSD$
#

CATEGORIES=             math
MASTER_SITES=           ${MASTER_SITE_R_CRAN:=contrib/}

MAINTAINER=             mchittur@cs.nmsu.edu
HOMEPAGE=               ${MASTER_SITE_R_CRAN:=contrib/Descriptions/statmod.html}
COMMENT=		Miscellaneous biostatistical modeling functions

R_PKGNAME=		statmod
R_PKGVER=               1.0.6

.include "../../math/R/Makefile.extension"
.include "../../mk/bsd.pkg.mk"
