# $NetBSD$
#

DISTNAME=	utility-ht-0.0.5.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Various small helper functions
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
