# $NetBSD$
#

DISTNAME=	chalkboard-0.2
CATEGORIES=	graphics

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://ittc.ku.edu/~andygill/chalkboard.php
COMMENT=	Combinators for building and processing 2D images
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
