# $NetBSD$

DISTNAME=	temporary-1.2.0.1
CATEGORIES=	sysutils

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Portable temporary file and directory support
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-exceptions/buildlink3.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
