# $NetBSD$

DISTNAME=	temporary-1.1.2.4
CATEGORIES=	sysutils

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Portable temporary file and directory support
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
