# $NetBSD$
#

DISTNAME=	regex-base-0.93.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Replaces/Enhances Haskell Text.Regex

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
