# $NetBSD$
#

DISTNAME=	regex-base-0.93.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://sourceforge.net/projects/lazy-regex
COMMENT=	Replaces/Enhances Haskell Text.Regex

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
