# $NetBSD$
#

DISTNAME=	rosezipper-0.1
PKGNAME=	hs-rosezipper1-0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Generic zipper implementation for Data.Tree (Old version)
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
