# $NetBSD$
#

DISTNAME=	html-1.0.1.2
PKGNAME=	hs-${DISTNAME}
PKGREVISION=	2
CATEGORIES=	www

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell HTML combinator library

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
