# $NetBSD$
#

ENGINE=		posix
ENGINE_DIR=	posix

.include "../../wip/lua-lrexlib/Makefile.common"

PKGREVISION=	1
COMMENT=	POSIX regexp library for Lua (lrexlib project)
MAINTAINER=	cheusov@tut.by

DESCR_SRC+=	${.CURDIR}/DESCR

.include "../../lang/lua/module.mk"
.include "../../mk/bsd.pkg.mk"
