# $NetBSD$
#

.include "../../wip/lua-lrexlib/Makefile.common"

COMMENT=	POSIX regexp library for Lua (lrexlib project)

ENGINE=		posix

DESCR_SRC+=	DESCR

.include "../../lang/lua/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
