# $NetBSD$
#

ENGINE=		posix

.include "../../wip/lua-lrexlib/Makefile.common"

COMMENT=	POSIX regexp library for Lua (lrexlib project)

DESCR_SRC+=	${.CURDIR}/DESCR

.include "../../lang/lua/module.mk"
.include "../../mk/bsd.pkg.mk"
