# $NetBSD$
#

DISTNAME=	FileManip-0.3.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell library for working with files and directories
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
