# $NetBSD$
#

DISTNAME=	filemanip-0.3.5.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Expressive file and directory manipulation for Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../wip/hs-unix-compat/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
