# $NetBSD$

.include "../../wip/io/version.mk"

PKGNAME=		io-editline-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		devel

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		EditLine addon for Io.

ADDON_NAME=		EditLine

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
