# $NetBSD$
#

PKGNAME=	poco-${POCO_VERSION}
CATEGORIES=	devel

COMMENT=	POCO C++ libraries

.include "../../mk/bsd.prefs.mk"

.include "../../wip/poco/Makefile.common"

.include "../../security/openssl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
