# $NetBSD$

DISTNAME=	bifunctors-4.1.1.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Bifunctors
LICENSE=	2-clause-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-semigroupoids/buildlink3.mk"
.include "../../math/hs-semigroups/buildlink3.mk"
.include "../../devel/hs-tagged/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
