#!/bin/sh
# $NetBSD: $
#
# start script for argouml

CLASSPATH=$CLASSPATH:@PREFIX@/lib/java/log4j-1.2.8.jar:@PREFIX@/lib/java/xerces.jar
for f in antlrall argouml gef i18n nsuml ocl-argo
do
    CLASSPATH=$CLASSPATH:@PREFIX@/lib/java/${f}.jar
done
export CLASSPATH

java -jar @PREFIX@/lib/java/argouml.jar
