# $NetBSD$
#

DISTNAME=	nmzmail-1.1
PKGREVISION=	1
CATEGORIES=	mail
MASTER_SITES=	http://www.ecademix.com/JohannesHofmann/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.ecademix.com/JohannesHofmann/nmzmail.html
COMMENT=	Fast mail searching for mutt

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=		yes

.include "../../devel/readline/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
