# $NetBSD$
#

DISTNAME=	nmzmail-1.0
CATEGORIES=	mail
MASTER_SITES=	http://www.ecademix.com/JohannesHofmann/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.ecademix.com/JohannesHofmann/nmzmail.html
COMMENT=	Fast mail searching for mutt

GNU_CONFIGURE=		yes
PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../devel/readline/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
