# $NetBSD$
#

DISTNAME=	dirb18
PKGNAME=	dirb-1.8
CATEGORIES=	wip security
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=dirb/}

MAINTAINER=	pancake@phreaker.net
HOMEPAGE=	http://dirb.sourceforge.net/
COMMENT=	Web Content Scanner

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../www/curl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
