# $NetBSD$
#

.include "${.CURDIR}/../../wip/ezm3/ezm3.mk"

ONLY_FOR_PLATFORM=      NetBSD-*-i386

BOOTSTRAP=	${DISTNAME}-NetBSDi386-boot.tar.bz2
TARGET=		NetBSDi386
TARGETDIR=	netbsd-1
WORDSIZE=	32

.include "../../mk/bsd.pkg.mk"
