# $NetBSD$

VERSION=	20050108
DISTNAME=	mg_MG
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Malagasy dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
