# $NetBSD$
#

DISTNAME=	parsec-3.0.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.cs.uu.nl/~daan/parsec.html
COMMENT=	Monadic parser combinators

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
