# $NetBSD$

DISTNAME=	json-0.7
CATEGORIES=	converters

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Support for serialising Haskell to and from JSON
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
