# $NetBSD$
#

DISTNAME=	NumInstances-1.3
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	https://github.com/conal/NumInstances
COMMENT=	Instances of numeric classes for functions and tuples
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
