# $NetBSD$

DISTNAME=	comonads-fd-3.0.3
CATEGORIES=	math

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Comonad transformers using functional dependencies
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-comonad/buildlink3.mk"
.include "../../wip/hs-comonad-transformers/buildlink3.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-semigroups/buildlink3.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
