# $NetBSD$
#

DISTNAME=	dependent-sum-0.2.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Dependent sum type
LICENSE=	public-domain

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
