# $NetBSD$
#

ISC_DHCP_TYPE=		dhcpd

COMMENT=		ISC Dynamic Host Configuration Protocol (DHCP) Server

CONFLICTS=		cmu-dhcpd-[0-9]* # same manual page filenames

.include "../../wip/isc-dhcpd/Makefile.common"
.include "../../mk/bsd.pkg.mk"
