# $NetBSD$
#

PEAR_CHANNEL=		pear.pdepend.org
PEAR_CHANNEL_ALIAS=	pdepend
PEAR_CHANNEL_VERSION=	2013.07.13

MAINTAINER=		noud4@home.nl

.include "../../wip/mk/pear-channel.mk"
.include "../../mk/bsd.pkg.mk"
