# $NetBSD$
#

DISTNAME=	data-default-0.5.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Class for types with a default value
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-dlist/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
