# $NetBSD$

DISTNAME=	netcat-0.7.0
PKGNAME=	gnetcat-0.7.0
CATEGORIES=	net www
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=netcat/}

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://netcat.sourceforge.net/
COMMENT=	Read and write data across network connections

GNU_CONFIGURE=		YES
USE_BUILDLINK2=		YES
USE_PERL5=		YES

USE_NEW_TEXINFO=	YES
INFO_FILES=		netcat.info

.include "../../mk/bsd.pkg.mk"
