# $NetBSD$

DISTNAME=	hslua-0.3.6.1
CATEGORIES=	lang

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Lua language interpreter embedding in Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
