# $NetBSD$

DISTNAME=	atmark-0.6.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc python
MASTER_SITES=	https://pypi.python.org/packages/source/a/atmark/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://pypi.python.org/packages/source/a/atmark/
COMMENT=	Awk/Sed for humans
LICENSE=	modified-bsd

WRKSRC=		${WRKDIR}/atmark-0.6.0

USE_LANGUAGES=	# none
PYDISTUTILSPKG= yes

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
