# $NetBSD$

DISTNAME=	xfce4-dev-tools-4.3.90.2
CATEGORIES=	devel
MASTER_SITES=	http://www.xfce.org/archive/xfce-4.3.90.2/src/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	martti@NetBSD.org
HOMEPAGE=	http://www.xfce.org/
COMMENT=	Xfce development tools

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
