# $NetBSD$
#

DISTNAME=	feynmf
PKGNAME=	tex-${DISTNAME}-1.08

MAINTAINER=	kamelderouiche@yahoo.com
COMMENT=	Set of LaTeX macros for creating Feynman diagrams

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
