# $NetBSD$
# TeX Live Revision 14095

DISTNAME=	texdoc.doc
PKGNAME=	tex-${DISTNAME:S/./-/}-2009.14095

MAINTAINER=	minskim@NetBSD.org
COMMENT=	Documentation for tex-texdoc
LICENSE=	gnu-gpl-v3

CONFLICTS+=	teTeX-texmf-[0-9]*

.include "../../wip/mk/tlpkg.mk"
.include "../../mk/bsd.pkg.mk"
