# $NetBSD$
#

DISTNAME=	dash-0.5.4
CATEGORIES=	wip
MASTER_SITES=	http://gondor.apana.org.au/~herbert/dash/files/

MAINTAINER=	christtrekker@users.sourceforge.net
HOMEPAGE=	http://gondor.apana.org.au/~herbert/dash/files/
COMMENT=	Debian Almquist shell, POSIX-compliant shell faster than bash

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
