# $NetBSD$
#
# Do NOT put a PKGREVISION statement in this file!
# used by wip/xspdapp/Makefile

XSPDVERSION=		6.3.1
XSPDISTID=		051219
XSPSYSID=		${XSPDISTID}
CATEGORIES=		www
MAINTAINER=		kcf@users.sourceforge.net
HOMEPAGE=		http://home.arcor.de/joachimschulze/xsp/

DISTNAME=		xspsrc_${XSPDISTID}_tar
MASTER_SITES=		http://home.arcor.de/joachimschulze/xsp/download/
EXTRACT_SUFX=		.tgz
