# $NetBSD$

VERSION=	20050108
DISTNAME=	ny_MW
MAINTAINER=	adam.hoka@gmail.com
COMMENT=	Chichewa dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
