# $NetBSD$

VERSION=	20050108
DISTNAME=	ny_MW
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Chichewa dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
