# $NetBSD$

BUILDLINK_TREE+=	grass

.if !defined(GRASS_BUILDLINK3_MK)
GRASS_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.grass+=	grass>=6.3.0
BUILDLINK_PKGSRCDIR.grass?=	../../wip/grass

.endif	# GRASS_BUILDLINK3_MK

BUILDLINK_TREE+=	-grass
