# $NetBSD$

DISTNAME=	aeneas-1.2
CATEGORIES=	misc
MASTER_SITES=	${MASTER_SITE_GNU:=aeneas/}
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	schwarz@NetBSD.org
HOMEPAGE=	http://www.gnu.org/software/aeneas/
COMMENT=	3D Monte Carlo simulation software for submicron semiconductor devices

GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"
