# $NetBSD$

DISTNAME=	rcm-1.2.3
CATEGORIES=	sysutils
MASTER_SITES=	http://thoughtbot.github.io/rcm/dist/

HOMEPAGE=	https://thoughtbot.github.io/rcm/
COMMENT=	Tools for rc file (dotfile) management
LICENSE=	modified-bsd

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
