# $NetBSD$

DISTNAME=	unordered-containers-0.2.4.0
CATEGORIES=	devel
LICENSE=	modified-bsd

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficient hashing-based container types

.include "../../mk/haskell.mk"
.include "../../wip/hs-hashable/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
