# $NetBSD$
#

DISTNAME=	unordered-containers-0.2.3.3
CATEGORIES=	devel
LICENSE=	modified-bsd

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficient hashing-based container types

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-hashable/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
