# $NetBSD$
#

DISTNAME=	dmidecode-2.3
CATEGORIES=	sysutils
MASTER_SITES=	http://savannah.gnu.org/download/dmidecode/

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://www.nongnu.org/dmidecode/
COMMENT=	Print out DMI (SMBIOS) table in human-readable format

USE_BUILDLINK3=		yes
USE_GNU_TOOLS+=		make
ONLY_FOR_PLATFORM=	*-*-i386 *-*-x86

.include "../../mk/bsd.pkg.mk"
