# $NetBSD$
#

DISTNAME=	dmidecode-2.2
CATEGORIES=	sysutils
MASTER_SITES=	http://savannah.gnu.org/download/dmidecode/dmidecode.pkg/2.2/

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://www.nongnu.org/dmidecode/
COMMENT=	Print out DMI (SMBIOS) table in human-readable format

USE_BUILDLINK2=		yes
USE_GMAKE=		yes
ONLY_FOR_PLATFORM=	*-*-i386 *-*-x86

.include "../../mk/bsd.pkg.mk"
