# $NetBSD$

DISTNAME=	cvsproxy-1.0.1
CATEGORIES=	net
MASTER_SITES=	http://www.sra.co.jp/people/m-kasahr/cvsproxy/src/

MAINTAINER=	oht@users.sourceforge.net
HOMEPAGE=	http://www.sra.co.jp/people/m-kasahr/cvsproxy/
COMMENT=	The cvsproxy is a relay server for the cvs pserver protocol

PKG_DESTDIR_SUPPORT=	none

GNU_CONFIGURE=	YES
USE_TOOLS+=		autoconf automake

.include "../../mk/bsd.pkg.mk"
