# $NetBSD$
#

DISTNAME=		libmemcache-1.4.0.b5
PKGNAME=		libmemcache-1.3.99
CATEGORIES=		devel
MASTER_SITES=		http://people.freebsd.org/~seanc/libmemcache/
EXTRACT_SUFX=		.tar.bz2

MAINTAINER=		elvstone@gmail.com
HOMEPAGE=		http://people.freebsd.org/~seanc/libmemcache/
COMMENT=		C API for memcached

USE_PKGLOCALEDIR=	yes
USE_LIBTOOL=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
