# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBDBI_BUILDLINK3_MK:=	${LIBDBI_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libdbi
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdbi}
BUILDLINK_PACKAGES+=	libdbi
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libdbi

.if ${LIBDBI_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libdbi+=	libdbi>=0.8.3
BUILDLINK_PKGSRCDIR.libdbi?=	../../wip/libdbi
.endif	# LIBDBI_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
