# $NetBSD: Makefile,v 1.13 2007/03/07 21:32:53 dmcmahill Exp $

MOZILLA=	thunderbird-gtk1

COMMENT=	Mozilla mail client using the older GTK1 toolkit

.include "../../wip/thunderbird2/Makefile-thunderbird.common"
.include "../../mk/bsd.pkg.mk"
