# $NetBSD: Makefile,v 1.9 2006/04/23 14:14:07 ghen Exp $

MOZILLA=	thunderbird2-gtk1

COMMENT=	Mozilla mail client using the older GTK1 toolkit

.include "../../wip/thunderbird2/Makefile-thunderbird.common"
.include "../../mk/bsd.pkg.mk"
