# $NetBSD$
#

DISTNAME=	vte-0.12.1
CATEGORIES=	x11

MAINTAINER=	pho@cielonegro.org
COMMENT=	Binding to the VTE library
LICENSE=	gnu-lgpl-v2.1

.include "../../wip/mk/haskell.mk"
.include "../../wip/gtk2hs-buildtools/buildlink3.mk"
.include "../../wip/hs-glib/buildlink3.mk"
.include "../../wip/hs-gtk/buildlink3.mk"
.include "../../wip/hs-pango/buildlink3.mk"
.include "../../x11/vte/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
