# $NetBSD$
#

DISTNAME=	itstool-1.1.1
CATEGORIES=	converters
MASTER_SITES=	http://files.itstool.org/itstool/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://itstool.org/
COMMENT=	Tool for translating XML documents with PO files
LICENSE=	gnu-gpl-v3

GNU_CONFIGURE=	yes
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
