# $NetBSD$
#

DISTNAME=	core-0.5
CATEGORIES=	lang

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell external core parser and pretty printer
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../textproc/hs-parsec/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
