# $NetBSD$
#

DISTNAME=	libdsk-1.3.3
CATEGORIES=	sysutils
MASTER_SITES=	http://www.seasip.info/Unix/LibDsk/

MAINTAINER=	shattered@NetBSD.org
HOMEPAGE=	http://www.seasip.info/Unix/LibDsk/
COMMENT=	Library for accessing floppy discs and disc image files
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c
USE_LIBTOOL=	yes

.include "../../mk/bsd.pkg.mk"
