# $NetBSD$
#

DISTNAME=	largeword-1.0.4
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Provides Word128, Word192 and Word256 and other large words
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
