# $NetBSD$

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GTKGLK_BUILDLINK3_MK:=	${GTKGLK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gtkglk
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngtkglk}
BUILDLINK_PACKAGES+=	gtkglk

.if !empty(GTKGLK_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.gtkglk+=	gtkglk>=0.2
BUILDLINK_PKGSRCDIR.gtkglk?=	../../wip/gtkglk
.endif	# GTKGLK_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
