# $NetBSD: Makefile,v 1.15 2005/04/11 21:45:31 tv Exp $
#

DISTNAME=		Date-Simple-3.02
PKGNAME=		p5-${DISTNAME}
CATEGORIES=		devel perl5
MASTER_SITES=		${MASTER_SITE_PERL_CPAN:=Date/}

MAINTAINER=	geeogeegeeoh@users.sourceforge.net
COMMENT=		A simple date object

PERL5_PACKLIST=         ${PERL5_SITEARCH}/auto/Date/Simple/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"

