# $NetBSD$
#

DISTNAME=	Cabal-1.6.0.3
CATEGORIES=	devel

MAINTAINER=	esg@sdf.lonestar.org
COMMENT=	Haskell common architecture for building applications and libraries

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
