# $NetBSD$
#

DISTNAME=	Cabal-1.6.0.3
CATEGORIES=	devel

MAINTAINER=	emil@math.su.se
COMMENT=	Haskell common architecture for building applications and libraries

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
