# $NetBSD$
#

DISTNAME=	Cabal-1.16.0.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Framework for packaging Haskell software
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
