# $NetBSD$

DISTNAME=		libixp
PKGNAME=		libixp-20061105
CATEGORIES=		devel
MASTER_SITES=		http://perso.orange.fr/kh.p/pkgsrc/

MAINTAINER=		kh.p@no-log.org
HOMEPAGE=		http://libs.suckless.org/
COMMENT=		Standalone client/server 9P library

NO_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
