# $NetBSD$
#

DISTNAME=		mp3chop-1.08
CATEGORIES=		audio
MASTER_SITES=		http://www.fysh.org/~mac/mp3chop/

MAINTAINER=		shattered@users.sourceforge.net
HOMEPAGE=		http://www.fysh.org/~mac/mp3chop/
COMMENT=		Program for chopping up mp3 files

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes
USE_LANGUAGES=		c c++

.include "../../mk/bsd.pkg.mk"
