# $NetBSD$

DISTNAME=	ocamlify-0.0.2
CATEGORIES=	devel
MASTER_SITES=	http://forge.ocamlcore.org/frs/download.php/1209/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://forge.ocamlcore.org/projects/ocamlify/
COMMENT=	Allows embedding external resources as OCaml code
LICENSE=	gnu-lgpl-v2.1

.include "../../wip/mk/ocaml-oasis.mk"
.include "../../mk/bsd.pkg.mk"
