# $NetBSD$

DISTNAME=	wkf-1.3.9
CATEGORIES=	japanese converters
MASTER_SITES=	http://www.mysticwall.com/download/

MAINTAINER=	obata@lins.jp
HOMEPAGE=	http://www.mysticwall.com/software/wkf/index.html
COMMENT=	WALL's Kanji Filter

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
