# $NetBSD$

DISTNAME=	wkf-1.3.11
CATEGORIES=	japanese converters
MASTER_SITES=	http://www.mysticwall.com/download/

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	http://www.mysticwall.com/software/wkf/index.html
COMMENT=	WALL's Kanji Filter

PKG_DESTDIR_SUPPORT= 	none

GNU_CONFIGURE=	yes

TEST_TARGET=	test

.include "../../mk/bsd.pkg.mk"
