# $NetBSD$
#

DISTNAME=	time-1.1.2.2
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://semantic.org/TimeLib/
COMMENT=	Haskell time library

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
