# $NetBSD$
#

DISTNAME=	time-1.1.2.4
CATEGORIES=	time

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://semantic.org/TimeLib/
COMMENT=	Haskell time library

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
