# $NetBSD$

DISTNAME=	constraints-0.3.4.2
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Constraint manipulation
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-newtype/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
